package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TbsubdictId generated by hbm2java
 */
public class TbsubdictId implements java.io.Serializable {

	private String hsKey;
	private String val;
	private String subItem;
	private BigDecimal sceneNo;

	public TbsubdictId() {
	}

	public TbsubdictId(String hsKey, String val, String subItem,
			BigDecimal sceneNo) {
		this.hsKey = hsKey;
		this.val = val;
		this.subItem = subItem;
		this.sceneNo = sceneNo;
	}

	public String getHsKey() {
		return this.hsKey;
	}

	public void setHsKey(String hsKey) {
		this.hsKey = hsKey;
	}

	public String getVal() {
		return this.val;
	}

	public void setVal(String val) {
		this.val = val;
	}

	public String getSubItem() {
		return this.subItem;
	}

	public void setSubItem(String subItem) {
		this.subItem = subItem;
	}

	public BigDecimal getSceneNo() {
		return this.sceneNo;
	}

	public void setSceneNo(BigDecimal sceneNo) {
		this.sceneNo = sceneNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbsubdictId))
			return false;
		TbsubdictId castOther = (TbsubdictId) other;

		return ((this.getHsKey() == castOther.getHsKey()) || (this.getHsKey() != null
				&& castOther.getHsKey() != null && this.getHsKey().equals(
				castOther.getHsKey())))
				&& ((this.getVal() == castOther.getVal()) || (this.getVal() != null
						&& castOther.getVal() != null && this.getVal().equals(
						castOther.getVal())))
				&& ((this.getSubItem() == castOther.getSubItem()) || (this
						.getSubItem() != null && castOther.getSubItem() != null && this
						.getSubItem().equals(castOther.getSubItem())))
				&& ((this.getSceneNo() == castOther.getSceneNo()) || (this
						.getSceneNo() != null && castOther.getSceneNo() != null && this
						.getSceneNo().equals(castOther.getSceneNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHsKey() == null ? 0 : this.getHsKey().hashCode());
		result = 37 * result
				+ (getVal() == null ? 0 : this.getVal().hashCode());
		result = 37 * result
				+ (getSubItem() == null ? 0 : this.getSubItem().hashCode());
		result = 37 * result
				+ (getSceneNo() == null ? 0 : this.getSceneNo().hashCode());
		return result;
	}

}
