package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbsubdict generated by hbm2java
 */
public class Tbsubdict implements java.io.Serializable {

	private TbsubdictId id;
	private String sceneDescr;
	private String subItemName;

	public Tbsubdict() {
	}

	public Tbsubdict(TbsubdictId id, String sceneDescr, String subItemName) {
		this.id = id;
		this.sceneDescr = sceneDescr;
		this.subItemName = subItemName;
	}

	public TbsubdictId getId() {
		return this.id;
	}

	public void setId(TbsubdictId id) {
		this.id = id;
	}

	public String getSceneDescr() {
		return this.sceneDescr;
	}

	public void setSceneDescr(String sceneDescr) {
		this.sceneDescr = sceneDescr;
	}

	public String getSubItemName() {
		return this.subItemName;
	}

	public void setSubItemName(String subItemName) {
		this.subItemName = subItemName;
	}

}
