package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbsyscustinfo generated by hbm2java
 */
public class Tbsyscustinfo implements java.io.Serializable {

	private String custNo;
	private String custType1;
	private String custFullname;
	private String custName;
	private String outerAppraise;
	private String innerAppraise;
	private String generalAppraise;
	private String registration;
	private String custStauts;
	private String license1;
	private String license2;
	private String license3;
	private String corporation;
	private String address;
	private String zipCode;
	private String isHeadoffice;
	private String upCustNo;
	private String bankNo;
	private String cfetsNo;
	private String flag;
	private String pym;
	private String coreCustNo;
	private String creditCustNo;
	private String custClass1;
	private String custClass2;
	private String financialClass1;
	private String financialClass2;
	private String financialNo1;
	private String financialNo2;
	private String bankBic;
	private String hvpsNo;
	private String reserve1;
	private String reserve2;

	public Tbsyscustinfo() {
	}

	public Tbsyscustinfo(String custNo, String custType1, String custFullname,
			String custName, String outerAppraise, String innerAppraise,
			String generalAppraise, String registration, String custStauts,
			String license1, String license2, String license3,
			String corporation, String address, String zipCode,
			String isHeadoffice, String upCustNo, String bankNo,
			String cfetsNo, String flag, String pym, String coreCustNo,
			String creditCustNo, String custClass1, String custClass2,
			String financialClass1, String financialClass2,
			String financialNo1, String financialNo2, String bankBic,
			String hvpsNo, String reserve1, String reserve2) {
		this.custNo = custNo;
		this.custType1 = custType1;
		this.custFullname = custFullname;
		this.custName = custName;
		this.outerAppraise = outerAppraise;
		this.innerAppraise = innerAppraise;
		this.generalAppraise = generalAppraise;
		this.registration = registration;
		this.custStauts = custStauts;
		this.license1 = license1;
		this.license2 = license2;
		this.license3 = license3;
		this.corporation = corporation;
		this.address = address;
		this.zipCode = zipCode;
		this.isHeadoffice = isHeadoffice;
		this.upCustNo = upCustNo;
		this.bankNo = bankNo;
		this.cfetsNo = cfetsNo;
		this.flag = flag;
		this.pym = pym;
		this.coreCustNo = coreCustNo;
		this.creditCustNo = creditCustNo;
		this.custClass1 = custClass1;
		this.custClass2 = custClass2;
		this.financialClass1 = financialClass1;
		this.financialClass2 = financialClass2;
		this.financialNo1 = financialNo1;
		this.financialNo2 = financialNo2;
		this.bankBic = bankBic;
		this.hvpsNo = hvpsNo;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	public String getCustType1() {
		return this.custType1;
	}

	public void setCustType1(String custType1) {
		this.custType1 = custType1;
	}

	public String getCustFullname() {
		return this.custFullname;
	}

	public void setCustFullname(String custFullname) {
		this.custFullname = custFullname;
	}

	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getOuterAppraise() {
		return this.outerAppraise;
	}

	public void setOuterAppraise(String outerAppraise) {
		this.outerAppraise = outerAppraise;
	}

	public String getInnerAppraise() {
		return this.innerAppraise;
	}

	public void setInnerAppraise(String innerAppraise) {
		this.innerAppraise = innerAppraise;
	}

	public String getGeneralAppraise() {
		return this.generalAppraise;
	}

	public void setGeneralAppraise(String generalAppraise) {
		this.generalAppraise = generalAppraise;
	}

	public String getRegistration() {
		return this.registration;
	}

	public void setRegistration(String registration) {
		this.registration = registration;
	}

	public String getCustStauts() {
		return this.custStauts;
	}

	public void setCustStauts(String custStauts) {
		this.custStauts = custStauts;
	}

	public String getLicense1() {
		return this.license1;
	}

	public void setLicense1(String license1) {
		this.license1 = license1;
	}

	public String getLicense2() {
		return this.license2;
	}

	public void setLicense2(String license2) {
		this.license2 = license2;
	}

	public String getLicense3() {
		return this.license3;
	}

	public void setLicense3(String license3) {
		this.license3 = license3;
	}

	public String getCorporation() {
		return this.corporation;
	}

	public void setCorporation(String corporation) {
		this.corporation = corporation;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getIsHeadoffice() {
		return this.isHeadoffice;
	}

	public void setIsHeadoffice(String isHeadoffice) {
		this.isHeadoffice = isHeadoffice;
	}

	public String getUpCustNo() {
		return this.upCustNo;
	}

	public void setUpCustNo(String upCustNo) {
		this.upCustNo = upCustNo;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	public String getCfetsNo() {
		return this.cfetsNo;
	}

	public void setCfetsNo(String cfetsNo) {
		this.cfetsNo = cfetsNo;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getPym() {
		return this.pym;
	}

	public void setPym(String pym) {
		this.pym = pym;
	}

	public String getCoreCustNo() {
		return this.coreCustNo;
	}

	public void setCoreCustNo(String coreCustNo) {
		this.coreCustNo = coreCustNo;
	}

	public String getCreditCustNo() {
		return this.creditCustNo;
	}

	public void setCreditCustNo(String creditCustNo) {
		this.creditCustNo = creditCustNo;
	}

	public String getCustClass1() {
		return this.custClass1;
	}

	public void setCustClass1(String custClass1) {
		this.custClass1 = custClass1;
	}

	public String getCustClass2() {
		return this.custClass2;
	}

	public void setCustClass2(String custClass2) {
		this.custClass2 = custClass2;
	}

	public String getFinancialClass1() {
		return this.financialClass1;
	}

	public void setFinancialClass1(String financialClass1) {
		this.financialClass1 = financialClass1;
	}

	public String getFinancialClass2() {
		return this.financialClass2;
	}

	public void setFinancialClass2(String financialClass2) {
		this.financialClass2 = financialClass2;
	}

	public String getFinancialNo1() {
		return this.financialNo1;
	}

	public void setFinancialNo1(String financialNo1) {
		this.financialNo1 = financialNo1;
	}

	public String getFinancialNo2() {
		return this.financialNo2;
	}

	public void setFinancialNo2(String financialNo2) {
		this.financialNo2 = financialNo2;
	}

	public String getBankBic() {
		return this.bankBic;
	}

	public void setBankBic(String bankBic) {
		this.bankBic = bankBic;
	}

	public String getHvpsNo() {
		return this.hvpsNo;
	}

	public void setHvpsNo(String hvpsNo) {
		this.hvpsNo = hvpsNo;
	}

	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
