package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TbsysteminfoId generated by hbm2java
 */
public class TbsysteminfoId implements java.io.Serializable {

	private String consumerNo;
	private String consumerName;
	private String productNo;
	private String productName;
	private String productVersionNo;
	private BigDecimal lastInitDate;
	private BigDecimal initDate;
	private String initializtionFlag;
	private BigDecimal timeZone;
	private BigDecimal archiveDate;
	private String businStatus;
	private String openBusinFlag;
	private String reserve1;
	private String reserve2;

	public TbsysteminfoId() {
	}

	public TbsysteminfoId(String consumerNo, String consumerName,
			String productNo, String productName, String productVersionNo,
			BigDecimal lastInitDate, BigDecimal initDate,
			String initializtionFlag, BigDecimal timeZone,
			BigDecimal archiveDate, String businStatus, String openBusinFlag,
			String reserve1, String reserve2) {
		this.consumerNo = consumerNo;
		this.consumerName = consumerName;
		this.productNo = productNo;
		this.productName = productName;
		this.productVersionNo = productVersionNo;
		this.lastInitDate = lastInitDate;
		this.initDate = initDate;
		this.initializtionFlag = initializtionFlag;
		this.timeZone = timeZone;
		this.archiveDate = archiveDate;
		this.businStatus = businStatus;
		this.openBusinFlag = openBusinFlag;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	public String getConsumerNo() {
		return this.consumerNo;
	}

	public void setConsumerNo(String consumerNo) {
		this.consumerNo = consumerNo;
	}

	public String getConsumerName() {
		return this.consumerName;
	}

	public void setConsumerName(String consumerName) {
		this.consumerName = consumerName;
	}

	public String getProductNo() {
		return this.productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getProductVersionNo() {
		return this.productVersionNo;
	}

	public void setProductVersionNo(String productVersionNo) {
		this.productVersionNo = productVersionNo;
	}

	public BigDecimal getLastInitDate() {
		return this.lastInitDate;
	}

	public void setLastInitDate(BigDecimal lastInitDate) {
		this.lastInitDate = lastInitDate;
	}

	public BigDecimal getInitDate() {
		return this.initDate;
	}

	public void setInitDate(BigDecimal initDate) {
		this.initDate = initDate;
	}

	public String getInitializtionFlag() {
		return this.initializtionFlag;
	}

	public void setInitializtionFlag(String initializtionFlag) {
		this.initializtionFlag = initializtionFlag;
	}

	public BigDecimal getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(BigDecimal timeZone) {
		this.timeZone = timeZone;
	}

	public BigDecimal getArchiveDate() {
		return this.archiveDate;
	}

	public void setArchiveDate(BigDecimal archiveDate) {
		this.archiveDate = archiveDate;
	}

	public String getBusinStatus() {
		return this.businStatus;
	}

	public void setBusinStatus(String businStatus) {
		this.businStatus = businStatus;
	}

	public String getOpenBusinFlag() {
		return this.openBusinFlag;
	}

	public void setOpenBusinFlag(String openBusinFlag) {
		this.openBusinFlag = openBusinFlag;
	}

	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbsysteminfoId))
			return false;
		TbsysteminfoId castOther = (TbsysteminfoId) other;

		return ((this.getConsumerNo() == castOther.getConsumerNo()) || (this
				.getConsumerNo() != null && castOther.getConsumerNo() != null && this
				.getConsumerNo().equals(castOther.getConsumerNo())))
				&& ((this.getConsumerName() == castOther.getConsumerName()) || (this
						.getConsumerName() != null
						&& castOther.getConsumerName() != null && this
						.getConsumerName().equals(castOther.getConsumerName())))
				&& ((this.getProductNo() == castOther.getProductNo()) || (this
						.getProductNo() != null
						&& castOther.getProductNo() != null && this
						.getProductNo().equals(castOther.getProductNo())))
				&& ((this.getProductName() == castOther.getProductName()) || (this
						.getProductName() != null
						&& castOther.getProductName() != null && this
						.getProductName().equals(castOther.getProductName())))
				&& ((this.getProductVersionNo() == castOther
						.getProductVersionNo()) || (this.getProductVersionNo() != null
						&& castOther.getProductVersionNo() != null && this
						.getProductVersionNo().equals(
								castOther.getProductVersionNo())))
				&& ((this.getLastInitDate() == castOther.getLastInitDate()) || (this
						.getLastInitDate() != null
						&& castOther.getLastInitDate() != null && this
						.getLastInitDate().equals(castOther.getLastInitDate())))
				&& ((this.getInitDate() == castOther.getInitDate()) || (this
						.getInitDate() != null
						&& castOther.getInitDate() != null && this
						.getInitDate().equals(castOther.getInitDate())))
				&& ((this.getInitializtionFlag() == castOther
						.getInitializtionFlag()) || (this
						.getInitializtionFlag() != null
						&& castOther.getInitializtionFlag() != null && this
						.getInitializtionFlag().equals(
								castOther.getInitializtionFlag())))
				&& ((this.getTimeZone() == castOther.getTimeZone()) || (this
						.getTimeZone() != null
						&& castOther.getTimeZone() != null && this
						.getTimeZone().equals(castOther.getTimeZone())))
				&& ((this.getArchiveDate() == castOther.getArchiveDate()) || (this
						.getArchiveDate() != null
						&& castOther.getArchiveDate() != null && this
						.getArchiveDate().equals(castOther.getArchiveDate())))
				&& ((this.getBusinStatus() == castOther.getBusinStatus()) || (this
						.getBusinStatus() != null
						&& castOther.getBusinStatus() != null && this
						.getBusinStatus().equals(castOther.getBusinStatus())))
				&& ((this.getOpenBusinFlag() == castOther.getOpenBusinFlag()) || (this
						.getOpenBusinFlag() != null
						&& castOther.getOpenBusinFlag() != null && this
						.getOpenBusinFlag()
						.equals(castOther.getOpenBusinFlag())))
				&& ((this.getReserve1() == castOther.getReserve1()) || (this
						.getReserve1() != null
						&& castOther.getReserve1() != null && this
						.getReserve1().equals(castOther.getReserve1())))
				&& ((this.getReserve2() == castOther.getReserve2()) || (this
						.getReserve2() != null
						&& castOther.getReserve2() != null && this
						.getReserve2().equals(castOther.getReserve2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConsumerNo() == null ? 0 : this.getConsumerNo()
						.hashCode());
		result = 37
				* result
				+ (getConsumerName() == null ? 0 : this.getConsumerName()
						.hashCode());
		result = 37 * result
				+ (getProductNo() == null ? 0 : this.getProductNo().hashCode());
		result = 37
				* result
				+ (getProductName() == null ? 0 : this.getProductName()
						.hashCode());
		result = 37
				* result
				+ (getProductVersionNo() == null ? 0 : this
						.getProductVersionNo().hashCode());
		result = 37
				* result
				+ (getLastInitDate() == null ? 0 : this.getLastInitDate()
						.hashCode());
		result = 37 * result
				+ (getInitDate() == null ? 0 : this.getInitDate().hashCode());
		result = 37
				* result
				+ (getInitializtionFlag() == null ? 0 : this
						.getInitializtionFlag().hashCode());
		result = 37 * result
				+ (getTimeZone() == null ? 0 : this.getTimeZone().hashCode());
		result = 37
				* result
				+ (getArchiveDate() == null ? 0 : this.getArchiveDate()
						.hashCode());
		result = 37
				* result
				+ (getBusinStatus() == null ? 0 : this.getBusinStatus()
						.hashCode());
		result = 37
				* result
				+ (getOpenBusinFlag() == null ? 0 : this.getOpenBusinFlag()
						.hashCode());
		result = 37 * result
				+ (getReserve1() == null ? 0 : this.getReserve1().hashCode());
		result = 37 * result
				+ (getReserve2() == null ? 0 : this.getReserve2().hashCode());
		return result;
	}

}
