package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbsyscustaccount generated by hbm2java
 */
public class Tbsyscustaccount implements java.io.Serializable {

	private TbsyscustaccountId id;
	private String bondAccountname;
	private String bondAccountProperty;

	public Tbsyscustaccount() {
	}

	public Tbsyscustaccount(TbsyscustaccountId id, String bondAccountname,
			String bondAccountProperty) {
		this.id = id;
		this.bondAccountname = bondAccountname;
		this.bondAccountProperty = bondAccountProperty;
	}

	public TbsyscustaccountId getId() {
		return this.id;
	}

	public void setId(TbsyscustaccountId id) {
		this.id = id;
	}

	public String getBondAccountname() {
		return this.bondAccountname;
	}

	public void setBondAccountname(String bondAccountname) {
		this.bondAccountname = bondAccountname;
	}

	public String getBondAccountProperty() {
		return this.bondAccountProperty;
	}

	public void setBondAccountProperty(String bondAccountProperty) {
		this.bondAccountProperty = bondAccountProperty;
	}

}
