package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbsysteminfo generated by hbm2java
 */
public class Tbsysteminfo implements java.io.Serializable {

	private TbsysteminfoId id;

	public Tbsysteminfo() {
	}

	public Tbsysteminfo(TbsysteminfoId id) {
		this.id = id;
	}

	public TbsysteminfoId getId() {
		return this.id;
	}

	public void setId(TbsysteminfoId id) {
		this.id = id;
	}

}
