package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TbtaskpoolId generated by hbm2java
 */
public class TbtaskpoolId implements java.io.Serializable {

	private String marketCode;
	private String taskCode;
	private String parentTaskCode;

	public TbtaskpoolId() {
	}

	public TbtaskpoolId(String marketCode, String taskCode,
			String parentTaskCode) {
		this.marketCode = marketCode;
		this.taskCode = taskCode;
		this.parentTaskCode = parentTaskCode;
	}

	public String getMarketCode() {
		return this.marketCode;
	}

	public void setMarketCode(String marketCode) {
		this.marketCode = marketCode;
	}

	public String getTaskCode() {
		return this.taskCode;
	}

	public void setTaskCode(String taskCode) {
		this.taskCode = taskCode;
	}

	public String getParentTaskCode() {
		return this.parentTaskCode;
	}

	public void setParentTaskCode(String parentTaskCode) {
		this.parentTaskCode = parentTaskCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbtaskpoolId))
			return false;
		TbtaskpoolId castOther = (TbtaskpoolId) other;

		return ((this.getMarketCode() == castOther.getMarketCode()) || (this
				.getMarketCode() != null && castOther.getMarketCode() != null && this
				.getMarketCode().equals(castOther.getMarketCode())))
				&& ((this.getTaskCode() == castOther.getTaskCode()) || (this
						.getTaskCode() != null
						&& castOther.getTaskCode() != null && this
						.getTaskCode().equals(castOther.getTaskCode())))
				&& ((this.getParentTaskCode() == castOther.getParentTaskCode()) || (this
						.getParentTaskCode() != null
						&& castOther.getParentTaskCode() != null && this
						.getParentTaskCode().equals(
								castOther.getParentTaskCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getMarketCode() == null ? 0 : this.getMarketCode()
						.hashCode());
		result = 37 * result
				+ (getTaskCode() == null ? 0 : this.getTaskCode().hashCode());
		result = 37
				* result
				+ (getParentTaskCode() == null ? 0 : this.getParentTaskCode()
						.hashCode());
		return result;
	}

}
