package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Tbtaskpool generated by hbm2java
 */
public class Tbtaskpool implements java.io.Serializable {

	private TbtaskpoolId id;
	private String taskName;
	private String actionClass;
	private String serialNo;
	private BigDecimal parentTaskNum;
	private String taskPage;
	private String taskType;
	private BigDecimal taskRow;
	private BigDecimal taskColumn;
	private String redoFlag;
	private String delayFlag;
	private String delayTime;
	private String opCode;
	private BigDecimal opTimes;
	private String dealStatus;
	private String stopDealFlag;
	private BigDecimal excutePercentage;
	private String errCode;
	private String errMsg;
	private String warnFlag;
	private String warnMsg;
	private BigDecimal beginTime;
	private BigDecimal endTime;
	private BigDecimal holdTime;
	private BigDecimal lastTransDate;
	private String transToSub;
	private String transToSub2;
	private String detailUrl;
	private String reserve1;
	private String reserve2;

	public Tbtaskpool() {
	}

	public Tbtaskpool(TbtaskpoolId id, String taskName, String actionClass,
			String serialNo, BigDecimal parentTaskNum, String taskPage,
			String taskType, BigDecimal taskRow, BigDecimal taskColumn,
			String redoFlag, String delayFlag, String delayTime, String opCode,
			BigDecimal opTimes, String dealStatus, String stopDealFlag,
			BigDecimal excutePercentage, String errCode, String errMsg,
			String warnFlag, String warnMsg, BigDecimal beginTime,
			BigDecimal endTime, BigDecimal holdTime, BigDecimal lastTransDate,
			String transToSub, String transToSub2, String detailUrl,
			String reserve1, String reserve2) {
		this.id = id;
		this.taskName = taskName;
		this.actionClass = actionClass;
		this.serialNo = serialNo;
		this.parentTaskNum = parentTaskNum;
		this.taskPage = taskPage;
		this.taskType = taskType;
		this.taskRow = taskRow;
		this.taskColumn = taskColumn;
		this.redoFlag = redoFlag;
		this.delayFlag = delayFlag;
		this.delayTime = delayTime;
		this.opCode = opCode;
		this.opTimes = opTimes;
		this.dealStatus = dealStatus;
		this.stopDealFlag = stopDealFlag;
		this.excutePercentage = excutePercentage;
		this.errCode = errCode;
		this.errMsg = errMsg;
		this.warnFlag = warnFlag;
		this.warnMsg = warnMsg;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.holdTime = holdTime;
		this.lastTransDate = lastTransDate;
		this.transToSub = transToSub;
		this.transToSub2 = transToSub2;
		this.detailUrl = detailUrl;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	public TbtaskpoolId getId() {
		return this.id;
	}

	public void setId(TbtaskpoolId id) {
		this.id = id;
	}

	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	public String getActionClass() {
		return this.actionClass;
	}

	public void setActionClass(String actionClass) {
		this.actionClass = actionClass;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public BigDecimal getParentTaskNum() {
		return this.parentTaskNum;
	}

	public void setParentTaskNum(BigDecimal parentTaskNum) {
		this.parentTaskNum = parentTaskNum;
	}

	public String getTaskPage() {
		return this.taskPage;
	}

	public void setTaskPage(String taskPage) {
		this.taskPage = taskPage;
	}

	public String getTaskType() {
		return this.taskType;
	}

	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}

	public BigDecimal getTaskRow() {
		return this.taskRow;
	}

	public void setTaskRow(BigDecimal taskRow) {
		this.taskRow = taskRow;
	}

	public BigDecimal getTaskColumn() {
		return this.taskColumn;
	}

	public void setTaskColumn(BigDecimal taskColumn) {
		this.taskColumn = taskColumn;
	}

	public String getRedoFlag() {
		return this.redoFlag;
	}

	public void setRedoFlag(String redoFlag) {
		this.redoFlag = redoFlag;
	}

	public String getDelayFlag() {
		return this.delayFlag;
	}

	public void setDelayFlag(String delayFlag) {
		this.delayFlag = delayFlag;
	}

	public String getDelayTime() {
		return this.delayTime;
	}

	public void setDelayTime(String delayTime) {
		this.delayTime = delayTime;
	}

	public String getOpCode() {
		return this.opCode;
	}

	public void setOpCode(String opCode) {
		this.opCode = opCode;
	}

	public BigDecimal getOpTimes() {
		return this.opTimes;
	}

	public void setOpTimes(BigDecimal opTimes) {
		this.opTimes = opTimes;
	}

	public String getDealStatus() {
		return this.dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	public String getStopDealFlag() {
		return this.stopDealFlag;
	}

	public void setStopDealFlag(String stopDealFlag) {
		this.stopDealFlag = stopDealFlag;
	}

	public BigDecimal getExcutePercentage() {
		return this.excutePercentage;
	}

	public void setExcutePercentage(BigDecimal excutePercentage) {
		this.excutePercentage = excutePercentage;
	}

	public String getErrCode() {
		return this.errCode;
	}

	public void setErrCode(String errCode) {
		this.errCode = errCode;
	}

	public String getErrMsg() {
		return this.errMsg;
	}

	public void setErrMsg(String errMsg) {
		this.errMsg = errMsg;
	}

	public String getWarnFlag() {
		return this.warnFlag;
	}

	public void setWarnFlag(String warnFlag) {
		this.warnFlag = warnFlag;
	}

	public String getWarnMsg() {
		return this.warnMsg;
	}

	public void setWarnMsg(String warnMsg) {
		this.warnMsg = warnMsg;
	}

	public BigDecimal getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(BigDecimal beginTime) {
		this.beginTime = beginTime;
	}

	public BigDecimal getEndTime() {
		return this.endTime;
	}

	public void setEndTime(BigDecimal endTime) {
		this.endTime = endTime;
	}

	public BigDecimal getHoldTime() {
		return this.holdTime;
	}

	public void setHoldTime(BigDecimal holdTime) {
		this.holdTime = holdTime;
	}

	public BigDecimal getLastTransDate() {
		return this.lastTransDate;
	}

	public void setLastTransDate(BigDecimal lastTransDate) {
		this.lastTransDate = lastTransDate;
	}

	public String getTransToSub() {
		return this.transToSub;
	}

	public void setTransToSub(String transToSub) {
		this.transToSub = transToSub;
	}

	public String getTransToSub2() {
		return this.transToSub2;
	}

	public void setTransToSub2(String transToSub2) {
		this.transToSub2 = transToSub2;
	}

	public String getDetailUrl() {
		return this.detailUrl;
	}

	public void setDetailUrl(String detailUrl) {
		this.detailUrl = detailUrl;
	}

	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
