package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbtempsubaccount generated by hbm2java
 */
public class Tbtempsubaccount implements java.io.Serializable {

	private TbtempsubaccountId id;

	public Tbtempsubaccount() {
	}

	public Tbtempsubaccount(TbtempsubaccountId id) {
		this.id = id;
	}

	public TbtempsubaccountId getId() {
		return this.id;
	}

	public void setId(TbtempsubaccountId id) {
		this.id = id;
	}

}
