package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Tbtempinstrcreditasset generated by hbm2java
 */
public class Tbtempinstrcreditasset implements java.io.Serializable {

	private TbtempinstrcreditassetId id;
	private String creditCode;
	private String assoSerial;
	private BigDecimal oriBeginDate;
	private BigDecimal creditBeginDate;
	private BigDecimal creditEndDate;
	private String payFrequency;
	private String interestFlag;
	private BigDecimal creditPrincipal;
	private BigDecimal interest;
	private BigDecimal realAmount;
	private String memo;

	public Tbtempinstrcreditasset() {
	}

	public Tbtempinstrcreditasset(TbtempinstrcreditassetId id,
			String creditCode, String assoSerial, BigDecimal oriBeginDate,
			BigDecimal creditBeginDate, BigDecimal creditEndDate,
			String payFrequency, String interestFlag,
			BigDecimal creditPrincipal, BigDecimal interest,
			BigDecimal realAmount, String memo) {
		this.id = id;
		this.creditCode = creditCode;
		this.assoSerial = assoSerial;
		this.oriBeginDate = oriBeginDate;
		this.creditBeginDate = creditBeginDate;
		this.creditEndDate = creditEndDate;
		this.payFrequency = payFrequency;
		this.interestFlag = interestFlag;
		this.creditPrincipal = creditPrincipal;
		this.interest = interest;
		this.realAmount = realAmount;
		this.memo = memo;
	}

	public TbtempinstrcreditassetId getId() {
		return this.id;
	}

	public void setId(TbtempinstrcreditassetId id) {
		this.id = id;
	}

	public String getCreditCode() {
		return this.creditCode;
	}

	public void setCreditCode(String creditCode) {
		this.creditCode = creditCode;
	}

	public String getAssoSerial() {
		return this.assoSerial;
	}

	public void setAssoSerial(String assoSerial) {
		this.assoSerial = assoSerial;
	}

	public BigDecimal getOriBeginDate() {
		return this.oriBeginDate;
	}

	public void setOriBeginDate(BigDecimal oriBeginDate) {
		this.oriBeginDate = oriBeginDate;
	}

	public BigDecimal getCreditBeginDate() {
		return this.creditBeginDate;
	}

	public void setCreditBeginDate(BigDecimal creditBeginDate) {
		this.creditBeginDate = creditBeginDate;
	}

	public BigDecimal getCreditEndDate() {
		return this.creditEndDate;
	}

	public void setCreditEndDate(BigDecimal creditEndDate) {
		this.creditEndDate = creditEndDate;
	}

	public String getPayFrequency() {
		return this.payFrequency;
	}

	public void setPayFrequency(String payFrequency) {
		this.payFrequency = payFrequency;
	}

	public String getInterestFlag() {
		return this.interestFlag;
	}

	public void setInterestFlag(String interestFlag) {
		this.interestFlag = interestFlag;
	}

	public BigDecimal getCreditPrincipal() {
		return this.creditPrincipal;
	}

	public void setCreditPrincipal(BigDecimal creditPrincipal) {
		this.creditPrincipal = creditPrincipal;
	}

	public BigDecimal getInterest() {
		return this.interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public BigDecimal getRealAmount() {
		return this.realAmount;
	}

	public void setRealAmount(BigDecimal realAmount) {
		this.realAmount = realAmount;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

}
