package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TbtempbillbatchId generated by hbm2java
 */
public class TbtempbillbatchId implements java.io.Serializable {

	private String batchNo;
	private String batchType;
	private String billNo;

	public TbtempbillbatchId() {
	}

	public TbtempbillbatchId(String batchNo, String batchType, String billNo) {
		this.batchNo = batchNo;
		this.batchType = batchType;
		this.billNo = billNo;
	}

	public String getBatchNo() {
		return this.batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getBatchType() {
		return this.batchType;
	}

	public void setBatchType(String batchType) {
		this.batchType = batchType;
	}

	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbtempbillbatchId))
			return false;
		TbtempbillbatchId castOther = (TbtempbillbatchId) other;

		return ((this.getBatchNo() == castOther.getBatchNo()) || (this
				.getBatchNo() != null && castOther.getBatchNo() != null && this
				.getBatchNo().equals(castOther.getBatchNo())))
				&& ((this.getBatchType() == castOther.getBatchType()) || (this
						.getBatchType() != null
						&& castOther.getBatchType() != null && this
						.getBatchType().equals(castOther.getBatchType())))
				&& ((this.getBillNo() == castOther.getBillNo()) || (this
						.getBillNo() != null && castOther.getBillNo() != null && this
						.getBillNo().equals(castOther.getBillNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBatchNo() == null ? 0 : this.getBatchNo().hashCode());
		result = 37 * result
				+ (getBatchType() == null ? 0 : this.getBatchType().hashCode());
		result = 37 * result
				+ (getBillNo() == null ? 0 : this.getBillNo().hashCode());
		return result;
	}

}
