package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TbtempbalsumId generated by hbm2java
 */
public class TbtempbalsumId implements java.io.Serializable {

	private String businNo;
	private BigDecimal transDate;

	public TbtempbalsumId() {
	}

	public TbtempbalsumId(String businNo, BigDecimal transDate) {
		this.businNo = businNo;
		this.transDate = transDate;
	}

	public String getBusinNo() {
		return this.businNo;
	}

	public void setBusinNo(String businNo) {
		this.businNo = businNo;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbtempbalsumId))
			return false;
		TbtempbalsumId castOther = (TbtempbalsumId) other;

		return ((this.getBusinNo() == castOther.getBusinNo()) || (this
				.getBusinNo() != null && castOther.getBusinNo() != null && this
				.getBusinNo().equals(castOther.getBusinNo())))
				&& ((this.getTransDate() == castOther.getTransDate()) || (this
						.getTransDate() != null
						&& castOther.getTransDate() != null && this
						.getTransDate().equals(castOther.getTransDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBusinNo() == null ? 0 : this.getBusinNo().hashCode());
		result = 37 * result
				+ (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		return result;
	}

}
