package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Tbtempinstruction generated by hbm2java
 */
public class Tbtempinstruction implements java.io.Serializable {

	private TbtempinstructionId id;
	private BigDecimal transDate;
	private String lockFlag;
	private BigDecimal indexLastModify;
	private String flowInstanceId;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String marketNo;
	private String instructionType;
	private BigDecimal beginDate;
	private BigDecimal endDate;
	private BigDecimal beginTime;
	private BigDecimal endTime;
	private BigDecimal directDate;
	private BigDecimal directTime;
	private String directOperator;
	private String summary;
	private BigDecimal modifyDate;
	private BigDecimal modifyTime;
	private String modifyOperator;
	private String modifyReason;
	private BigDecimal checkDate;
	private BigDecimal checkTime;
	private String checkOperator;
	private String checkRefuseReason;
	private BigDecimal cancelDate;
	private BigDecimal cancelTime;
	private String cancelOperator;
	private String cancelReason;
	private BigDecimal cancelCheckDate;
	private BigDecimal cancelCheckTime;
	private String cancelCheckOperator;
	private String cancelCheckRefuseReason;
	private String executeOperator;
	private String instructionStatus;
	private String checkStatus;
	private String approveStatus;
	private String cancelCheckStatus;
	private String entrustExecuteStatus;
	private String dealExecuteStatus;
	private String businClass;
	private BigDecimal transTime;
	private String approveNoStatus;
	private String approveNo;
	private String virtualInstr;
	private String instructionRelatedNo;
	private String branchNo;
	private String strategy;
	private String reserve1;
	private String reserve2;

	public Tbtempinstruction() {
	}

	public Tbtempinstruction(TbtempinstructionId id, BigDecimal transDate,
			String lockFlag, BigDecimal indexLastModify, String flowInstanceId,
			String fundNo, String assetNo, String combiNo, String marketNo,
			String instructionType, BigDecimal beginDate, BigDecimal endDate,
			BigDecimal beginTime, BigDecimal endTime, BigDecimal directDate,
			BigDecimal directTime, String directOperator, String summary,
			BigDecimal modifyDate, BigDecimal modifyTime,
			String modifyOperator, String modifyReason, BigDecimal checkDate,
			BigDecimal checkTime, String checkOperator,
			String checkRefuseReason, BigDecimal cancelDate,
			BigDecimal cancelTime, String cancelOperator, String cancelReason,
			BigDecimal cancelCheckDate, BigDecimal cancelCheckTime,
			String cancelCheckOperator, String cancelCheckRefuseReason,
			String executeOperator, String instructionStatus,
			String checkStatus, String approveStatus, String cancelCheckStatus,
			String entrustExecuteStatus, String dealExecuteStatus,
			String businClass, BigDecimal transTime, String approveNoStatus,
			String approveNo, String virtualInstr, String instructionRelatedNo,
			String branchNo, String strategy, String reserve1, String reserve2) {
		this.id = id;
		this.transDate = transDate;
		this.lockFlag = lockFlag;
		this.indexLastModify = indexLastModify;
		this.flowInstanceId = flowInstanceId;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.marketNo = marketNo;
		this.instructionType = instructionType;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.directDate = directDate;
		this.directTime = directTime;
		this.directOperator = directOperator;
		this.summary = summary;
		this.modifyDate = modifyDate;
		this.modifyTime = modifyTime;
		this.modifyOperator = modifyOperator;
		this.modifyReason = modifyReason;
		this.checkDate = checkDate;
		this.checkTime = checkTime;
		this.checkOperator = checkOperator;
		this.checkRefuseReason = checkRefuseReason;
		this.cancelDate = cancelDate;
		this.cancelTime = cancelTime;
		this.cancelOperator = cancelOperator;
		this.cancelReason = cancelReason;
		this.cancelCheckDate = cancelCheckDate;
		this.cancelCheckTime = cancelCheckTime;
		this.cancelCheckOperator = cancelCheckOperator;
		this.cancelCheckRefuseReason = cancelCheckRefuseReason;
		this.executeOperator = executeOperator;
		this.instructionStatus = instructionStatus;
		this.checkStatus = checkStatus;
		this.approveStatus = approveStatus;
		this.cancelCheckStatus = cancelCheckStatus;
		this.entrustExecuteStatus = entrustExecuteStatus;
		this.dealExecuteStatus = dealExecuteStatus;
		this.businClass = businClass;
		this.transTime = transTime;
		this.approveNoStatus = approveNoStatus;
		this.approveNo = approveNo;
		this.virtualInstr = virtualInstr;
		this.instructionRelatedNo = instructionRelatedNo;
		this.branchNo = branchNo;
		this.strategy = strategy;
		this.reserve1 = reserve1;
		this.reserve2 = reserve2;
	}

	public TbtempinstructionId getId() {
		return this.id;
	}

	public void setId(TbtempinstructionId id) {
		this.id = id;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getLockFlag() {
		return this.lockFlag;
	}

	public void setLockFlag(String lockFlag) {
		this.lockFlag = lockFlag;
	}

	public BigDecimal getIndexLastModify() {
		return this.indexLastModify;
	}

	public void setIndexLastModify(BigDecimal indexLastModify) {
		this.indexLastModify = indexLastModify;
	}

	public String getFlowInstanceId() {
		return this.flowInstanceId;
	}

	public void setFlowInstanceId(String flowInstanceId) {
		this.flowInstanceId = flowInstanceId;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getMarketNo() {
		return this.marketNo;
	}

	public void setMarketNo(String marketNo) {
		this.marketNo = marketNo;
	}

	public String getInstructionType() {
		return this.instructionType;
	}

	public void setInstructionType(String instructionType) {
		this.instructionType = instructionType;
	}

	public BigDecimal getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(BigDecimal beginDate) {
		this.beginDate = beginDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(BigDecimal beginTime) {
		this.beginTime = beginTime;
	}

	public BigDecimal getEndTime() {
		return this.endTime;
	}

	public void setEndTime(BigDecimal endTime) {
		this.endTime = endTime;
	}

	public BigDecimal getDirectDate() {
		return this.directDate;
	}

	public void setDirectDate(BigDecimal directDate) {
		this.directDate = directDate;
	}

	public BigDecimal getDirectTime() {
		return this.directTime;
	}

	public void setDirectTime(BigDecimal directTime) {
		this.directTime = directTime;
	}

	public String getDirectOperator() {
		return this.directOperator;
	}

	public void setDirectOperator(String directOperator) {
		this.directOperator = directOperator;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public BigDecimal getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(BigDecimal modifyDate) {
		this.modifyDate = modifyDate;
	}

	public BigDecimal getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(BigDecimal modifyTime) {
		this.modifyTime = modifyTime;
	}

	public String getModifyOperator() {
		return this.modifyOperator;
	}

	public void setModifyOperator(String modifyOperator) {
		this.modifyOperator = modifyOperator;
	}

	public String getModifyReason() {
		return this.modifyReason;
	}

	public void setModifyReason(String modifyReason) {
		this.modifyReason = modifyReason;
	}

	public BigDecimal getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(BigDecimal checkDate) {
		this.checkDate = checkDate;
	}

	public BigDecimal getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(BigDecimal checkTime) {
		this.checkTime = checkTime;
	}

	public String getCheckOperator() {
		return this.checkOperator;
	}

	public void setCheckOperator(String checkOperator) {
		this.checkOperator = checkOperator;
	}

	public String getCheckRefuseReason() {
		return this.checkRefuseReason;
	}

	public void setCheckRefuseReason(String checkRefuseReason) {
		this.checkRefuseReason = checkRefuseReason;
	}

	public BigDecimal getCancelDate() {
		return this.cancelDate;
	}

	public void setCancelDate(BigDecimal cancelDate) {
		this.cancelDate = cancelDate;
	}

	public BigDecimal getCancelTime() {
		return this.cancelTime;
	}

	public void setCancelTime(BigDecimal cancelTime) {
		this.cancelTime = cancelTime;
	}

	public String getCancelOperator() {
		return this.cancelOperator;
	}

	public void setCancelOperator(String cancelOperator) {
		this.cancelOperator = cancelOperator;
	}

	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	public BigDecimal getCancelCheckDate() {
		return this.cancelCheckDate;
	}

	public void setCancelCheckDate(BigDecimal cancelCheckDate) {
		this.cancelCheckDate = cancelCheckDate;
	}

	public BigDecimal getCancelCheckTime() {
		return this.cancelCheckTime;
	}

	public void setCancelCheckTime(BigDecimal cancelCheckTime) {
		this.cancelCheckTime = cancelCheckTime;
	}

	public String getCancelCheckOperator() {
		return this.cancelCheckOperator;
	}

	public void setCancelCheckOperator(String cancelCheckOperator) {
		this.cancelCheckOperator = cancelCheckOperator;
	}

	public String getCancelCheckRefuseReason() {
		return this.cancelCheckRefuseReason;
	}

	public void setCancelCheckRefuseReason(String cancelCheckRefuseReason) {
		this.cancelCheckRefuseReason = cancelCheckRefuseReason;
	}

	public String getExecuteOperator() {
		return this.executeOperator;
	}

	public void setExecuteOperator(String executeOperator) {
		this.executeOperator = executeOperator;
	}

	public String getInstructionStatus() {
		return this.instructionStatus;
	}

	public void setInstructionStatus(String instructionStatus) {
		this.instructionStatus = instructionStatus;
	}

	public String getCheckStatus() {
		return this.checkStatus;
	}

	public void setCheckStatus(String checkStatus) {
		this.checkStatus = checkStatus;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public String getCancelCheckStatus() {
		return this.cancelCheckStatus;
	}

	public void setCancelCheckStatus(String cancelCheckStatus) {
		this.cancelCheckStatus = cancelCheckStatus;
	}

	public String getEntrustExecuteStatus() {
		return this.entrustExecuteStatus;
	}

	public void setEntrustExecuteStatus(String entrustExecuteStatus) {
		this.entrustExecuteStatus = entrustExecuteStatus;
	}

	public String getDealExecuteStatus() {
		return this.dealExecuteStatus;
	}

	public void setDealExecuteStatus(String dealExecuteStatus) {
		this.dealExecuteStatus = dealExecuteStatus;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public BigDecimal getTransTime() {
		return this.transTime;
	}

	public void setTransTime(BigDecimal transTime) {
		this.transTime = transTime;
	}

	public String getApproveNoStatus() {
		return this.approveNoStatus;
	}

	public void setApproveNoStatus(String approveNoStatus) {
		this.approveNoStatus = approveNoStatus;
	}

	public String getApproveNo() {
		return this.approveNo;
	}

	public void setApproveNo(String approveNo) {
		this.approveNo = approveNo;
	}

	public String getVirtualInstr() {
		return this.virtualInstr;
	}

	public void setVirtualInstr(String virtualInstr) {
		this.virtualInstr = virtualInstr;
	}

	public String getInstructionRelatedNo() {
		return this.instructionRelatedNo;
	}

	public void setInstructionRelatedNo(String instructionRelatedNo) {
		this.instructionRelatedNo = instructionRelatedNo;
	}

	public String getBranchNo() {
		return this.branchNo;
	}

	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	public String getStrategy() {
		return this.strategy;
	}

	public void setStrategy(String strategy) {
		this.strategy = strategy;
	}

	public String getReserve1() {
		return this.reserve1;
	}

	public void setReserve1(String reserve1) {
		this.reserve1 = reserve1;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

}
