package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Tbtotalcredit generated by hbm2java
 */
public class Tbtotalcredit implements java.io.Serializable {

	private String totalCreditId;
	private String creditObjectId;
	private String currType;
	private BigDecimal totalCreditBalance;
	private BigDecimal beginDate;
	private BigDecimal endDate;
	private String creditStatus;
	private String returnStatus;
	private String branchNo;
	private String latestMaintainOperator;
	private BigDecimal latestMaintainDate;

	public Tbtotalcredit() {
	}

	public Tbtotalcredit(String totalCreditId, String creditObjectId,
			String currType, BigDecimal totalCreditBalance,
			BigDecimal beginDate, BigDecimal endDate, String creditStatus,
			String returnStatus, String branchNo,
			String latestMaintainOperator, BigDecimal latestMaintainDate) {
		this.totalCreditId = totalCreditId;
		this.creditObjectId = creditObjectId;
		this.currType = currType;
		this.totalCreditBalance = totalCreditBalance;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.creditStatus = creditStatus;
		this.returnStatus = returnStatus;
		this.branchNo = branchNo;
		this.latestMaintainOperator = latestMaintainOperator;
		this.latestMaintainDate = latestMaintainDate;
	}

	public String getTotalCreditId() {
		return this.totalCreditId;
	}

	public void setTotalCreditId(String totalCreditId) {
		this.totalCreditId = totalCreditId;
	}

	public String getCreditObjectId() {
		return this.creditObjectId;
	}

	public void setCreditObjectId(String creditObjectId) {
		this.creditObjectId = creditObjectId;
	}

	public String getCurrType() {
		return this.currType;
	}

	public void setCurrType(String currType) {
		this.currType = currType;
	}

	public BigDecimal getTotalCreditBalance() {
		return this.totalCreditBalance;
	}

	public void setTotalCreditBalance(BigDecimal totalCreditBalance) {
		this.totalCreditBalance = totalCreditBalance;
	}

	public BigDecimal getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(BigDecimal beginDate) {
		this.beginDate = beginDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public String getCreditStatus() {
		return this.creditStatus;
	}

	public void setCreditStatus(String creditStatus) {
		this.creditStatus = creditStatus;
	}

	public String getReturnStatus() {
		return this.returnStatus;
	}

	public void setReturnStatus(String returnStatus) {
		this.returnStatus = returnStatus;
	}

	public String getBranchNo() {
		return this.branchNo;
	}

	public void setBranchNo(String branchNo) {
		this.branchNo = branchNo;
	}

	public String getLatestMaintainOperator() {
		return this.latestMaintainOperator;
	}

	public void setLatestMaintainOperator(String latestMaintainOperator) {
		this.latestMaintainOperator = latestMaintainOperator;
	}

	public BigDecimal getLatestMaintainDate() {
		return this.latestMaintainDate;
	}

	public void setLatestMaintainDate(BigDecimal latestMaintainDate) {
		this.latestMaintainDate = latestMaintainDate;
	}

}
