package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Tbtransflow generated by hbm2java
 */
public class Tbtransflow implements java.io.Serializable {

	private String serialNo;
	private BigDecimal occurDate;
	private String marketNo;
	private String userId;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String costsCenter;
	private String sourceFlag;
	private String businSerial;
	private String oriBusinSerial;
	private String businClass;
	private String subCode;
	private String businFlag;
	private String investType;
	private String stockName;
	private String reportCode;
	private BigDecimal balance;
	private BigDecimal interest;
	private BigDecimal amount;
	private String currType;
	private BigDecimal price;
	private String fundConfirmFlag;
	private BigDecimal fundConfirmDate;
	private BigDecimal settleDate;
	private BigDecimal transDate;
	private BigDecimal endDate;
	private BigDecimal farDate;
	private BigDecimal hgRate;
	private String currContra;
	private BigDecimal amountContra;
	private BigDecimal balanceContra;
	private BigDecimal farPrice;
	private BigDecimal farBalance;
	private BigDecimal farBalanceContra;
	private String principleExchType;
	private String optionUpFlag;
	private BigDecimal fee;
	private String cancelFlag;
	private String summary;
	private String reserve;
	private String toCombiNo;
	private String approveStatus;
	private String rivalNo;
	private String contraBusinSerial;
	private String dealSerialNo;
	private String bookBranch;

	public Tbtransflow() {
	}

	public Tbtransflow(String serialNo, BigDecimal occurDate, String marketNo,
			String userId, String fundNo, String assetNo, String combiNo,
			String costsCenter, String sourceFlag, String businSerial,
			String oriBusinSerial, String businClass, String subCode,
			String businFlag, String investType, String stockName,
			String reportCode, BigDecimal balance, BigDecimal interest,
			BigDecimal amount, String currType, BigDecimal price,
			String fundConfirmFlag, BigDecimal fundConfirmDate,
			BigDecimal settleDate, BigDecimal transDate, BigDecimal endDate,
			BigDecimal farDate, BigDecimal hgRate, String currContra,
			BigDecimal amountContra, BigDecimal balanceContra,
			BigDecimal farPrice, BigDecimal farBalance,
			BigDecimal farBalanceContra, String principleExchType,
			String optionUpFlag, BigDecimal fee, String cancelFlag,
			String summary, String reserve, String toCombiNo,
			String approveStatus, String rivalNo, String contraBusinSerial,
			String dealSerialNo, String bookBranch) {
		this.serialNo = serialNo;
		this.occurDate = occurDate;
		this.marketNo = marketNo;
		this.userId = userId;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.costsCenter = costsCenter;
		this.sourceFlag = sourceFlag;
		this.businSerial = businSerial;
		this.oriBusinSerial = oriBusinSerial;
		this.businClass = businClass;
		this.subCode = subCode;
		this.businFlag = businFlag;
		this.investType = investType;
		this.stockName = stockName;
		this.reportCode = reportCode;
		this.balance = balance;
		this.interest = interest;
		this.amount = amount;
		this.currType = currType;
		this.price = price;
		this.fundConfirmFlag = fundConfirmFlag;
		this.fundConfirmDate = fundConfirmDate;
		this.settleDate = settleDate;
		this.transDate = transDate;
		this.endDate = endDate;
		this.farDate = farDate;
		this.hgRate = hgRate;
		this.currContra = currContra;
		this.amountContra = amountContra;
		this.balanceContra = balanceContra;
		this.farPrice = farPrice;
		this.farBalance = farBalance;
		this.farBalanceContra = farBalanceContra;
		this.principleExchType = principleExchType;
		this.optionUpFlag = optionUpFlag;
		this.fee = fee;
		this.cancelFlag = cancelFlag;
		this.summary = summary;
		this.reserve = reserve;
		this.toCombiNo = toCombiNo;
		this.approveStatus = approveStatus;
		this.rivalNo = rivalNo;
		this.contraBusinSerial = contraBusinSerial;
		this.dealSerialNo = dealSerialNo;
		this.bookBranch = bookBranch;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public BigDecimal getOccurDate() {
		return this.occurDate;
	}

	public void setOccurDate(BigDecimal occurDate) {
		this.occurDate = occurDate;
	}

	public String getMarketNo() {
		return this.marketNo;
	}

	public void setMarketNo(String marketNo) {
		this.marketNo = marketNo;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getCostsCenter() {
		return this.costsCenter;
	}

	public void setCostsCenter(String costsCenter) {
		this.costsCenter = costsCenter;
	}

	public String getSourceFlag() {
		return this.sourceFlag;
	}

	public void setSourceFlag(String sourceFlag) {
		this.sourceFlag = sourceFlag;
	}

	public String getBusinSerial() {
		return this.businSerial;
	}

	public void setBusinSerial(String businSerial) {
		this.businSerial = businSerial;
	}

	public String getOriBusinSerial() {
		return this.oriBusinSerial;
	}

	public void setOriBusinSerial(String oriBusinSerial) {
		this.oriBusinSerial = oriBusinSerial;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public String getBusinFlag() {
		return this.businFlag;
	}

	public void setBusinFlag(String businFlag) {
		this.businFlag = businFlag;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getStockName() {
		return this.stockName;
	}

	public void setStockName(String stockName) {
		this.stockName = stockName;
	}

	public String getReportCode() {
		return this.reportCode;
	}

	public void setReportCode(String reportCode) {
		this.reportCode = reportCode;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getInterest() {
		return this.interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getCurrType() {
		return this.currType;
	}

	public void setCurrType(String currType) {
		this.currType = currType;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getFundConfirmFlag() {
		return this.fundConfirmFlag;
	}

	public void setFundConfirmFlag(String fundConfirmFlag) {
		this.fundConfirmFlag = fundConfirmFlag;
	}

	public BigDecimal getFundConfirmDate() {
		return this.fundConfirmDate;
	}

	public void setFundConfirmDate(BigDecimal fundConfirmDate) {
		this.fundConfirmDate = fundConfirmDate;
	}

	public BigDecimal getSettleDate() {
		return this.settleDate;
	}

	public void setSettleDate(BigDecimal settleDate) {
		this.settleDate = settleDate;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getFarDate() {
		return this.farDate;
	}

	public void setFarDate(BigDecimal farDate) {
		this.farDate = farDate;
	}

	public BigDecimal getHgRate() {
		return this.hgRate;
	}

	public void setHgRate(BigDecimal hgRate) {
		this.hgRate = hgRate;
	}

	public String getCurrContra() {
		return this.currContra;
	}

	public void setCurrContra(String currContra) {
		this.currContra = currContra;
	}

	public BigDecimal getAmountContra() {
		return this.amountContra;
	}

	public void setAmountContra(BigDecimal amountContra) {
		this.amountContra = amountContra;
	}

	public BigDecimal getBalanceContra() {
		return this.balanceContra;
	}

	public void setBalanceContra(BigDecimal balanceContra) {
		this.balanceContra = balanceContra;
	}

	public BigDecimal getFarPrice() {
		return this.farPrice;
	}

	public void setFarPrice(BigDecimal farPrice) {
		this.farPrice = farPrice;
	}

	public BigDecimal getFarBalance() {
		return this.farBalance;
	}

	public void setFarBalance(BigDecimal farBalance) {
		this.farBalance = farBalance;
	}

	public BigDecimal getFarBalanceContra() {
		return this.farBalanceContra;
	}

	public void setFarBalanceContra(BigDecimal farBalanceContra) {
		this.farBalanceContra = farBalanceContra;
	}

	public String getPrincipleExchType() {
		return this.principleExchType;
	}

	public void setPrincipleExchType(String principleExchType) {
		this.principleExchType = principleExchType;
	}

	public String getOptionUpFlag() {
		return this.optionUpFlag;
	}

	public void setOptionUpFlag(String optionUpFlag) {
		this.optionUpFlag = optionUpFlag;
	}

	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	public String getCancelFlag() {
		return this.cancelFlag;
	}

	public void setCancelFlag(String cancelFlag) {
		this.cancelFlag = cancelFlag;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getToCombiNo() {
		return this.toCombiNo;
	}

	public void setToCombiNo(String toCombiNo) {
		this.toCombiNo = toCombiNo;
	}

	public String getApproveStatus() {
		return this.approveStatus;
	}

	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}

	public String getRivalNo() {
		return this.rivalNo;
	}

	public void setRivalNo(String rivalNo) {
		this.rivalNo = rivalNo;
	}

	public String getContraBusinSerial() {
		return this.contraBusinSerial;
	}

	public void setContraBusinSerial(String contraBusinSerial) {
		this.contraBusinSerial = contraBusinSerial;
	}

	public String getDealSerialNo() {
		return this.dealSerialNo;
	}

	public void setDealSerialNo(String dealSerialNo) {
		this.dealSerialNo = dealSerialNo;
	}

	public String getBookBranch() {
		return this.bookBranch;
	}

	public void setBookBranch(String bookBranch) {
		this.bookBranch = bookBranch;
	}

}
