package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Tbunitcfl generated by hbm2java
 */
public class Tbunitcfl implements java.io.Serializable {

	private TbunitcflId id;
	private String fundNo;
	private String assetNo;
	private String sourceFlag;
	private BigDecimal startDate;
	private BigDecimal endDate;
	private String compdMethod;
	private BigDecimal payDate;
	private BigDecimal payAmt;
	private String payCcy;
	private String status;
	private String dealStatus;
	private String cflType;
	private BigDecimal actualAmt;
	private BigDecimal actualDate;
	private String position;
	private BigDecimal nominalAmt;
	private BigDecimal amount;
	private String payBasis;
	private BigDecimal payRate;
	private String accSerialNo;
	private String accSerialNo2;
	private String nettingNo;
	private String remark;
	private BigDecimal ruleNo;
	private String name;
	private String feeType;
	private String selfSerialNo;
	private String rivalSerialNo;
	private String rivalNo;
	private String payMethod;
	private String firstMaturity;
	private String cashSettleStatus;
	private String selfPathType;
	private String rivalPathType;
	private String selfNo;
	private String postscript;
	private String bookBranch;
	private BigDecimal lastDate;
	private BigDecimal lastTime;
	private String businType;
	private String businClass;
	private String subCode;
	private String reserve;
	private String reserve2;
	private String reserve3;

	public Tbunitcfl() {
	}

	public Tbunitcfl(TbunitcflId id, String fundNo, String assetNo,
			String sourceFlag, BigDecimal startDate, BigDecimal endDate,
			String compdMethod, BigDecimal payDate, BigDecimal payAmt,
			String payCcy, String status, String dealStatus, String cflType,
			BigDecimal actualAmt, BigDecimal actualDate, String position,
			BigDecimal nominalAmt, BigDecimal amount, String payBasis,
			BigDecimal payRate, String accSerialNo, String accSerialNo2,
			String nettingNo, String remark, BigDecimal ruleNo, String name,
			String feeType, String selfSerialNo, String rivalSerialNo,
			String rivalNo, String payMethod, String firstMaturity,
			String cashSettleStatus, String selfPathType, String rivalPathType,
			String selfNo, String postscript, String bookBranch,
			BigDecimal lastDate, BigDecimal lastTime, String businType,
			String businClass, String subCode, String reserve, String reserve2,
			String reserve3) {
		this.id = id;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.sourceFlag = sourceFlag;
		this.startDate = startDate;
		this.endDate = endDate;
		this.compdMethod = compdMethod;
		this.payDate = payDate;
		this.payAmt = payAmt;
		this.payCcy = payCcy;
		this.status = status;
		this.dealStatus = dealStatus;
		this.cflType = cflType;
		this.actualAmt = actualAmt;
		this.actualDate = actualDate;
		this.position = position;
		this.nominalAmt = nominalAmt;
		this.amount = amount;
		this.payBasis = payBasis;
		this.payRate = payRate;
		this.accSerialNo = accSerialNo;
		this.accSerialNo2 = accSerialNo2;
		this.nettingNo = nettingNo;
		this.remark = remark;
		this.ruleNo = ruleNo;
		this.name = name;
		this.feeType = feeType;
		this.selfSerialNo = selfSerialNo;
		this.rivalSerialNo = rivalSerialNo;
		this.rivalNo = rivalNo;
		this.payMethod = payMethod;
		this.firstMaturity = firstMaturity;
		this.cashSettleStatus = cashSettleStatus;
		this.selfPathType = selfPathType;
		this.rivalPathType = rivalPathType;
		this.selfNo = selfNo;
		this.postscript = postscript;
		this.bookBranch = bookBranch;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
		this.businType = businType;
		this.businClass = businClass;
		this.subCode = subCode;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
	}

	public TbunitcflId getId() {
		return this.id;
	}

	public void setId(TbunitcflId id) {
		this.id = id;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getSourceFlag() {
		return this.sourceFlag;
	}

	public void setSourceFlag(String sourceFlag) {
		this.sourceFlag = sourceFlag;
	}

	public BigDecimal getStartDate() {
		return this.startDate;
	}

	public void setStartDate(BigDecimal startDate) {
		this.startDate = startDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public String getCompdMethod() {
		return this.compdMethod;
	}

	public void setCompdMethod(String compdMethod) {
		this.compdMethod = compdMethod;
	}

	public BigDecimal getPayDate() {
		return this.payDate;
	}

	public void setPayDate(BigDecimal payDate) {
		this.payDate = payDate;
	}

	public BigDecimal getPayAmt() {
		return this.payAmt;
	}

	public void setPayAmt(BigDecimal payAmt) {
		this.payAmt = payAmt;
	}

	public String getPayCcy() {
		return this.payCcy;
	}

	public void setPayCcy(String payCcy) {
		this.payCcy = payCcy;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDealStatus() {
		return this.dealStatus;
	}

	public void setDealStatus(String dealStatus) {
		this.dealStatus = dealStatus;
	}

	public String getCflType() {
		return this.cflType;
	}

	public void setCflType(String cflType) {
		this.cflType = cflType;
	}

	public BigDecimal getActualAmt() {
		return this.actualAmt;
	}

	public void setActualAmt(BigDecimal actualAmt) {
		this.actualAmt = actualAmt;
	}

	public BigDecimal getActualDate() {
		return this.actualDate;
	}

	public void setActualDate(BigDecimal actualDate) {
		this.actualDate = actualDate;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public BigDecimal getNominalAmt() {
		return this.nominalAmt;
	}

	public void setNominalAmt(BigDecimal nominalAmt) {
		this.nominalAmt = nominalAmt;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getPayBasis() {
		return this.payBasis;
	}

	public void setPayBasis(String payBasis) {
		this.payBasis = payBasis;
	}

	public BigDecimal getPayRate() {
		return this.payRate;
	}

	public void setPayRate(BigDecimal payRate) {
		this.payRate = payRate;
	}

	public String getAccSerialNo() {
		return this.accSerialNo;
	}

	public void setAccSerialNo(String accSerialNo) {
		this.accSerialNo = accSerialNo;
	}

	public String getAccSerialNo2() {
		return this.accSerialNo2;
	}

	public void setAccSerialNo2(String accSerialNo2) {
		this.accSerialNo2 = accSerialNo2;
	}

	public String getNettingNo() {
		return this.nettingNo;
	}

	public void setNettingNo(String nettingNo) {
		this.nettingNo = nettingNo;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getRuleNo() {
		return this.ruleNo;
	}

	public void setRuleNo(BigDecimal ruleNo) {
		this.ruleNo = ruleNo;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFeeType() {
		return this.feeType;
	}

	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	public String getSelfSerialNo() {
		return this.selfSerialNo;
	}

	public void setSelfSerialNo(String selfSerialNo) {
		this.selfSerialNo = selfSerialNo;
	}

	public String getRivalSerialNo() {
		return this.rivalSerialNo;
	}

	public void setRivalSerialNo(String rivalSerialNo) {
		this.rivalSerialNo = rivalSerialNo;
	}

	public String getRivalNo() {
		return this.rivalNo;
	}

	public void setRivalNo(String rivalNo) {
		this.rivalNo = rivalNo;
	}

	public String getPayMethod() {
		return this.payMethod;
	}

	public void setPayMethod(String payMethod) {
		this.payMethod = payMethod;
	}

	public String getFirstMaturity() {
		return this.firstMaturity;
	}

	public void setFirstMaturity(String firstMaturity) {
		this.firstMaturity = firstMaturity;
	}

	public String getCashSettleStatus() {
		return this.cashSettleStatus;
	}

	public void setCashSettleStatus(String cashSettleStatus) {
		this.cashSettleStatus = cashSettleStatus;
	}

	public String getSelfPathType() {
		return this.selfPathType;
	}

	public void setSelfPathType(String selfPathType) {
		this.selfPathType = selfPathType;
	}

	public String getRivalPathType() {
		return this.rivalPathType;
	}

	public void setRivalPathType(String rivalPathType) {
		this.rivalPathType = rivalPathType;
	}

	public String getSelfNo() {
		return this.selfNo;
	}

	public void setSelfNo(String selfNo) {
		this.selfNo = selfNo;
	}

	public String getPostscript() {
		return this.postscript;
	}

	public void setPostscript(String postscript) {
		this.postscript = postscript;
	}

	public String getBookBranch() {
		return this.bookBranch;
	}

	public void setBookBranch(String bookBranch) {
		this.bookBranch = bookBranch;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

	public String getBusinType() {
		return this.businType;
	}

	public void setBusinType(String businType) {
		this.businType = businType;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getSubCode() {
		return this.subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

}
