package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbuserlinkinfo generated by hbm2java
 */
public class Tbuserlinkinfo implements java.io.Serializable {

	private String userId;
	private String phone;
	private String fax;
	private String mobilePhone;
	private String email;
	private String reserve;
	private String trade1;
	private String trade1Default;
	private String trade2;
	private String trade2Default;
	private String trade3;
	private String trade3Default;
	private String trade4;
	private String trade4Default;
	private String trade5;
	private String trade5Default;

	public Tbuserlinkinfo() {
	}

	public Tbuserlinkinfo(String userId, String phone, String fax,
			String mobilePhone, String email, String reserve, String trade1,
			String trade1Default, String trade2, String trade2Default,
			String trade3, String trade3Default, String trade4,
			String trade4Default, String trade5, String trade5Default) {
		this.userId = userId;
		this.phone = phone;
		this.fax = fax;
		this.mobilePhone = mobilePhone;
		this.email = email;
		this.reserve = reserve;
		this.trade1 = trade1;
		this.trade1Default = trade1Default;
		this.trade2 = trade2;
		this.trade2Default = trade2Default;
		this.trade3 = trade3;
		this.trade3Default = trade3Default;
		this.trade4 = trade4;
		this.trade4Default = trade4Default;
		this.trade5 = trade5;
		this.trade5Default = trade5Default;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getTrade1() {
		return this.trade1;
	}

	public void setTrade1(String trade1) {
		this.trade1 = trade1;
	}

	public String getTrade1Default() {
		return this.trade1Default;
	}

	public void setTrade1Default(String trade1Default) {
		this.trade1Default = trade1Default;
	}

	public String getTrade2() {
		return this.trade2;
	}

	public void setTrade2(String trade2) {
		this.trade2 = trade2;
	}

	public String getTrade2Default() {
		return this.trade2Default;
	}

	public void setTrade2Default(String trade2Default) {
		this.trade2Default = trade2Default;
	}

	public String getTrade3() {
		return this.trade3;
	}

	public void setTrade3(String trade3) {
		this.trade3 = trade3;
	}

	public String getTrade3Default() {
		return this.trade3Default;
	}

	public void setTrade3Default(String trade3Default) {
		this.trade3Default = trade3Default;
	}

	public String getTrade4() {
		return this.trade4;
	}

	public void setTrade4(String trade4) {
		this.trade4 = trade4;
	}

	public String getTrade4Default() {
		return this.trade4Default;
	}

	public void setTrade4Default(String trade4Default) {
		this.trade4Default = trade4Default;
	}

	public String getTrade5() {
		return this.trade5;
	}

	public void setTrade5(String trade5) {
		this.trade5 = trade5;
	}

	public String getTrade5Default() {
		return this.trade5Default;
	}

	public void setTrade5Default(String trade5Default) {
		this.trade5Default = trade5Default;
	}

}
