package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbusers generated by hbm2java
 */
public class Tbusers implements java.io.Serializable {

	private String id;
	private String name;
	private String password;

	public Tbusers() {
	}

	public Tbusers(String id) {
		this.id = id;
	}

	public Tbusers(String id, String name, String password) {
		this.id = id;
		this.name = name;
		this.password = password;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
