package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * Tbvirtualcombirelation generated by hbm2java
 */
public class Tbvirtualcombirelation implements java.io.Serializable {

	private TbvirtualcombirelationId id;

	public Tbvirtualcombirelation() {
	}

	public Tbvirtualcombirelation(TbvirtualcombirelationId id) {
		this.id = id;
	}

	public TbvirtualcombirelationId getId() {
		return this.id;
	}

	public void setId(TbvirtualcombirelationId id) {
		this.id = id;
	}

}
