package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * Test11Id generated by hbm2java
 */
public class Test11Id implements java.io.Serializable {

	private String code;
	private BigDecimal dates;

	public Test11Id() {
	}

	public Test11Id(String code, BigDecimal dates) {
		this.code = code;
		this.dates = dates;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public BigDecimal getDates() {
		return this.dates;
	}

	public void setDates(BigDecimal dates) {
		this.dates = dates;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Test11Id))
			return false;
		Test11Id castOther = (Test11Id) other;

		return ((this.getCode() == castOther.getCode()) || (this.getCode() != null
				&& castOther.getCode() != null && this.getCode().equals(
				castOther.getCode())))
				&& ((this.getDates() == castOther.getDates()) || (this
						.getDates() != null && castOther.getDates() != null && this
						.getDates().equals(castOther.getDates())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getDates() == null ? 0 : this.getDates().hashCode());
		return result;
	}

}
