package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtbsellcostId generated by hbm2java
 */
public class TmpAtbsellcostId implements java.io.Serializable {

	private String serialNo;
	private String costNo;
	private String sellDate;
	private BigDecimal sellamt;
	private BigDecimal buyamt;

	public TmpAtbsellcostId() {
	}

	public TmpAtbsellcostId(String serialNo) {
		this.serialNo = serialNo;
	}

	public TmpAtbsellcostId(String serialNo, String costNo, String sellDate,
			BigDecimal sellamt, BigDecimal buyamt) {
		this.serialNo = serialNo;
		this.costNo = costNo;
		this.sellDate = sellDate;
		this.sellamt = sellamt;
		this.buyamt = buyamt;
	}

	public String getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(String serialNo) {
		this.serialNo = serialNo;
	}

	public String getCostNo() {
		return this.costNo;
	}

	public void setCostNo(String costNo) {
		this.costNo = costNo;
	}

	public String getSellDate() {
		return this.sellDate;
	}

	public void setSellDate(String sellDate) {
		this.sellDate = sellDate;
	}

	public BigDecimal getSellamt() {
		return this.sellamt;
	}

	public void setSellamt(BigDecimal sellamt) {
		this.sellamt = sellamt;
	}

	public BigDecimal getBuyamt() {
		return this.buyamt;
	}

	public void setBuyamt(BigDecimal buyamt) {
		this.buyamt = buyamt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtbsellcostId))
			return false;
		TmpAtbsellcostId castOther = (TmpAtbsellcostId) other;

		return ((this.getSerialNo() == castOther.getSerialNo()) || (this
				.getSerialNo() != null && castOther.getSerialNo() != null && this
				.getSerialNo().equals(castOther.getSerialNo())))
				&& ((this.getCostNo() == castOther.getCostNo()) || (this
						.getCostNo() != null && castOther.getCostNo() != null && this
						.getCostNo().equals(castOther.getCostNo())))
				&& ((this.getSellDate() == castOther.getSellDate()) || (this
						.getSellDate() != null
						&& castOther.getSellDate() != null && this
						.getSellDate().equals(castOther.getSellDate())))
				&& ((this.getSellamt() == castOther.getSellamt()) || (this
						.getSellamt() != null && castOther.getSellamt() != null && this
						.getSellamt().equals(castOther.getSellamt())))
				&& ((this.getBuyamt() == castOther.getBuyamt()) || (this
						.getBuyamt() != null && castOther.getBuyamt() != null && this
						.getBuyamt().equals(castOther.getBuyamt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSerialNo() == null ? 0 : this.getSerialNo().hashCode());
		result = 37 * result
				+ (getCostNo() == null ? 0 : this.getCostNo().hashCode());
		result = 37 * result
				+ (getSellDate() == null ? 0 : this.getSellDate().hashCode());
		result = 37 * result
				+ (getSellamt() == null ? 0 : this.getSellamt().hashCode());
		result = 37 * result
				+ (getBuyamt() == null ? 0 : this.getBuyamt().hashCode());
		return result;
	}

}
