package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbhisassetiposition generated by hbm2java
 */
public class TmpAtbhisassetiposition implements java.io.Serializable {

	private TmpAtbhisassetipositionId id;

	public TmpAtbhisassetiposition() {
	}

	public TmpAtbhisassetiposition(TmpAtbhisassetipositionId id) {
		this.id = id;
	}

	public TmpAtbhisassetipositionId getId() {
		return this.id;
	}

	public void setId(TmpAtbhisassetipositionId id) {
		this.id = id;
	}

}
