package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbassetamor generated by hbm2java
 */
public class TmpAtbassetamor implements java.io.Serializable {

	private TmpAtbassetamorId id;

	public TmpAtbassetamor() {
	}

	public TmpAtbassetamor(TmpAtbassetamorId id) {
		this.id = id;
	}

	public TmpAtbassetamorId getId() {
		return this.id;
	}

	public void setId(TmpAtbassetamorId id) {
		this.id = id;
	}

}
