package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbhedgeamort generated by hbm2java
 */
public class TmpAtbhedgeamort implements java.io.Serializable {

	private TmpAtbhedgeamortId id;

	public TmpAtbhedgeamort() {
	}

	public TmpAtbhedgeamort(TmpAtbhedgeamortId id) {
		this.id = id;
	}

	public TmpAtbhedgeamortId getId() {
		return this.id;
	}

	public void setId(TmpAtbhedgeamortId id) {
		this.id = id;
	}

}
