package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtunpostlist generated by hbm2java
 */
public class TmpAtunpostlist implements java.io.Serializable {

	private TmpAtunpostlistId id;

	public TmpAtunpostlist() {
	}

	public TmpAtunpostlist(TmpAtunpostlistId id) {
		this.id = id;
	}

	public TmpAtunpostlistId getId() {
		return this.id;
	}

	public void setId(TmpAtunpostlistId id) {
		this.id = id;
	}

}
