package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtbassetamorId generated by hbm2java
 */
public class TmpAtbassetamorId implements java.io.Serializable {

	private String bookcode;
	private String assetId;
	private char amortizationType;
	private String assetPort;
	private String costsCenter;
	private String assetType;
	private String amorDate;
	private String transId;
	private String bookBranch;
	private String curCode;
	private BigDecimal assetAmor;
	private BigDecimal amorDays;
	private Character incomeStatus;
	private String incomeCert;

	public TmpAtbassetamorId() {
	}

	public TmpAtbassetamorId(String bookcode, String assetId,
			char amortizationType, String assetPort, String costsCenter,
			String assetType, String amorDate, String transId) {
		this.bookcode = bookcode;
		this.assetId = assetId;
		this.amortizationType = amortizationType;
		this.assetPort = assetPort;
		this.costsCenter = costsCenter;
		this.assetType = assetType;
		this.amorDate = amorDate;
		this.transId = transId;
	}

	public TmpAtbassetamorId(String bookcode, String assetId,
			char amortizationType, String assetPort, String costsCenter,
			String assetType, String amorDate, String transId,
			String bookBranch, String curCode, BigDecimal assetAmor,
			BigDecimal amorDays, Character incomeStatus, String incomeCert) {
		this.bookcode = bookcode;
		this.assetId = assetId;
		this.amortizationType = amortizationType;
		this.assetPort = assetPort;
		this.costsCenter = costsCenter;
		this.assetType = assetType;
		this.amorDate = amorDate;
		this.transId = transId;
		this.bookBranch = bookBranch;
		this.curCode = curCode;
		this.assetAmor = assetAmor;
		this.amorDays = amorDays;
		this.incomeStatus = incomeStatus;
		this.incomeCert = incomeCert;
	}

	public String getBookcode() {
		return this.bookcode;
	}

	public void setBookcode(String bookcode) {
		this.bookcode = bookcode;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public char getAmortizationType() {
		return this.amortizationType;
	}

	public void setAmortizationType(char amortizationType) {
		this.amortizationType = amortizationType;
	}

	public String getAssetPort() {
		return this.assetPort;
	}

	public void setAssetPort(String assetPort) {
		this.assetPort = assetPort;
	}

	public String getCostsCenter() {
		return this.costsCenter;
	}

	public void setCostsCenter(String costsCenter) {
		this.costsCenter = costsCenter;
	}

	public String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	public String getAmorDate() {
		return this.amorDate;
	}

	public void setAmorDate(String amorDate) {
		this.amorDate = amorDate;
	}

	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	public String getBookBranch() {
		return this.bookBranch;
	}

	public void setBookBranch(String bookBranch) {
		this.bookBranch = bookBranch;
	}

	public String getCurCode() {
		return this.curCode;
	}

	public void setCurCode(String curCode) {
		this.curCode = curCode;
	}

	public BigDecimal getAssetAmor() {
		return this.assetAmor;
	}

	public void setAssetAmor(BigDecimal assetAmor) {
		this.assetAmor = assetAmor;
	}

	public BigDecimal getAmorDays() {
		return this.amorDays;
	}

	public void setAmorDays(BigDecimal amorDays) {
		this.amorDays = amorDays;
	}

	public Character getIncomeStatus() {
		return this.incomeStatus;
	}

	public void setIncomeStatus(Character incomeStatus) {
		this.incomeStatus = incomeStatus;
	}

	public String getIncomeCert() {
		return this.incomeCert;
	}

	public void setIncomeCert(String incomeCert) {
		this.incomeCert = incomeCert;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtbassetamorId))
			return false;
		TmpAtbassetamorId castOther = (TmpAtbassetamorId) other;

		return ((this.getBookcode() == castOther.getBookcode()) || (this
				.getBookcode() != null && castOther.getBookcode() != null && this
				.getBookcode().equals(castOther.getBookcode())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null && castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& (this.getAmortizationType() == castOther
						.getAmortizationType())
				&& ((this.getAssetPort() == castOther.getAssetPort()) || (this
						.getAssetPort() != null
						&& castOther.getAssetPort() != null && this
						.getAssetPort().equals(castOther.getAssetPort())))
				&& ((this.getCostsCenter() == castOther.getCostsCenter()) || (this
						.getCostsCenter() != null
						&& castOther.getCostsCenter() != null && this
						.getCostsCenter().equals(castOther.getCostsCenter())))
				&& ((this.getAssetType() == castOther.getAssetType()) || (this
						.getAssetType() != null
						&& castOther.getAssetType() != null && this
						.getAssetType().equals(castOther.getAssetType())))
				&& ((this.getAmorDate() == castOther.getAmorDate()) || (this
						.getAmorDate() != null
						&& castOther.getAmorDate() != null && this
						.getAmorDate().equals(castOther.getAmorDate())))
				&& ((this.getTransId() == castOther.getTransId()) || (this
						.getTransId() != null && castOther.getTransId() != null && this
						.getTransId().equals(castOther.getTransId())))
				&& ((this.getBookBranch() == castOther.getBookBranch()) || (this
						.getBookBranch() != null
						&& castOther.getBookBranch() != null && this
						.getBookBranch().equals(castOther.getBookBranch())))
				&& ((this.getCurCode() == castOther.getCurCode()) || (this
						.getCurCode() != null && castOther.getCurCode() != null && this
						.getCurCode().equals(castOther.getCurCode())))
				&& ((this.getAssetAmor() == castOther.getAssetAmor()) || (this
						.getAssetAmor() != null
						&& castOther.getAssetAmor() != null && this
						.getAssetAmor().equals(castOther.getAssetAmor())))
				&& ((this.getAmorDays() == castOther.getAmorDays()) || (this
						.getAmorDays() != null
						&& castOther.getAmorDays() != null && this
						.getAmorDays().equals(castOther.getAmorDays())))
				&& ((this.getIncomeStatus() == castOther.getIncomeStatus()) || (this
						.getIncomeStatus() != null
						&& castOther.getIncomeStatus() != null && this
						.getIncomeStatus().equals(castOther.getIncomeStatus())))
				&& ((this.getIncomeCert() == castOther.getIncomeCert()) || (this
						.getIncomeCert() != null
						&& castOther.getIncomeCert() != null && this
						.getIncomeCert().equals(castOther.getIncomeCert())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBookcode() == null ? 0 : this.getBookcode().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result + this.getAmortizationType();
		result = 37 * result
				+ (getAssetPort() == null ? 0 : this.getAssetPort().hashCode());
		result = 37
				* result
				+ (getCostsCenter() == null ? 0 : this.getCostsCenter()
						.hashCode());
		result = 37 * result
				+ (getAssetType() == null ? 0 : this.getAssetType().hashCode());
		result = 37 * result
				+ (getAmorDate() == null ? 0 : this.getAmorDate().hashCode());
		result = 37 * result
				+ (getTransId() == null ? 0 : this.getTransId().hashCode());
		result = 37
				* result
				+ (getBookBranch() == null ? 0 : this.getBookBranch()
						.hashCode());
		result = 37 * result
				+ (getCurCode() == null ? 0 : this.getCurCode().hashCode());
		result = 37 * result
				+ (getAssetAmor() == null ? 0 : this.getAssetAmor().hashCode());
		result = 37 * result
				+ (getAmorDays() == null ? 0 : this.getAmorDays().hashCode());
		result = 37
				* result
				+ (getIncomeStatus() == null ? 0 : this.getIncomeStatus()
						.hashCode());
		result = 37
				* result
				+ (getIncomeCert() == null ? 0 : this.getIncomeCert()
						.hashCode());
		return result;
	}

}
