package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbfairprice generated by hbm2java
 */
public class TmpAtbfairprice implements java.io.Serializable {

	private TmpAtbfairpriceId id;

	public TmpAtbfairprice() {
	}

	public TmpAtbfairprice(TmpAtbfairpriceId id) {
		this.id = id;
	}

	public TmpAtbfairpriceId getId() {
		return this.id;
	}

	public void setId(TmpAtbfairpriceId id) {
		this.id = id;
	}

}
