package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbhisassetamor generated by hbm2java
 */
public class TmpAtbhisassetamor implements java.io.Serializable {

	private TmpAtbhisassetamorId id;

	public TmpAtbhisassetamor() {
	}

	public TmpAtbhisassetamor(TmpAtbhisassetamorId id) {
		this.id = id;
	}

	public TmpAtbhisassetamorId getId() {
		return this.id;
	}

	public void setId(TmpAtbhisassetamorId id) {
		this.id = id;
	}

}
