package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtunpostentryId generated by hbm2java
 */
public class TmpAtunpostentryId implements java.io.Serializable {

	private BigDecimal serialno;
	private String bookcode;
	private BigDecimal registerdate;
	private BigDecimal entrydate;
	private String entrycatalog;
	private BigDecimal entryno;
	private String voucher;
	private BigDecimal enclosure;
	private String operator;
	private String checkout;
	private String postor;
	private Character checkflag;
	private Character genflag;
	private Character genhostflag;
	private Character delFlag;
	private String srcId;

	public TmpAtunpostentryId() {
	}

	public TmpAtunpostentryId(String bookcode, String entrycatalog,
			BigDecimal entryno, String operator, String checkout, String postor) {
		this.bookcode = bookcode;
		this.entrycatalog = entrycatalog;
		this.entryno = entryno;
		this.operator = operator;
		this.checkout = checkout;
		this.postor = postor;
	}

	public TmpAtunpostentryId(BigDecimal serialno, String bookcode,
			BigDecimal registerdate, BigDecimal entrydate, String entrycatalog,
			BigDecimal entryno, String voucher, BigDecimal enclosure,
			String operator, String checkout, String postor,
			Character checkflag, Character genflag, Character genhostflag,
			Character delFlag, String srcId) {
		this.serialno = serialno;
		this.bookcode = bookcode;
		this.registerdate = registerdate;
		this.entrydate = entrydate;
		this.entrycatalog = entrycatalog;
		this.entryno = entryno;
		this.voucher = voucher;
		this.enclosure = enclosure;
		this.operator = operator;
		this.checkout = checkout;
		this.postor = postor;
		this.checkflag = checkflag;
		this.genflag = genflag;
		this.genhostflag = genhostflag;
		this.delFlag = delFlag;
		this.srcId = srcId;
	}

	public BigDecimal getSerialno() {
		return this.serialno;
	}

	public void setSerialno(BigDecimal serialno) {
		this.serialno = serialno;
	}

	public String getBookcode() {
		return this.bookcode;
	}

	public void setBookcode(String bookcode) {
		this.bookcode = bookcode;
	}

	public BigDecimal getRegisterdate() {
		return this.registerdate;
	}

	public void setRegisterdate(BigDecimal registerdate) {
		this.registerdate = registerdate;
	}

	public BigDecimal getEntrydate() {
		return this.entrydate;
	}

	public void setEntrydate(BigDecimal entrydate) {
		this.entrydate = entrydate;
	}

	public String getEntrycatalog() {
		return this.entrycatalog;
	}

	public void setEntrycatalog(String entrycatalog) {
		this.entrycatalog = entrycatalog;
	}

	public BigDecimal getEntryno() {
		return this.entryno;
	}

	public void setEntryno(BigDecimal entryno) {
		this.entryno = entryno;
	}

	public String getVoucher() {
		return this.voucher;
	}

	public void setVoucher(String voucher) {
		this.voucher = voucher;
	}

	public BigDecimal getEnclosure() {
		return this.enclosure;
	}

	public void setEnclosure(BigDecimal enclosure) {
		this.enclosure = enclosure;
	}

	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getCheckout() {
		return this.checkout;
	}

	public void setCheckout(String checkout) {
		this.checkout = checkout;
	}

	public String getPostor() {
		return this.postor;
	}

	public void setPostor(String postor) {
		this.postor = postor;
	}

	public Character getCheckflag() {
		return this.checkflag;
	}

	public void setCheckflag(Character checkflag) {
		this.checkflag = checkflag;
	}

	public Character getGenflag() {
		return this.genflag;
	}

	public void setGenflag(Character genflag) {
		this.genflag = genflag;
	}

	public Character getGenhostflag() {
		return this.genhostflag;
	}

	public void setGenhostflag(Character genhostflag) {
		this.genhostflag = genhostflag;
	}

	public Character getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(Character delFlag) {
		this.delFlag = delFlag;
	}

	public String getSrcId() {
		return this.srcId;
	}

	public void setSrcId(String srcId) {
		this.srcId = srcId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtunpostentryId))
			return false;
		TmpAtunpostentryId castOther = (TmpAtunpostentryId) other;

		return ((this.getSerialno() == castOther.getSerialno()) || (this
				.getSerialno() != null && castOther.getSerialno() != null && this
				.getSerialno().equals(castOther.getSerialno())))
				&& ((this.getBookcode() == castOther.getBookcode()) || (this
						.getBookcode() != null
						&& castOther.getBookcode() != null && this
						.getBookcode().equals(castOther.getBookcode())))
				&& ((this.getRegisterdate() == castOther.getRegisterdate()) || (this
						.getRegisterdate() != null
						&& castOther.getRegisterdate() != null && this
						.getRegisterdate().equals(castOther.getRegisterdate())))
				&& ((this.getEntrydate() == castOther.getEntrydate()) || (this
						.getEntrydate() != null
						&& castOther.getEntrydate() != null && this
						.getEntrydate().equals(castOther.getEntrydate())))
				&& ((this.getEntrycatalog() == castOther.getEntrycatalog()) || (this
						.getEntrycatalog() != null
						&& castOther.getEntrycatalog() != null && this
						.getEntrycatalog().equals(castOther.getEntrycatalog())))
				&& ((this.getEntryno() == castOther.getEntryno()) || (this
						.getEntryno() != null && castOther.getEntryno() != null && this
						.getEntryno().equals(castOther.getEntryno())))
				&& ((this.getVoucher() == castOther.getVoucher()) || (this
						.getVoucher() != null && castOther.getVoucher() != null && this
						.getVoucher().equals(castOther.getVoucher())))
				&& ((this.getEnclosure() == castOther.getEnclosure()) || (this
						.getEnclosure() != null
						&& castOther.getEnclosure() != null && this
						.getEnclosure().equals(castOther.getEnclosure())))
				&& ((this.getOperator() == castOther.getOperator()) || (this
						.getOperator() != null
						&& castOther.getOperator() != null && this
						.getOperator().equals(castOther.getOperator())))
				&& ((this.getCheckout() == castOther.getCheckout()) || (this
						.getCheckout() != null
						&& castOther.getCheckout() != null && this
						.getCheckout().equals(castOther.getCheckout())))
				&& ((this.getPostor() == castOther.getPostor()) || (this
						.getPostor() != null && castOther.getPostor() != null && this
						.getPostor().equals(castOther.getPostor())))
				&& ((this.getCheckflag() == castOther.getCheckflag()) || (this
						.getCheckflag() != null
						&& castOther.getCheckflag() != null && this
						.getCheckflag().equals(castOther.getCheckflag())))
				&& ((this.getGenflag() == castOther.getGenflag()) || (this
						.getGenflag() != null && castOther.getGenflag() != null && this
						.getGenflag().equals(castOther.getGenflag())))
				&& ((this.getGenhostflag() == castOther.getGenhostflag()) || (this
						.getGenhostflag() != null
						&& castOther.getGenhostflag() != null && this
						.getGenhostflag().equals(castOther.getGenhostflag())))
				&& ((this.getDelFlag() == castOther.getDelFlag()) || (this
						.getDelFlag() != null && castOther.getDelFlag() != null && this
						.getDelFlag().equals(castOther.getDelFlag())))
				&& ((this.getSrcId() == castOther.getSrcId()) || (this
						.getSrcId() != null && castOther.getSrcId() != null && this
						.getSrcId().equals(castOther.getSrcId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSerialno() == null ? 0 : this.getSerialno().hashCode());
		result = 37 * result
				+ (getBookcode() == null ? 0 : this.getBookcode().hashCode());
		result = 37
				* result
				+ (getRegisterdate() == null ? 0 : this.getRegisterdate()
						.hashCode());
		result = 37 * result
				+ (getEntrydate() == null ? 0 : this.getEntrydate().hashCode());
		result = 37
				* result
				+ (getEntrycatalog() == null ? 0 : this.getEntrycatalog()
						.hashCode());
		result = 37 * result
				+ (getEntryno() == null ? 0 : this.getEntryno().hashCode());
		result = 37 * result
				+ (getVoucher() == null ? 0 : this.getVoucher().hashCode());
		result = 37 * result
				+ (getEnclosure() == null ? 0 : this.getEnclosure().hashCode());
		result = 37 * result
				+ (getOperator() == null ? 0 : this.getOperator().hashCode());
		result = 37 * result
				+ (getCheckout() == null ? 0 : this.getCheckout().hashCode());
		result = 37 * result
				+ (getPostor() == null ? 0 : this.getPostor().hashCode());
		result = 37 * result
				+ (getCheckflag() == null ? 0 : this.getCheckflag().hashCode());
		result = 37 * result
				+ (getGenflag() == null ? 0 : this.getGenflag().hashCode());
		result = 37
				* result
				+ (getGenhostflag() == null ? 0 : this.getGenhostflag()
						.hashCode());
		result = 37 * result
				+ (getDelFlag() == null ? 0 : this.getDelFlag().hashCode());
		result = 37 * result
				+ (getSrcId() == null ? 0 : this.getSrcId().hashCode());
		return result;
	}

}
