package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtbassetinfoId generated by hbm2java
 */
public class TmpAtbassetinfoId implements java.io.Serializable {

	private String assetId;
	private String assetCode;
	private String assetName;
	private String assetPublish;
	private BigDecimal faceValue;
	private BigDecimal price;
	private String assetType;
	private String assetSubType1;
	private String assetSubType2;
	private String assetSubType3;
	private String acctType;
	private String interestBase;
	private String interestFrequency;
	private String curCode;
	private String valueDate;
	private String endDate;
	private String transPlaces;
	private Character interestType;
	private String xdividendXdivrule;
	private String xdividendXdivbdrule;
	private String daysruleSettleRule;
	private String daysruleSettleBdrule;
	private BigDecimal daysruleSettleDays;
	private BigDecimal daysruleValueDays;
	private String daysruleValueRule;
	private String daysruleValueBdrule;
	private BigDecimal lformatPriceformCentunits;
	private BigDecimal lformatPriceformRound;
	private String collateral;
	private String country;
	private BigDecimal sizeissue;
	private String payingagent;
	private String srtylevel;
	private BigDecimal ratio;
	private String quote;
	private String yieldformula;
	private String priceformula;
	private BigDecimal ypspread;
	private BigDecimal yield;
	private String riskindex;
	private String fundindex;
	private BigDecimal fundspread;
	private BigDecimal repospread;
	private String callable;
	private String puttable;
	private BigDecimal issueprice;
	private BigDecimal redemptionprice;
	private String pors;
	private String assetccy;
	private BigDecimal interestNrate;
	private String interestDmindex;
	private String interestCcy;
	private String intRefSource;
	private BigDecimal interestSpread;
	private String interestTerm;
	private String intAccAcccalc;
	private String intAccBasis;
	private String interestFwddecomp;
	private String schedPayFreq;
	private BigDecimal schedPayAnnday;
	private String schedPayRule;
	private String schedPayIntrule;
	private String schedPayTime;
	private String schedPayCal;
	private String schedResetFreq;
	private BigDecimal schedResetAnnday;
	private String schedResetRule;
	private String schedResetIntrule;
	private String schedResetTime;
	private String schedResetCal;
	private String custom;
	private BigDecimal crossCcyForexrate;
	private String nextfixing;
	private String intResRefixmode;
	private BigDecimal amortSchedAnnday;
	private String intResFxGap;
	private String schedPayGap;
	private String schedResetGap;
	private String intResPaymentreset;
	private String busmatdate;
	private BigDecimal interestFundsprd;
	private String intResNtlGap;
	private String interestIntratetype;
	private String prmdiscountindex;
	private String qmethodindex;
	private String qmethodccy;
	private String payproccparty;
	private String fullypositionable;
	private String autopricing;
	private String deliverable;
	private String netcouponflows;
	private String ceccy;
	private String guarantor;
	private String custid;
	private String datesMonthEnd;
	private String compdMethod;
	private String principalamortFlag;
	private String principalamortType;
	private String principalamortValue;
	private String principalamortFreq;
	private String principalamort1stDate;
	private String principalamortLastDate;
	private char status;
	private String couponFstDate;
	private String couponLastDate;

	public TmpAtbassetinfoId() {
	}

	public TmpAtbassetinfoId(String assetId, char status) {
		this.assetId = assetId;
		this.status = status;
	}

	public TmpAtbassetinfoId(String assetId, String assetCode,
			String assetName, String assetPublish, BigDecimal faceValue,
			BigDecimal price, String assetType, String assetSubType1,
			String assetSubType2, String assetSubType3, String acctType,
			String interestBase, String interestFrequency, String curCode,
			String valueDate, String endDate, String transPlaces,
			Character interestType, String xdividendXdivrule,
			String xdividendXdivbdrule, String daysruleSettleRule,
			String daysruleSettleBdrule, BigDecimal daysruleSettleDays,
			BigDecimal daysruleValueDays, String daysruleValueRule,
			String daysruleValueBdrule, BigDecimal lformatPriceformCentunits,
			BigDecimal lformatPriceformRound, String collateral,
			String country, BigDecimal sizeissue, String payingagent,
			String srtylevel, BigDecimal ratio, String quote,
			String yieldformula, String priceformula, BigDecimal ypspread,
			BigDecimal yield, String riskindex, String fundindex,
			BigDecimal fundspread, BigDecimal repospread, String callable,
			String puttable, BigDecimal issueprice, BigDecimal redemptionprice,
			String pors, String assetccy, BigDecimal interestNrate,
			String interestDmindex, String interestCcy, String intRefSource,
			BigDecimal interestSpread, String interestTerm,
			String intAccAcccalc, String intAccBasis, String interestFwddecomp,
			String schedPayFreq, BigDecimal schedPayAnnday,
			String schedPayRule, String schedPayIntrule, String schedPayTime,
			String schedPayCal, String schedResetFreq,
			BigDecimal schedResetAnnday, String schedResetRule,
			String schedResetIntrule, String schedResetTime,
			String schedResetCal, String custom, BigDecimal crossCcyForexrate,
			String nextfixing, String intResRefixmode,
			BigDecimal amortSchedAnnday, String intResFxGap,
			String schedPayGap, String schedResetGap,
			String intResPaymentreset, String busmatdate,
			BigDecimal interestFundsprd, String intResNtlGap,
			String interestIntratetype, String prmdiscountindex,
			String qmethodindex, String qmethodccy, String payproccparty,
			String fullypositionable, String autopricing, String deliverable,
			String netcouponflows, String ceccy, String guarantor,
			String custid, String datesMonthEnd, String compdMethod,
			String principalamortFlag, String principalamortType,
			String principalamortValue, String principalamortFreq,
			String principalamort1stDate, String principalamortLastDate,
			char status, String couponFstDate, String couponLastDate) {
		this.assetId = assetId;
		this.assetCode = assetCode;
		this.assetName = assetName;
		this.assetPublish = assetPublish;
		this.faceValue = faceValue;
		this.price = price;
		this.assetType = assetType;
		this.assetSubType1 = assetSubType1;
		this.assetSubType2 = assetSubType2;
		this.assetSubType3 = assetSubType3;
		this.acctType = acctType;
		this.interestBase = interestBase;
		this.interestFrequency = interestFrequency;
		this.curCode = curCode;
		this.valueDate = valueDate;
		this.endDate = endDate;
		this.transPlaces = transPlaces;
		this.interestType = interestType;
		this.xdividendXdivrule = xdividendXdivrule;
		this.xdividendXdivbdrule = xdividendXdivbdrule;
		this.daysruleSettleRule = daysruleSettleRule;
		this.daysruleSettleBdrule = daysruleSettleBdrule;
		this.daysruleSettleDays = daysruleSettleDays;
		this.daysruleValueDays = daysruleValueDays;
		this.daysruleValueRule = daysruleValueRule;
		this.daysruleValueBdrule = daysruleValueBdrule;
		this.lformatPriceformCentunits = lformatPriceformCentunits;
		this.lformatPriceformRound = lformatPriceformRound;
		this.collateral = collateral;
		this.country = country;
		this.sizeissue = sizeissue;
		this.payingagent = payingagent;
		this.srtylevel = srtylevel;
		this.ratio = ratio;
		this.quote = quote;
		this.yieldformula = yieldformula;
		this.priceformula = priceformula;
		this.ypspread = ypspread;
		this.yield = yield;
		this.riskindex = riskindex;
		this.fundindex = fundindex;
		this.fundspread = fundspread;
		this.repospread = repospread;
		this.callable = callable;
		this.puttable = puttable;
		this.issueprice = issueprice;
		this.redemptionprice = redemptionprice;
		this.pors = pors;
		this.assetccy = assetccy;
		this.interestNrate = interestNrate;
		this.interestDmindex = interestDmindex;
		this.interestCcy = interestCcy;
		this.intRefSource = intRefSource;
		this.interestSpread = interestSpread;
		this.interestTerm = interestTerm;
		this.intAccAcccalc = intAccAcccalc;
		this.intAccBasis = intAccBasis;
		this.interestFwddecomp = interestFwddecomp;
		this.schedPayFreq = schedPayFreq;
		this.schedPayAnnday = schedPayAnnday;
		this.schedPayRule = schedPayRule;
		this.schedPayIntrule = schedPayIntrule;
		this.schedPayTime = schedPayTime;
		this.schedPayCal = schedPayCal;
		this.schedResetFreq = schedResetFreq;
		this.schedResetAnnday = schedResetAnnday;
		this.schedResetRule = schedResetRule;
		this.schedResetIntrule = schedResetIntrule;
		this.schedResetTime = schedResetTime;
		this.schedResetCal = schedResetCal;
		this.custom = custom;
		this.crossCcyForexrate = crossCcyForexrate;
		this.nextfixing = nextfixing;
		this.intResRefixmode = intResRefixmode;
		this.amortSchedAnnday = amortSchedAnnday;
		this.intResFxGap = intResFxGap;
		this.schedPayGap = schedPayGap;
		this.schedResetGap = schedResetGap;
		this.intResPaymentreset = intResPaymentreset;
		this.busmatdate = busmatdate;
		this.interestFundsprd = interestFundsprd;
		this.intResNtlGap = intResNtlGap;
		this.interestIntratetype = interestIntratetype;
		this.prmdiscountindex = prmdiscountindex;
		this.qmethodindex = qmethodindex;
		this.qmethodccy = qmethodccy;
		this.payproccparty = payproccparty;
		this.fullypositionable = fullypositionable;
		this.autopricing = autopricing;
		this.deliverable = deliverable;
		this.netcouponflows = netcouponflows;
		this.ceccy = ceccy;
		this.guarantor = guarantor;
		this.custid = custid;
		this.datesMonthEnd = datesMonthEnd;
		this.compdMethod = compdMethod;
		this.principalamortFlag = principalamortFlag;
		this.principalamortType = principalamortType;
		this.principalamortValue = principalamortValue;
		this.principalamortFreq = principalamortFreq;
		this.principalamort1stDate = principalamort1stDate;
		this.principalamortLastDate = principalamortLastDate;
		this.status = status;
		this.couponFstDate = couponFstDate;
		this.couponLastDate = couponLastDate;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getAssetCode() {
		return this.assetCode;
	}

	public void setAssetCode(String assetCode) {
		this.assetCode = assetCode;
	}

	public String getAssetName() {
		return this.assetName;
	}

	public void setAssetName(String assetName) {
		this.assetName = assetName;
	}

	public String getAssetPublish() {
		return this.assetPublish;
	}

	public void setAssetPublish(String assetPublish) {
		this.assetPublish = assetPublish;
	}

	public BigDecimal getFaceValue() {
		return this.faceValue;
	}

	public void setFaceValue(BigDecimal faceValue) {
		this.faceValue = faceValue;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	public String getAssetSubType1() {
		return this.assetSubType1;
	}

	public void setAssetSubType1(String assetSubType1) {
		this.assetSubType1 = assetSubType1;
	}

	public String getAssetSubType2() {
		return this.assetSubType2;
	}

	public void setAssetSubType2(String assetSubType2) {
		this.assetSubType2 = assetSubType2;
	}

	public String getAssetSubType3() {
		return this.assetSubType3;
	}

	public void setAssetSubType3(String assetSubType3) {
		this.assetSubType3 = assetSubType3;
	}

	public String getAcctType() {
		return this.acctType;
	}

	public void setAcctType(String acctType) {
		this.acctType = acctType;
	}

	public String getInterestBase() {
		return this.interestBase;
	}

	public void setInterestBase(String interestBase) {
		this.interestBase = interestBase;
	}

	public String getInterestFrequency() {
		return this.interestFrequency;
	}

	public void setInterestFrequency(String interestFrequency) {
		this.interestFrequency = interestFrequency;
	}

	public String getCurCode() {
		return this.curCode;
	}

	public void setCurCode(String curCode) {
		this.curCode = curCode;
	}

	public String getValueDate() {
		return this.valueDate;
	}

	public void setValueDate(String valueDate) {
		this.valueDate = valueDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getTransPlaces() {
		return this.transPlaces;
	}

	public void setTransPlaces(String transPlaces) {
		this.transPlaces = transPlaces;
	}

	public Character getInterestType() {
		return this.interestType;
	}

	public void setInterestType(Character interestType) {
		this.interestType = interestType;
	}

	public String getXdividendXdivrule() {
		return this.xdividendXdivrule;
	}

	public void setXdividendXdivrule(String xdividendXdivrule) {
		this.xdividendXdivrule = xdividendXdivrule;
	}

	public String getXdividendXdivbdrule() {
		return this.xdividendXdivbdrule;
	}

	public void setXdividendXdivbdrule(String xdividendXdivbdrule) {
		this.xdividendXdivbdrule = xdividendXdivbdrule;
	}

	public String getDaysruleSettleRule() {
		return this.daysruleSettleRule;
	}

	public void setDaysruleSettleRule(String daysruleSettleRule) {
		this.daysruleSettleRule = daysruleSettleRule;
	}

	public String getDaysruleSettleBdrule() {
		return this.daysruleSettleBdrule;
	}

	public void setDaysruleSettleBdrule(String daysruleSettleBdrule) {
		this.daysruleSettleBdrule = daysruleSettleBdrule;
	}

	public BigDecimal getDaysruleSettleDays() {
		return this.daysruleSettleDays;
	}

	public void setDaysruleSettleDays(BigDecimal daysruleSettleDays) {
		this.daysruleSettleDays = daysruleSettleDays;
	}

	public BigDecimal getDaysruleValueDays() {
		return this.daysruleValueDays;
	}

	public void setDaysruleValueDays(BigDecimal daysruleValueDays) {
		this.daysruleValueDays = daysruleValueDays;
	}

	public String getDaysruleValueRule() {
		return this.daysruleValueRule;
	}

	public void setDaysruleValueRule(String daysruleValueRule) {
		this.daysruleValueRule = daysruleValueRule;
	}

	public String getDaysruleValueBdrule() {
		return this.daysruleValueBdrule;
	}

	public void setDaysruleValueBdrule(String daysruleValueBdrule) {
		this.daysruleValueBdrule = daysruleValueBdrule;
	}

	public BigDecimal getLformatPriceformCentunits() {
		return this.lformatPriceformCentunits;
	}

	public void setLformatPriceformCentunits(
			BigDecimal lformatPriceformCentunits) {
		this.lformatPriceformCentunits = lformatPriceformCentunits;
	}

	public BigDecimal getLformatPriceformRound() {
		return this.lformatPriceformRound;
	}

	public void setLformatPriceformRound(BigDecimal lformatPriceformRound) {
		this.lformatPriceformRound = lformatPriceformRound;
	}

	public String getCollateral() {
		return this.collateral;
	}

	public void setCollateral(String collateral) {
		this.collateral = collateral;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public BigDecimal getSizeissue() {
		return this.sizeissue;
	}

	public void setSizeissue(BigDecimal sizeissue) {
		this.sizeissue = sizeissue;
	}

	public String getPayingagent() {
		return this.payingagent;
	}

	public void setPayingagent(String payingagent) {
		this.payingagent = payingagent;
	}

	public String getSrtylevel() {
		return this.srtylevel;
	}

	public void setSrtylevel(String srtylevel) {
		this.srtylevel = srtylevel;
	}

	public BigDecimal getRatio() {
		return this.ratio;
	}

	public void setRatio(BigDecimal ratio) {
		this.ratio = ratio;
	}

	public String getQuote() {
		return this.quote;
	}

	public void setQuote(String quote) {
		this.quote = quote;
	}

	public String getYieldformula() {
		return this.yieldformula;
	}

	public void setYieldformula(String yieldformula) {
		this.yieldformula = yieldformula;
	}

	public String getPriceformula() {
		return this.priceformula;
	}

	public void setPriceformula(String priceformula) {
		this.priceformula = priceformula;
	}

	public BigDecimal getYpspread() {
		return this.ypspread;
	}

	public void setYpspread(BigDecimal ypspread) {
		this.ypspread = ypspread;
	}

	public BigDecimal getYield() {
		return this.yield;
	}

	public void setYield(BigDecimal yield) {
		this.yield = yield;
	}

	public String getRiskindex() {
		return this.riskindex;
	}

	public void setRiskindex(String riskindex) {
		this.riskindex = riskindex;
	}

	public String getFundindex() {
		return this.fundindex;
	}

	public void setFundindex(String fundindex) {
		this.fundindex = fundindex;
	}

	public BigDecimal getFundspread() {
		return this.fundspread;
	}

	public void setFundspread(BigDecimal fundspread) {
		this.fundspread = fundspread;
	}

	public BigDecimal getRepospread() {
		return this.repospread;
	}

	public void setRepospread(BigDecimal repospread) {
		this.repospread = repospread;
	}

	public String getCallable() {
		return this.callable;
	}

	public void setCallable(String callable) {
		this.callable = callable;
	}

	public String getPuttable() {
		return this.puttable;
	}

	public void setPuttable(String puttable) {
		this.puttable = puttable;
	}

	public BigDecimal getIssueprice() {
		return this.issueprice;
	}

	public void setIssueprice(BigDecimal issueprice) {
		this.issueprice = issueprice;
	}

	public BigDecimal getRedemptionprice() {
		return this.redemptionprice;
	}

	public void setRedemptionprice(BigDecimal redemptionprice) {
		this.redemptionprice = redemptionprice;
	}

	public String getPors() {
		return this.pors;
	}

	public void setPors(String pors) {
		this.pors = pors;
	}

	public String getAssetccy() {
		return this.assetccy;
	}

	public void setAssetccy(String assetccy) {
		this.assetccy = assetccy;
	}

	public BigDecimal getInterestNrate() {
		return this.interestNrate;
	}

	public void setInterestNrate(BigDecimal interestNrate) {
		this.interestNrate = interestNrate;
	}

	public String getInterestDmindex() {
		return this.interestDmindex;
	}

	public void setInterestDmindex(String interestDmindex) {
		this.interestDmindex = interestDmindex;
	}

	public String getInterestCcy() {
		return this.interestCcy;
	}

	public void setInterestCcy(String interestCcy) {
		this.interestCcy = interestCcy;
	}

	public String getIntRefSource() {
		return this.intRefSource;
	}

	public void setIntRefSource(String intRefSource) {
		this.intRefSource = intRefSource;
	}

	public BigDecimal getInterestSpread() {
		return this.interestSpread;
	}

	public void setInterestSpread(BigDecimal interestSpread) {
		this.interestSpread = interestSpread;
	}

	public String getInterestTerm() {
		return this.interestTerm;
	}

	public void setInterestTerm(String interestTerm) {
		this.interestTerm = interestTerm;
	}

	public String getIntAccAcccalc() {
		return this.intAccAcccalc;
	}

	public void setIntAccAcccalc(String intAccAcccalc) {
		this.intAccAcccalc = intAccAcccalc;
	}

	public String getIntAccBasis() {
		return this.intAccBasis;
	}

	public void setIntAccBasis(String intAccBasis) {
		this.intAccBasis = intAccBasis;
	}

	public String getInterestFwddecomp() {
		return this.interestFwddecomp;
	}

	public void setInterestFwddecomp(String interestFwddecomp) {
		this.interestFwddecomp = interestFwddecomp;
	}

	public String getSchedPayFreq() {
		return this.schedPayFreq;
	}

	public void setSchedPayFreq(String schedPayFreq) {
		this.schedPayFreq = schedPayFreq;
	}

	public BigDecimal getSchedPayAnnday() {
		return this.schedPayAnnday;
	}

	public void setSchedPayAnnday(BigDecimal schedPayAnnday) {
		this.schedPayAnnday = schedPayAnnday;
	}

	public String getSchedPayRule() {
		return this.schedPayRule;
	}

	public void setSchedPayRule(String schedPayRule) {
		this.schedPayRule = schedPayRule;
	}

	public String getSchedPayIntrule() {
		return this.schedPayIntrule;
	}

	public void setSchedPayIntrule(String schedPayIntrule) {
		this.schedPayIntrule = schedPayIntrule;
	}

	public String getSchedPayTime() {
		return this.schedPayTime;
	}

	public void setSchedPayTime(String schedPayTime) {
		this.schedPayTime = schedPayTime;
	}

	public String getSchedPayCal() {
		return this.schedPayCal;
	}

	public void setSchedPayCal(String schedPayCal) {
		this.schedPayCal = schedPayCal;
	}

	public String getSchedResetFreq() {
		return this.schedResetFreq;
	}

	public void setSchedResetFreq(String schedResetFreq) {
		this.schedResetFreq = schedResetFreq;
	}

	public BigDecimal getSchedResetAnnday() {
		return this.schedResetAnnday;
	}

	public void setSchedResetAnnday(BigDecimal schedResetAnnday) {
		this.schedResetAnnday = schedResetAnnday;
	}

	public String getSchedResetRule() {
		return this.schedResetRule;
	}

	public void setSchedResetRule(String schedResetRule) {
		this.schedResetRule = schedResetRule;
	}

	public String getSchedResetIntrule() {
		return this.schedResetIntrule;
	}

	public void setSchedResetIntrule(String schedResetIntrule) {
		this.schedResetIntrule = schedResetIntrule;
	}

	public String getSchedResetTime() {
		return this.schedResetTime;
	}

	public void setSchedResetTime(String schedResetTime) {
		this.schedResetTime = schedResetTime;
	}

	public String getSchedResetCal() {
		return this.schedResetCal;
	}

	public void setSchedResetCal(String schedResetCal) {
		this.schedResetCal = schedResetCal;
	}

	public String getCustom() {
		return this.custom;
	}

	public void setCustom(String custom) {
		this.custom = custom;
	}

	public BigDecimal getCrossCcyForexrate() {
		return this.crossCcyForexrate;
	}

	public void setCrossCcyForexrate(BigDecimal crossCcyForexrate) {
		this.crossCcyForexrate = crossCcyForexrate;
	}

	public String getNextfixing() {
		return this.nextfixing;
	}

	public void setNextfixing(String nextfixing) {
		this.nextfixing = nextfixing;
	}

	public String getIntResRefixmode() {
		return this.intResRefixmode;
	}

	public void setIntResRefixmode(String intResRefixmode) {
		this.intResRefixmode = intResRefixmode;
	}

	public BigDecimal getAmortSchedAnnday() {
		return this.amortSchedAnnday;
	}

	public void setAmortSchedAnnday(BigDecimal amortSchedAnnday) {
		this.amortSchedAnnday = amortSchedAnnday;
	}

	public String getIntResFxGap() {
		return this.intResFxGap;
	}

	public void setIntResFxGap(String intResFxGap) {
		this.intResFxGap = intResFxGap;
	}

	public String getSchedPayGap() {
		return this.schedPayGap;
	}

	public void setSchedPayGap(String schedPayGap) {
		this.schedPayGap = schedPayGap;
	}

	public String getSchedResetGap() {
		return this.schedResetGap;
	}

	public void setSchedResetGap(String schedResetGap) {
		this.schedResetGap = schedResetGap;
	}

	public String getIntResPaymentreset() {
		return this.intResPaymentreset;
	}

	public void setIntResPaymentreset(String intResPaymentreset) {
		this.intResPaymentreset = intResPaymentreset;
	}

	public String getBusmatdate() {
		return this.busmatdate;
	}

	public void setBusmatdate(String busmatdate) {
		this.busmatdate = busmatdate;
	}

	public BigDecimal getInterestFundsprd() {
		return this.interestFundsprd;
	}

	public void setInterestFundsprd(BigDecimal interestFundsprd) {
		this.interestFundsprd = interestFundsprd;
	}

	public String getIntResNtlGap() {
		return this.intResNtlGap;
	}

	public void setIntResNtlGap(String intResNtlGap) {
		this.intResNtlGap = intResNtlGap;
	}

	public String getInterestIntratetype() {
		return this.interestIntratetype;
	}

	public void setInterestIntratetype(String interestIntratetype) {
		this.interestIntratetype = interestIntratetype;
	}

	public String getPrmdiscountindex() {
		return this.prmdiscountindex;
	}

	public void setPrmdiscountindex(String prmdiscountindex) {
		this.prmdiscountindex = prmdiscountindex;
	}

	public String getQmethodindex() {
		return this.qmethodindex;
	}

	public void setQmethodindex(String qmethodindex) {
		this.qmethodindex = qmethodindex;
	}

	public String getQmethodccy() {
		return this.qmethodccy;
	}

	public void setQmethodccy(String qmethodccy) {
		this.qmethodccy = qmethodccy;
	}

	public String getPayproccparty() {
		return this.payproccparty;
	}

	public void setPayproccparty(String payproccparty) {
		this.payproccparty = payproccparty;
	}

	public String getFullypositionable() {
		return this.fullypositionable;
	}

	public void setFullypositionable(String fullypositionable) {
		this.fullypositionable = fullypositionable;
	}

	public String getAutopricing() {
		return this.autopricing;
	}

	public void setAutopricing(String autopricing) {
		this.autopricing = autopricing;
	}

	public String getDeliverable() {
		return this.deliverable;
	}

	public void setDeliverable(String deliverable) {
		this.deliverable = deliverable;
	}

	public String getNetcouponflows() {
		return this.netcouponflows;
	}

	public void setNetcouponflows(String netcouponflows) {
		this.netcouponflows = netcouponflows;
	}

	public String getCeccy() {
		return this.ceccy;
	}

	public void setCeccy(String ceccy) {
		this.ceccy = ceccy;
	}

	public String getGuarantor() {
		return this.guarantor;
	}

	public void setGuarantor(String guarantor) {
		this.guarantor = guarantor;
	}

	public String getCustid() {
		return this.custid;
	}

	public void setCustid(String custid) {
		this.custid = custid;
	}

	public String getDatesMonthEnd() {
		return this.datesMonthEnd;
	}

	public void setDatesMonthEnd(String datesMonthEnd) {
		this.datesMonthEnd = datesMonthEnd;
	}

	public String getCompdMethod() {
		return this.compdMethod;
	}

	public void setCompdMethod(String compdMethod) {
		this.compdMethod = compdMethod;
	}

	public String getPrincipalamortFlag() {
		return this.principalamortFlag;
	}

	public void setPrincipalamortFlag(String principalamortFlag) {
		this.principalamortFlag = principalamortFlag;
	}

	public String getPrincipalamortType() {
		return this.principalamortType;
	}

	public void setPrincipalamortType(String principalamortType) {
		this.principalamortType = principalamortType;
	}

	public String getPrincipalamortValue() {
		return this.principalamortValue;
	}

	public void setPrincipalamortValue(String principalamortValue) {
		this.principalamortValue = principalamortValue;
	}

	public String getPrincipalamortFreq() {
		return this.principalamortFreq;
	}

	public void setPrincipalamortFreq(String principalamortFreq) {
		this.principalamortFreq = principalamortFreq;
	}

	public String getPrincipalamort1stDate() {
		return this.principalamort1stDate;
	}

	public void setPrincipalamort1stDate(String principalamort1stDate) {
		this.principalamort1stDate = principalamort1stDate;
	}

	public String getPrincipalamortLastDate() {
		return this.principalamortLastDate;
	}

	public void setPrincipalamortLastDate(String principalamortLastDate) {
		this.principalamortLastDate = principalamortLastDate;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public String getCouponFstDate() {
		return this.couponFstDate;
	}

	public void setCouponFstDate(String couponFstDate) {
		this.couponFstDate = couponFstDate;
	}

	public String getCouponLastDate() {
		return this.couponLastDate;
	}

	public void setCouponLastDate(String couponLastDate) {
		this.couponLastDate = couponLastDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtbassetinfoId))
			return false;
		TmpAtbassetinfoId castOther = (TmpAtbassetinfoId) other;

		return ((this.getAssetId() == castOther.getAssetId()) || (this
				.getAssetId() != null && castOther.getAssetId() != null && this
				.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getAssetCode() == castOther.getAssetCode()) || (this
						.getAssetCode() != null
						&& castOther.getAssetCode() != null && this
						.getAssetCode().equals(castOther.getAssetCode())))
				&& ((this.getAssetName() == castOther.getAssetName()) || (this
						.getAssetName() != null
						&& castOther.getAssetName() != null && this
						.getAssetName().equals(castOther.getAssetName())))
				&& ((this.getAssetPublish() == castOther.getAssetPublish()) || (this
						.getAssetPublish() != null
						&& castOther.getAssetPublish() != null && this
						.getAssetPublish().equals(castOther.getAssetPublish())))
				&& ((this.getFaceValue() == castOther.getFaceValue()) || (this
						.getFaceValue() != null
						&& castOther.getFaceValue() != null && this
						.getFaceValue().equals(castOther.getFaceValue())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getAssetType() == castOther.getAssetType()) || (this
						.getAssetType() != null
						&& castOther.getAssetType() != null && this
						.getAssetType().equals(castOther.getAssetType())))
				&& ((this.getAssetSubType1() == castOther.getAssetSubType1()) || (this
						.getAssetSubType1() != null
						&& castOther.getAssetSubType1() != null && this
						.getAssetSubType1()
						.equals(castOther.getAssetSubType1())))
				&& ((this.getAssetSubType2() == castOther.getAssetSubType2()) || (this
						.getAssetSubType2() != null
						&& castOther.getAssetSubType2() != null && this
						.getAssetSubType2()
						.equals(castOther.getAssetSubType2())))
				&& ((this.getAssetSubType3() == castOther.getAssetSubType3()) || (this
						.getAssetSubType3() != null
						&& castOther.getAssetSubType3() != null && this
						.getAssetSubType3()
						.equals(castOther.getAssetSubType3())))
				&& ((this.getAcctType() == castOther.getAcctType()) || (this
						.getAcctType() != null
						&& castOther.getAcctType() != null && this
						.getAcctType().equals(castOther.getAcctType())))
				&& ((this.getInterestBase() == castOther.getInterestBase()) || (this
						.getInterestBase() != null
						&& castOther.getInterestBase() != null && this
						.getInterestBase().equals(castOther.getInterestBase())))
				&& ((this.getInterestFrequency() == castOther
						.getInterestFrequency()) || (this
						.getInterestFrequency() != null
						&& castOther.getInterestFrequency() != null && this
						.getInterestFrequency().equals(
								castOther.getInterestFrequency())))
				&& ((this.getCurCode() == castOther.getCurCode()) || (this
						.getCurCode() != null && castOther.getCurCode() != null && this
						.getCurCode().equals(castOther.getCurCode())))
				&& ((this.getValueDate() == castOther.getValueDate()) || (this
						.getValueDate() != null
						&& castOther.getValueDate() != null && this
						.getValueDate().equals(castOther.getValueDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this
						.getEndDate() != null && castOther.getEndDate() != null && this
						.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getTransPlaces() == castOther.getTransPlaces()) || (this
						.getTransPlaces() != null
						&& castOther.getTransPlaces() != null && this
						.getTransPlaces().equals(castOther.getTransPlaces())))
				&& ((this.getInterestType() == castOther.getInterestType()) || (this
						.getInterestType() != null
						&& castOther.getInterestType() != null && this
						.getInterestType().equals(castOther.getInterestType())))
				&& ((this.getXdividendXdivrule() == castOther
						.getXdividendXdivrule()) || (this
						.getXdividendXdivrule() != null
						&& castOther.getXdividendXdivrule() != null && this
						.getXdividendXdivrule().equals(
								castOther.getXdividendXdivrule())))
				&& ((this.getXdividendXdivbdrule() == castOther
						.getXdividendXdivbdrule()) || (this
						.getXdividendXdivbdrule() != null
						&& castOther.getXdividendXdivbdrule() != null && this
						.getXdividendXdivbdrule().equals(
								castOther.getXdividendXdivbdrule())))
				&& ((this.getDaysruleSettleRule() == castOther
						.getDaysruleSettleRule()) || (this
						.getDaysruleSettleRule() != null
						&& castOther.getDaysruleSettleRule() != null && this
						.getDaysruleSettleRule().equals(
								castOther.getDaysruleSettleRule())))
				&& ((this.getDaysruleSettleBdrule() == castOther
						.getDaysruleSettleBdrule()) || (this
						.getDaysruleSettleBdrule() != null
						&& castOther.getDaysruleSettleBdrule() != null && this
						.getDaysruleSettleBdrule().equals(
								castOther.getDaysruleSettleBdrule())))
				&& ((this.getDaysruleSettleDays() == castOther
						.getDaysruleSettleDays()) || (this
						.getDaysruleSettleDays() != null
						&& castOther.getDaysruleSettleDays() != null && this
						.getDaysruleSettleDays().equals(
								castOther.getDaysruleSettleDays())))
				&& ((this.getDaysruleValueDays() == castOther
						.getDaysruleValueDays()) || (this
						.getDaysruleValueDays() != null
						&& castOther.getDaysruleValueDays() != null && this
						.getDaysruleValueDays().equals(
								castOther.getDaysruleValueDays())))
				&& ((this.getDaysruleValueRule() == castOther
						.getDaysruleValueRule()) || (this
						.getDaysruleValueRule() != null
						&& castOther.getDaysruleValueRule() != null && this
						.getDaysruleValueRule().equals(
								castOther.getDaysruleValueRule())))
				&& ((this.getDaysruleValueBdrule() == castOther
						.getDaysruleValueBdrule()) || (this
						.getDaysruleValueBdrule() != null
						&& castOther.getDaysruleValueBdrule() != null && this
						.getDaysruleValueBdrule().equals(
								castOther.getDaysruleValueBdrule())))
				&& ((this.getLformatPriceformCentunits() == castOther
						.getLformatPriceformCentunits()) || (this
						.getLformatPriceformCentunits() != null
						&& castOther.getLformatPriceformCentunits() != null && this
						.getLformatPriceformCentunits().equals(
								castOther.getLformatPriceformCentunits())))
				&& ((this.getLformatPriceformRound() == castOther
						.getLformatPriceformRound()) || (this
						.getLformatPriceformRound() != null
						&& castOther.getLformatPriceformRound() != null && this
						.getLformatPriceformRound().equals(
								castOther.getLformatPriceformRound())))
				&& ((this.getCollateral() == castOther.getCollateral()) || (this
						.getCollateral() != null
						&& castOther.getCollateral() != null && this
						.getCollateral().equals(castOther.getCollateral())))
				&& ((this.getCountry() == castOther.getCountry()) || (this
						.getCountry() != null && castOther.getCountry() != null && this
						.getCountry().equals(castOther.getCountry())))
				&& ((this.getSizeissue() == castOther.getSizeissue()) || (this
						.getSizeissue() != null
						&& castOther.getSizeissue() != null && this
						.getSizeissue().equals(castOther.getSizeissue())))
				&& ((this.getPayingagent() == castOther.getPayingagent()) || (this
						.getPayingagent() != null
						&& castOther.getPayingagent() != null && this
						.getPayingagent().equals(castOther.getPayingagent())))
				&& ((this.getSrtylevel() == castOther.getSrtylevel()) || (this
						.getSrtylevel() != null
						&& castOther.getSrtylevel() != null && this
						.getSrtylevel().equals(castOther.getSrtylevel())))
				&& ((this.getRatio() == castOther.getRatio()) || (this
						.getRatio() != null && castOther.getRatio() != null && this
						.getRatio().equals(castOther.getRatio())))
				&& ((this.getQuote() == castOther.getQuote()) || (this
						.getQuote() != null && castOther.getQuote() != null && this
						.getQuote().equals(castOther.getQuote())))
				&& ((this.getYieldformula() == castOther.getYieldformula()) || (this
						.getYieldformula() != null
						&& castOther.getYieldformula() != null && this
						.getYieldformula().equals(castOther.getYieldformula())))
				&& ((this.getPriceformula() == castOther.getPriceformula()) || (this
						.getPriceformula() != null
						&& castOther.getPriceformula() != null && this
						.getPriceformula().equals(castOther.getPriceformula())))
				&& ((this.getYpspread() == castOther.getYpspread()) || (this
						.getYpspread() != null
						&& castOther.getYpspread() != null && this
						.getYpspread().equals(castOther.getYpspread())))
				&& ((this.getYield() == castOther.getYield()) || (this
						.getYield() != null && castOther.getYield() != null && this
						.getYield().equals(castOther.getYield())))
				&& ((this.getRiskindex() == castOther.getRiskindex()) || (this
						.getRiskindex() != null
						&& castOther.getRiskindex() != null && this
						.getRiskindex().equals(castOther.getRiskindex())))
				&& ((this.getFundindex() == castOther.getFundindex()) || (this
						.getFundindex() != null
						&& castOther.getFundindex() != null && this
						.getFundindex().equals(castOther.getFundindex())))
				&& ((this.getFundspread() == castOther.getFundspread()) || (this
						.getFundspread() != null
						&& castOther.getFundspread() != null && this
						.getFundspread().equals(castOther.getFundspread())))
				&& ((this.getRepospread() == castOther.getRepospread()) || (this
						.getRepospread() != null
						&& castOther.getRepospread() != null && this
						.getRepospread().equals(castOther.getRepospread())))
				&& ((this.getCallable() == castOther.getCallable()) || (this
						.getCallable() != null
						&& castOther.getCallable() != null && this
						.getCallable().equals(castOther.getCallable())))
				&& ((this.getPuttable() == castOther.getPuttable()) || (this
						.getPuttable() != null
						&& castOther.getPuttable() != null && this
						.getPuttable().equals(castOther.getPuttable())))
				&& ((this.getIssueprice() == castOther.getIssueprice()) || (this
						.getIssueprice() != null
						&& castOther.getIssueprice() != null && this
						.getIssueprice().equals(castOther.getIssueprice())))
				&& ((this.getRedemptionprice() == castOther
						.getRedemptionprice()) || (this.getRedemptionprice() != null
						&& castOther.getRedemptionprice() != null && this
						.getRedemptionprice().equals(
								castOther.getRedemptionprice())))
				&& ((this.getPors() == castOther.getPors()) || (this.getPors() != null
						&& castOther.getPors() != null && this.getPors()
						.equals(castOther.getPors())))
				&& ((this.getAssetccy() == castOther.getAssetccy()) || (this
						.getAssetccy() != null
						&& castOther.getAssetccy() != null && this
						.getAssetccy().equals(castOther.getAssetccy())))
				&& ((this.getInterestNrate() == castOther.getInterestNrate()) || (this
						.getInterestNrate() != null
						&& castOther.getInterestNrate() != null && this
						.getInterestNrate()
						.equals(castOther.getInterestNrate())))
				&& ((this.getInterestDmindex() == castOther
						.getInterestDmindex()) || (this.getInterestDmindex() != null
						&& castOther.getInterestDmindex() != null && this
						.getInterestDmindex().equals(
								castOther.getInterestDmindex())))
				&& ((this.getInterestCcy() == castOther.getInterestCcy()) || (this
						.getInterestCcy() != null
						&& castOther.getInterestCcy() != null && this
						.getInterestCcy().equals(castOther.getInterestCcy())))
				&& ((this.getIntRefSource() == castOther.getIntRefSource()) || (this
						.getIntRefSource() != null
						&& castOther.getIntRefSource() != null && this
						.getIntRefSource().equals(castOther.getIntRefSource())))
				&& ((this.getInterestSpread() == castOther.getInterestSpread()) || (this
						.getInterestSpread() != null
						&& castOther.getInterestSpread() != null && this
						.getInterestSpread().equals(
								castOther.getInterestSpread())))
				&& ((this.getInterestTerm() == castOther.getInterestTerm()) || (this
						.getInterestTerm() != null
						&& castOther.getInterestTerm() != null && this
						.getInterestTerm().equals(castOther.getInterestTerm())))
				&& ((this.getIntAccAcccalc() == castOther.getIntAccAcccalc()) || (this
						.getIntAccAcccalc() != null
						&& castOther.getIntAccAcccalc() != null && this
						.getIntAccAcccalc()
						.equals(castOther.getIntAccAcccalc())))
				&& ((this.getIntAccBasis() == castOther.getIntAccBasis()) || (this
						.getIntAccBasis() != null
						&& castOther.getIntAccBasis() != null && this
						.getIntAccBasis().equals(castOther.getIntAccBasis())))
				&& ((this.getInterestFwddecomp() == castOther
						.getInterestFwddecomp()) || (this
						.getInterestFwddecomp() != null
						&& castOther.getInterestFwddecomp() != null && this
						.getInterestFwddecomp().equals(
								castOther.getInterestFwddecomp())))
				&& ((this.getSchedPayFreq() == castOther.getSchedPayFreq()) || (this
						.getSchedPayFreq() != null
						&& castOther.getSchedPayFreq() != null && this
						.getSchedPayFreq().equals(castOther.getSchedPayFreq())))
				&& ((this.getSchedPayAnnday() == castOther.getSchedPayAnnday()) || (this
						.getSchedPayAnnday() != null
						&& castOther.getSchedPayAnnday() != null && this
						.getSchedPayAnnday().equals(
								castOther.getSchedPayAnnday())))
				&& ((this.getSchedPayRule() == castOther.getSchedPayRule()) || (this
						.getSchedPayRule() != null
						&& castOther.getSchedPayRule() != null && this
						.getSchedPayRule().equals(castOther.getSchedPayRule())))
				&& ((this.getSchedPayIntrule() == castOther
						.getSchedPayIntrule()) || (this.getSchedPayIntrule() != null
						&& castOther.getSchedPayIntrule() != null && this
						.getSchedPayIntrule().equals(
								castOther.getSchedPayIntrule())))
				&& ((this.getSchedPayTime() == castOther.getSchedPayTime()) || (this
						.getSchedPayTime() != null
						&& castOther.getSchedPayTime() != null && this
						.getSchedPayTime().equals(castOther.getSchedPayTime())))
				&& ((this.getSchedPayCal() == castOther.getSchedPayCal()) || (this
						.getSchedPayCal() != null
						&& castOther.getSchedPayCal() != null && this
						.getSchedPayCal().equals(castOther.getSchedPayCal())))
				&& ((this.getSchedResetFreq() == castOther.getSchedResetFreq()) || (this
						.getSchedResetFreq() != null
						&& castOther.getSchedResetFreq() != null && this
						.getSchedResetFreq().equals(
								castOther.getSchedResetFreq())))
				&& ((this.getSchedResetAnnday() == castOther
						.getSchedResetAnnday()) || (this.getSchedResetAnnday() != null
						&& castOther.getSchedResetAnnday() != null && this
						.getSchedResetAnnday().equals(
								castOther.getSchedResetAnnday())))
				&& ((this.getSchedResetRule() == castOther.getSchedResetRule()) || (this
						.getSchedResetRule() != null
						&& castOther.getSchedResetRule() != null && this
						.getSchedResetRule().equals(
								castOther.getSchedResetRule())))
				&& ((this.getSchedResetIntrule() == castOther
						.getSchedResetIntrule()) || (this
						.getSchedResetIntrule() != null
						&& castOther.getSchedResetIntrule() != null && this
						.getSchedResetIntrule().equals(
								castOther.getSchedResetIntrule())))
				&& ((this.getSchedResetTime() == castOther.getSchedResetTime()) || (this
						.getSchedResetTime() != null
						&& castOther.getSchedResetTime() != null && this
						.getSchedResetTime().equals(
								castOther.getSchedResetTime())))
				&& ((this.getSchedResetCal() == castOther.getSchedResetCal()) || (this
						.getSchedResetCal() != null
						&& castOther.getSchedResetCal() != null && this
						.getSchedResetCal()
						.equals(castOther.getSchedResetCal())))
				&& ((this.getCustom() == castOther.getCustom()) || (this
						.getCustom() != null && castOther.getCustom() != null && this
						.getCustom().equals(castOther.getCustom())))
				&& ((this.getCrossCcyForexrate() == castOther
						.getCrossCcyForexrate()) || (this
						.getCrossCcyForexrate() != null
						&& castOther.getCrossCcyForexrate() != null && this
						.getCrossCcyForexrate().equals(
								castOther.getCrossCcyForexrate())))
				&& ((this.getNextfixing() == castOther.getNextfixing()) || (this
						.getNextfixing() != null
						&& castOther.getNextfixing() != null && this
						.getNextfixing().equals(castOther.getNextfixing())))
				&& ((this.getIntResRefixmode() == castOther
						.getIntResRefixmode()) || (this.getIntResRefixmode() != null
						&& castOther.getIntResRefixmode() != null && this
						.getIntResRefixmode().equals(
								castOther.getIntResRefixmode())))
				&& ((this.getAmortSchedAnnday() == castOther
						.getAmortSchedAnnday()) || (this.getAmortSchedAnnday() != null
						&& castOther.getAmortSchedAnnday() != null && this
						.getAmortSchedAnnday().equals(
								castOther.getAmortSchedAnnday())))
				&& ((this.getIntResFxGap() == castOther.getIntResFxGap()) || (this
						.getIntResFxGap() != null
						&& castOther.getIntResFxGap() != null && this
						.getIntResFxGap().equals(castOther.getIntResFxGap())))
				&& ((this.getSchedPayGap() == castOther.getSchedPayGap()) || (this
						.getSchedPayGap() != null
						&& castOther.getSchedPayGap() != null && this
						.getSchedPayGap().equals(castOther.getSchedPayGap())))
				&& ((this.getSchedResetGap() == castOther.getSchedResetGap()) || (this
						.getSchedResetGap() != null
						&& castOther.getSchedResetGap() != null && this
						.getSchedResetGap()
						.equals(castOther.getSchedResetGap())))
				&& ((this.getIntResPaymentreset() == castOther
						.getIntResPaymentreset()) || (this
						.getIntResPaymentreset() != null
						&& castOther.getIntResPaymentreset() != null && this
						.getIntResPaymentreset().equals(
								castOther.getIntResPaymentreset())))
				&& ((this.getBusmatdate() == castOther.getBusmatdate()) || (this
						.getBusmatdate() != null
						&& castOther.getBusmatdate() != null && this
						.getBusmatdate().equals(castOther.getBusmatdate())))
				&& ((this.getInterestFundsprd() == castOther
						.getInterestFundsprd()) || (this.getInterestFundsprd() != null
						&& castOther.getInterestFundsprd() != null && this
						.getInterestFundsprd().equals(
								castOther.getInterestFundsprd())))
				&& ((this.getIntResNtlGap() == castOther.getIntResNtlGap()) || (this
						.getIntResNtlGap() != null
						&& castOther.getIntResNtlGap() != null && this
						.getIntResNtlGap().equals(castOther.getIntResNtlGap())))
				&& ((this.getInterestIntratetype() == castOther
						.getInterestIntratetype()) || (this
						.getInterestIntratetype() != null
						&& castOther.getInterestIntratetype() != null && this
						.getInterestIntratetype().equals(
								castOther.getInterestIntratetype())))
				&& ((this.getPrmdiscountindex() == castOther
						.getPrmdiscountindex()) || (this.getPrmdiscountindex() != null
						&& castOther.getPrmdiscountindex() != null && this
						.getPrmdiscountindex().equals(
								castOther.getPrmdiscountindex())))
				&& ((this.getQmethodindex() == castOther.getQmethodindex()) || (this
						.getQmethodindex() != null
						&& castOther.getQmethodindex() != null && this
						.getQmethodindex().equals(castOther.getQmethodindex())))
				&& ((this.getQmethodccy() == castOther.getQmethodccy()) || (this
						.getQmethodccy() != null
						&& castOther.getQmethodccy() != null && this
						.getQmethodccy().equals(castOther.getQmethodccy())))
				&& ((this.getPayproccparty() == castOther.getPayproccparty()) || (this
						.getPayproccparty() != null
						&& castOther.getPayproccparty() != null && this
						.getPayproccparty()
						.equals(castOther.getPayproccparty())))
				&& ((this.getFullypositionable() == castOther
						.getFullypositionable()) || (this
						.getFullypositionable() != null
						&& castOther.getFullypositionable() != null && this
						.getFullypositionable().equals(
								castOther.getFullypositionable())))
				&& ((this.getAutopricing() == castOther.getAutopricing()) || (this
						.getAutopricing() != null
						&& castOther.getAutopricing() != null && this
						.getAutopricing().equals(castOther.getAutopricing())))
				&& ((this.getDeliverable() == castOther.getDeliverable()) || (this
						.getDeliverable() != null
						&& castOther.getDeliverable() != null && this
						.getDeliverable().equals(castOther.getDeliverable())))
				&& ((this.getNetcouponflows() == castOther.getNetcouponflows()) || (this
						.getNetcouponflows() != null
						&& castOther.getNetcouponflows() != null && this
						.getNetcouponflows().equals(
								castOther.getNetcouponflows())))
				&& ((this.getCeccy() == castOther.getCeccy()) || (this
						.getCeccy() != null && castOther.getCeccy() != null && this
						.getCeccy().equals(castOther.getCeccy())))
				&& ((this.getGuarantor() == castOther.getGuarantor()) || (this
						.getGuarantor() != null
						&& castOther.getGuarantor() != null && this
						.getGuarantor().equals(castOther.getGuarantor())))
				&& ((this.getCustid() == castOther.getCustid()) || (this
						.getCustid() != null && castOther.getCustid() != null && this
						.getCustid().equals(castOther.getCustid())))
				&& ((this.getDatesMonthEnd() == castOther.getDatesMonthEnd()) || (this
						.getDatesMonthEnd() != null
						&& castOther.getDatesMonthEnd() != null && this
						.getDatesMonthEnd()
						.equals(castOther.getDatesMonthEnd())))
				&& ((this.getCompdMethod() == castOther.getCompdMethod()) || (this
						.getCompdMethod() != null
						&& castOther.getCompdMethod() != null && this
						.getCompdMethod().equals(castOther.getCompdMethod())))
				&& ((this.getPrincipalamortFlag() == castOther
						.getPrincipalamortFlag()) || (this
						.getPrincipalamortFlag() != null
						&& castOther.getPrincipalamortFlag() != null && this
						.getPrincipalamortFlag().equals(
								castOther.getPrincipalamortFlag())))
				&& ((this.getPrincipalamortType() == castOther
						.getPrincipalamortType()) || (this
						.getPrincipalamortType() != null
						&& castOther.getPrincipalamortType() != null && this
						.getPrincipalamortType().equals(
								castOther.getPrincipalamortType())))
				&& ((this.getPrincipalamortValue() == castOther
						.getPrincipalamortValue()) || (this
						.getPrincipalamortValue() != null
						&& castOther.getPrincipalamortValue() != null && this
						.getPrincipalamortValue().equals(
								castOther.getPrincipalamortValue())))
				&& ((this.getPrincipalamortFreq() == castOther
						.getPrincipalamortFreq()) || (this
						.getPrincipalamortFreq() != null
						&& castOther.getPrincipalamortFreq() != null && this
						.getPrincipalamortFreq().equals(
								castOther.getPrincipalamortFreq())))
				&& ((this.getPrincipalamort1stDate() == castOther
						.getPrincipalamort1stDate()) || (this
						.getPrincipalamort1stDate() != null
						&& castOther.getPrincipalamort1stDate() != null && this
						.getPrincipalamort1stDate().equals(
								castOther.getPrincipalamort1stDate())))
				&& ((this.getPrincipalamortLastDate() == castOther
						.getPrincipalamortLastDate()) || (this
						.getPrincipalamortLastDate() != null
						&& castOther.getPrincipalamortLastDate() != null && this
						.getPrincipalamortLastDate().equals(
								castOther.getPrincipalamortLastDate())))
				&& (this.getStatus() == castOther.getStatus())
				&& ((this.getCouponFstDate() == castOther.getCouponFstDate()) || (this
						.getCouponFstDate() != null
						&& castOther.getCouponFstDate() != null && this
						.getCouponFstDate()
						.equals(castOther.getCouponFstDate())))
				&& ((this.getCouponLastDate() == castOther.getCouponLastDate()) || (this
						.getCouponLastDate() != null
						&& castOther.getCouponLastDate() != null && this
						.getCouponLastDate().equals(
								castOther.getCouponLastDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result
				+ (getAssetCode() == null ? 0 : this.getAssetCode().hashCode());
		result = 37 * result
				+ (getAssetName() == null ? 0 : this.getAssetName().hashCode());
		result = 37
				* result
				+ (getAssetPublish() == null ? 0 : this.getAssetPublish()
						.hashCode());
		result = 37 * result
				+ (getFaceValue() == null ? 0 : this.getFaceValue().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result
				+ (getAssetType() == null ? 0 : this.getAssetType().hashCode());
		result = 37
				* result
				+ (getAssetSubType1() == null ? 0 : this.getAssetSubType1()
						.hashCode());
		result = 37
				* result
				+ (getAssetSubType2() == null ? 0 : this.getAssetSubType2()
						.hashCode());
		result = 37
				* result
				+ (getAssetSubType3() == null ? 0 : this.getAssetSubType3()
						.hashCode());
		result = 37 * result
				+ (getAcctType() == null ? 0 : this.getAcctType().hashCode());
		result = 37
				* result
				+ (getInterestBase() == null ? 0 : this.getInterestBase()
						.hashCode());
		result = 37
				* result
				+ (getInterestFrequency() == null ? 0 : this
						.getInterestFrequency().hashCode());
		result = 37 * result
				+ (getCurCode() == null ? 0 : this.getCurCode().hashCode());
		result = 37 * result
				+ (getValueDate() == null ? 0 : this.getValueDate().hashCode());
		result = 37 * result
				+ (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37
				* result
				+ (getTransPlaces() == null ? 0 : this.getTransPlaces()
						.hashCode());
		result = 37
				* result
				+ (getInterestType() == null ? 0 : this.getInterestType()
						.hashCode());
		result = 37
				* result
				+ (getXdividendXdivrule() == null ? 0 : this
						.getXdividendXdivrule().hashCode());
		result = 37
				* result
				+ (getXdividendXdivbdrule() == null ? 0 : this
						.getXdividendXdivbdrule().hashCode());
		result = 37
				* result
				+ (getDaysruleSettleRule() == null ? 0 : this
						.getDaysruleSettleRule().hashCode());
		result = 37
				* result
				+ (getDaysruleSettleBdrule() == null ? 0 : this
						.getDaysruleSettleBdrule().hashCode());
		result = 37
				* result
				+ (getDaysruleSettleDays() == null ? 0 : this
						.getDaysruleSettleDays().hashCode());
		result = 37
				* result
				+ (getDaysruleValueDays() == null ? 0 : this
						.getDaysruleValueDays().hashCode());
		result = 37
				* result
				+ (getDaysruleValueRule() == null ? 0 : this
						.getDaysruleValueRule().hashCode());
		result = 37
				* result
				+ (getDaysruleValueBdrule() == null ? 0 : this
						.getDaysruleValueBdrule().hashCode());
		result = 37
				* result
				+ (getLformatPriceformCentunits() == null ? 0 : this
						.getLformatPriceformCentunits().hashCode());
		result = 37
				* result
				+ (getLformatPriceformRound() == null ? 0 : this
						.getLformatPriceformRound().hashCode());
		result = 37
				* result
				+ (getCollateral() == null ? 0 : this.getCollateral()
						.hashCode());
		result = 37 * result
				+ (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result
				+ (getSizeissue() == null ? 0 : this.getSizeissue().hashCode());
		result = 37
				* result
				+ (getPayingagent() == null ? 0 : this.getPayingagent()
						.hashCode());
		result = 37 * result
				+ (getSrtylevel() == null ? 0 : this.getSrtylevel().hashCode());
		result = 37 * result
				+ (getRatio() == null ? 0 : this.getRatio().hashCode());
		result = 37 * result
				+ (getQuote() == null ? 0 : this.getQuote().hashCode());
		result = 37
				* result
				+ (getYieldformula() == null ? 0 : this.getYieldformula()
						.hashCode());
		result = 37
				* result
				+ (getPriceformula() == null ? 0 : this.getPriceformula()
						.hashCode());
		result = 37 * result
				+ (getYpspread() == null ? 0 : this.getYpspread().hashCode());
		result = 37 * result
				+ (getYield() == null ? 0 : this.getYield().hashCode());
		result = 37 * result
				+ (getRiskindex() == null ? 0 : this.getRiskindex().hashCode());
		result = 37 * result
				+ (getFundindex() == null ? 0 : this.getFundindex().hashCode());
		result = 37
				* result
				+ (getFundspread() == null ? 0 : this.getFundspread()
						.hashCode());
		result = 37
				* result
				+ (getRepospread() == null ? 0 : this.getRepospread()
						.hashCode());
		result = 37 * result
				+ (getCallable() == null ? 0 : this.getCallable().hashCode());
		result = 37 * result
				+ (getPuttable() == null ? 0 : this.getPuttable().hashCode());
		result = 37
				* result
				+ (getIssueprice() == null ? 0 : this.getIssueprice()
						.hashCode());
		result = 37
				* result
				+ (getRedemptionprice() == null ? 0 : this.getRedemptionprice()
						.hashCode());
		result = 37 * result
				+ (getPors() == null ? 0 : this.getPors().hashCode());
		result = 37 * result
				+ (getAssetccy() == null ? 0 : this.getAssetccy().hashCode());
		result = 37
				* result
				+ (getInterestNrate() == null ? 0 : this.getInterestNrate()
						.hashCode());
		result = 37
				* result
				+ (getInterestDmindex() == null ? 0 : this.getInterestDmindex()
						.hashCode());
		result = 37
				* result
				+ (getInterestCcy() == null ? 0 : this.getInterestCcy()
						.hashCode());
		result = 37
				* result
				+ (getIntRefSource() == null ? 0 : this.getIntRefSource()
						.hashCode());
		result = 37
				* result
				+ (getInterestSpread() == null ? 0 : this.getInterestSpread()
						.hashCode());
		result = 37
				* result
				+ (getInterestTerm() == null ? 0 : this.getInterestTerm()
						.hashCode());
		result = 37
				* result
				+ (getIntAccAcccalc() == null ? 0 : this.getIntAccAcccalc()
						.hashCode());
		result = 37
				* result
				+ (getIntAccBasis() == null ? 0 : this.getIntAccBasis()
						.hashCode());
		result = 37
				* result
				+ (getInterestFwddecomp() == null ? 0 : this
						.getInterestFwddecomp().hashCode());
		result = 37
				* result
				+ (getSchedPayFreq() == null ? 0 : this.getSchedPayFreq()
						.hashCode());
		result = 37
				* result
				+ (getSchedPayAnnday() == null ? 0 : this.getSchedPayAnnday()
						.hashCode());
		result = 37
				* result
				+ (getSchedPayRule() == null ? 0 : this.getSchedPayRule()
						.hashCode());
		result = 37
				* result
				+ (getSchedPayIntrule() == null ? 0 : this.getSchedPayIntrule()
						.hashCode());
		result = 37
				* result
				+ (getSchedPayTime() == null ? 0 : this.getSchedPayTime()
						.hashCode());
		result = 37
				* result
				+ (getSchedPayCal() == null ? 0 : this.getSchedPayCal()
						.hashCode());
		result = 37
				* result
				+ (getSchedResetFreq() == null ? 0 : this.getSchedResetFreq()
						.hashCode());
		result = 37
				* result
				+ (getSchedResetAnnday() == null ? 0 : this
						.getSchedResetAnnday().hashCode());
		result = 37
				* result
				+ (getSchedResetRule() == null ? 0 : this.getSchedResetRule()
						.hashCode());
		result = 37
				* result
				+ (getSchedResetIntrule() == null ? 0 : this
						.getSchedResetIntrule().hashCode());
		result = 37
				* result
				+ (getSchedResetTime() == null ? 0 : this.getSchedResetTime()
						.hashCode());
		result = 37
				* result
				+ (getSchedResetCal() == null ? 0 : this.getSchedResetCal()
						.hashCode());
		result = 37 * result
				+ (getCustom() == null ? 0 : this.getCustom().hashCode());
		result = 37
				* result
				+ (getCrossCcyForexrate() == null ? 0 : this
						.getCrossCcyForexrate().hashCode());
		result = 37
				* result
				+ (getNextfixing() == null ? 0 : this.getNextfixing()
						.hashCode());
		result = 37
				* result
				+ (getIntResRefixmode() == null ? 0 : this.getIntResRefixmode()
						.hashCode());
		result = 37
				* result
				+ (getAmortSchedAnnday() == null ? 0 : this
						.getAmortSchedAnnday().hashCode());
		result = 37
				* result
				+ (getIntResFxGap() == null ? 0 : this.getIntResFxGap()
						.hashCode());
		result = 37
				* result
				+ (getSchedPayGap() == null ? 0 : this.getSchedPayGap()
						.hashCode());
		result = 37
				* result
				+ (getSchedResetGap() == null ? 0 : this.getSchedResetGap()
						.hashCode());
		result = 37
				* result
				+ (getIntResPaymentreset() == null ? 0 : this
						.getIntResPaymentreset().hashCode());
		result = 37
				* result
				+ (getBusmatdate() == null ? 0 : this.getBusmatdate()
						.hashCode());
		result = 37
				* result
				+ (getInterestFundsprd() == null ? 0 : this
						.getInterestFundsprd().hashCode());
		result = 37
				* result
				+ (getIntResNtlGap() == null ? 0 : this.getIntResNtlGap()
						.hashCode());
		result = 37
				* result
				+ (getInterestIntratetype() == null ? 0 : this
						.getInterestIntratetype().hashCode());
		result = 37
				* result
				+ (getPrmdiscountindex() == null ? 0 : this
						.getPrmdiscountindex().hashCode());
		result = 37
				* result
				+ (getQmethodindex() == null ? 0 : this.getQmethodindex()
						.hashCode());
		result = 37
				* result
				+ (getQmethodccy() == null ? 0 : this.getQmethodccy()
						.hashCode());
		result = 37
				* result
				+ (getPayproccparty() == null ? 0 : this.getPayproccparty()
						.hashCode());
		result = 37
				* result
				+ (getFullypositionable() == null ? 0 : this
						.getFullypositionable().hashCode());
		result = 37
				* result
				+ (getAutopricing() == null ? 0 : this.getAutopricing()
						.hashCode());
		result = 37
				* result
				+ (getDeliverable() == null ? 0 : this.getDeliverable()
						.hashCode());
		result = 37
				* result
				+ (getNetcouponflows() == null ? 0 : this.getNetcouponflows()
						.hashCode());
		result = 37 * result
				+ (getCeccy() == null ? 0 : this.getCeccy().hashCode());
		result = 37 * result
				+ (getGuarantor() == null ? 0 : this.getGuarantor().hashCode());
		result = 37 * result
				+ (getCustid() == null ? 0 : this.getCustid().hashCode());
		result = 37
				* result
				+ (getDatesMonthEnd() == null ? 0 : this.getDatesMonthEnd()
						.hashCode());
		result = 37
				* result
				+ (getCompdMethod() == null ? 0 : this.getCompdMethod()
						.hashCode());
		result = 37
				* result
				+ (getPrincipalamortFlag() == null ? 0 : this
						.getPrincipalamortFlag().hashCode());
		result = 37
				* result
				+ (getPrincipalamortType() == null ? 0 : this
						.getPrincipalamortType().hashCode());
		result = 37
				* result
				+ (getPrincipalamortValue() == null ? 0 : this
						.getPrincipalamortValue().hashCode());
		result = 37
				* result
				+ (getPrincipalamortFreq() == null ? 0 : this
						.getPrincipalamortFreq().hashCode());
		result = 37
				* result
				+ (getPrincipalamort1stDate() == null ? 0 : this
						.getPrincipalamort1stDate().hashCode());
		result = 37
				* result
				+ (getPrincipalamortLastDate() == null ? 0 : this
						.getPrincipalamortLastDate().hashCode());
		result = 37 * result + this.getStatus();
		result = 37
				* result
				+ (getCouponFstDate() == null ? 0 : this.getCouponFstDate()
						.hashCode());
		result = 37
				* result
				+ (getCouponLastDate() == null ? 0 : this.getCouponLastDate()
						.hashCode());
		return result;
	}

}
