package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbcashflow generated by hbm2java
 */
public class TmpAtbcashflow implements java.io.Serializable {

	private TmpAtbcashflowId id;

	public TmpAtbcashflow() {
	}

	public TmpAtbcashflow(TmpAtbcashflowId id) {
		this.id = id;
	}

	public TmpAtbcashflowId getId() {
		return this.id;
	}

	public void setId(TmpAtbcashflowId id) {
		this.id = id;
	}

}
