package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtunpostlistId generated by hbm2java
 */
public class TmpAtunpostlistId implements java.io.Serializable {

	private BigDecimal serialno;
	private BigDecimal listid;
	private String description;
	private String account;
	private String deptno;
	private String projno;
	private char direction;
	private BigDecimal amount;
	private String curcode;
	private BigDecimal foreignamount;
	private Double rate;
	private String billno;
	private String payreceivno;
	private Double quantity;
	private Double price;
	private String bankacct;
	private String trntype;
	private String catcode;
	private String acctype;
	private String erykey;

	public TmpAtunpostlistId() {
	}

	public TmpAtunpostlistId(BigDecimal listid, String account, char direction,
			BigDecimal amount, String curcode) {
		this.listid = listid;
		this.account = account;
		this.direction = direction;
		this.amount = amount;
		this.curcode = curcode;
	}

	public TmpAtunpostlistId(BigDecimal serialno, BigDecimal listid,
			String description, String account, String deptno, String projno,
			char direction, BigDecimal amount, String curcode,
			BigDecimal foreignamount, Double rate, String billno,
			String payreceivno, Double quantity, Double price, String bankacct,
			String trntype, String catcode, String acctype, String erykey) {
		this.serialno = serialno;
		this.listid = listid;
		this.description = description;
		this.account = account;
		this.deptno = deptno;
		this.projno = projno;
		this.direction = direction;
		this.amount = amount;
		this.curcode = curcode;
		this.foreignamount = foreignamount;
		this.rate = rate;
		this.billno = billno;
		this.payreceivno = payreceivno;
		this.quantity = quantity;
		this.price = price;
		this.bankacct = bankacct;
		this.trntype = trntype;
		this.catcode = catcode;
		this.acctype = acctype;
		this.erykey = erykey;
	}

	public BigDecimal getSerialno() {
		return this.serialno;
	}

	public void setSerialno(BigDecimal serialno) {
		this.serialno = serialno;
	}

	public BigDecimal getListid() {
		return this.listid;
	}

	public void setListid(BigDecimal listid) {
		this.listid = listid;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getDeptno() {
		return this.deptno;
	}

	public void setDeptno(String deptno) {
		this.deptno = deptno;
	}

	public String getProjno() {
		return this.projno;
	}

	public void setProjno(String projno) {
		this.projno = projno;
	}

	public char getDirection() {
		return this.direction;
	}

	public void setDirection(char direction) {
		this.direction = direction;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getCurcode() {
		return this.curcode;
	}

	public void setCurcode(String curcode) {
		this.curcode = curcode;
	}

	public BigDecimal getForeignamount() {
		return this.foreignamount;
	}

	public void setForeignamount(BigDecimal foreignamount) {
		this.foreignamount = foreignamount;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public String getBillno() {
		return this.billno;
	}

	public void setBillno(String billno) {
		this.billno = billno;
	}

	public String getPayreceivno() {
		return this.payreceivno;
	}

	public void setPayreceivno(String payreceivno) {
		this.payreceivno = payreceivno;
	}

	public Double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Double quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getBankacct() {
		return this.bankacct;
	}

	public void setBankacct(String bankacct) {
		this.bankacct = bankacct;
	}

	public String getTrntype() {
		return this.trntype;
	}

	public void setTrntype(String trntype) {
		this.trntype = trntype;
	}

	public String getCatcode() {
		return this.catcode;
	}

	public void setCatcode(String catcode) {
		this.catcode = catcode;
	}

	public String getAcctype() {
		return this.acctype;
	}

	public void setAcctype(String acctype) {
		this.acctype = acctype;
	}

	public String getErykey() {
		return this.erykey;
	}

	public void setErykey(String erykey) {
		this.erykey = erykey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtunpostlistId))
			return false;
		TmpAtunpostlistId castOther = (TmpAtunpostlistId) other;

		return ((this.getSerialno() == castOther.getSerialno()) || (this
				.getSerialno() != null && castOther.getSerialno() != null && this
				.getSerialno().equals(castOther.getSerialno())))
				&& ((this.getListid() == castOther.getListid()) || (this
						.getListid() != null && castOther.getListid() != null && this
						.getListid().equals(castOther.getListid())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getAccount() == castOther.getAccount()) || (this
						.getAccount() != null && castOther.getAccount() != null && this
						.getAccount().equals(castOther.getAccount())))
				&& ((this.getDeptno() == castOther.getDeptno()) || (this
						.getDeptno() != null && castOther.getDeptno() != null && this
						.getDeptno().equals(castOther.getDeptno())))
				&& ((this.getProjno() == castOther.getProjno()) || (this
						.getProjno() != null && castOther.getProjno() != null && this
						.getProjno().equals(castOther.getProjno())))
				&& (this.getDirection() == castOther.getDirection())
				&& ((this.getAmount() == castOther.getAmount()) || (this
						.getAmount() != null && castOther.getAmount() != null && this
						.getAmount().equals(castOther.getAmount())))
				&& ((this.getCurcode() == castOther.getCurcode()) || (this
						.getCurcode() != null && castOther.getCurcode() != null && this
						.getCurcode().equals(castOther.getCurcode())))
				&& ((this.getForeignamount() == castOther.getForeignamount()) || (this
						.getForeignamount() != null
						&& castOther.getForeignamount() != null && this
						.getForeignamount()
						.equals(castOther.getForeignamount())))
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null
						&& castOther.getRate() != null && this.getRate()
						.equals(castOther.getRate())))
				&& ((this.getBillno() == castOther.getBillno()) || (this
						.getBillno() != null && castOther.getBillno() != null && this
						.getBillno().equals(castOther.getBillno())))
				&& ((this.getPayreceivno() == castOther.getPayreceivno()) || (this
						.getPayreceivno() != null
						&& castOther.getPayreceivno() != null && this
						.getPayreceivno().equals(castOther.getPayreceivno())))
				&& ((this.getQuantity() == castOther.getQuantity()) || (this
						.getQuantity() != null
						&& castOther.getQuantity() != null && this
						.getQuantity().equals(castOther.getQuantity())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())))
				&& ((this.getBankacct() == castOther.getBankacct()) || (this
						.getBankacct() != null
						&& castOther.getBankacct() != null && this
						.getBankacct().equals(castOther.getBankacct())))
				&& ((this.getTrntype() == castOther.getTrntype()) || (this
						.getTrntype() != null && castOther.getTrntype() != null && this
						.getTrntype().equals(castOther.getTrntype())))
				&& ((this.getCatcode() == castOther.getCatcode()) || (this
						.getCatcode() != null && castOther.getCatcode() != null && this
						.getCatcode().equals(castOther.getCatcode())))
				&& ((this.getAcctype() == castOther.getAcctype()) || (this
						.getAcctype() != null && castOther.getAcctype() != null && this
						.getAcctype().equals(castOther.getAcctype())))
				&& ((this.getErykey() == castOther.getErykey()) || (this
						.getErykey() != null && castOther.getErykey() != null && this
						.getErykey().equals(castOther.getErykey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSerialno() == null ? 0 : this.getSerialno().hashCode());
		result = 37 * result
				+ (getListid() == null ? 0 : this.getListid().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getAccount() == null ? 0 : this.getAccount().hashCode());
		result = 37 * result
				+ (getDeptno() == null ? 0 : this.getDeptno().hashCode());
		result = 37 * result
				+ (getProjno() == null ? 0 : this.getProjno().hashCode());
		result = 37 * result + this.getDirection();
		result = 37 * result
				+ (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result
				+ (getCurcode() == null ? 0 : this.getCurcode().hashCode());
		result = 37
				* result
				+ (getForeignamount() == null ? 0 : this.getForeignamount()
						.hashCode());
		result = 37 * result
				+ (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37 * result
				+ (getBillno() == null ? 0 : this.getBillno().hashCode());
		result = 37
				* result
				+ (getPayreceivno() == null ? 0 : this.getPayreceivno()
						.hashCode());
		result = 37 * result
				+ (getQuantity() == null ? 0 : this.getQuantity().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		result = 37 * result
				+ (getBankacct() == null ? 0 : this.getBankacct().hashCode());
		result = 37 * result
				+ (getTrntype() == null ? 0 : this.getTrntype().hashCode());
		result = 37 * result
				+ (getCatcode() == null ? 0 : this.getCatcode().hashCode());
		result = 37 * result
				+ (getAcctype() == null ? 0 : this.getAcctype().hashCode());
		result = 37 * result
				+ (getErykey() == null ? 0 : this.getErykey().hashCode());
		return result;
	}

}
