package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbassetbookvalue generated by hbm2java
 */
public class TmpAtbassetbookvalue implements java.io.Serializable {

	private TmpAtbassetbookvalueId id;

	public TmpAtbassetbookvalue() {
	}

	public TmpAtbassetbookvalue(TmpAtbassetbookvalueId id) {
		this.id = id;
	}

	public TmpAtbassetbookvalueId getId() {
		return this.id;
	}

	public void setId(TmpAtbassetbookvalueId id) {
		this.id = id;
	}

}
