package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbtoacc generated by hbm2java
 */
public class TmpAtbtoacc implements java.io.Serializable {

	private TmpAtbtoaccId id;

	public TmpAtbtoacc() {
	}

	public TmpAtbtoacc(TmpAtbtoaccId id) {
		this.id = id;
	}

	public TmpAtbtoaccId getId() {
		return this.id;
	}

	public void setId(TmpAtbtoaccId id) {
		this.id = id;
	}

}
