package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtbfairpriceId generated by hbm2java
 */
public class TmpAtbfairpriceId implements java.io.Serializable {

	private String transId;
	private String accType;
	private String bookcode;
	private String assetId;
	private String accDate;
	private String costsCenter;
	private String bookBranch;
	private String curCode;
	private BigDecimal amount;
	private BigDecimal price;

	public TmpAtbfairpriceId() {
	}

	public TmpAtbfairpriceId(String transId, String accType, String bookcode,
			String assetId, String accDate, String costsCenter) {
		this.transId = transId;
		this.accType = accType;
		this.bookcode = bookcode;
		this.assetId = assetId;
		this.accDate = accDate;
		this.costsCenter = costsCenter;
	}

	public TmpAtbfairpriceId(String transId, String accType, String bookcode,
			String assetId, String accDate, String costsCenter,
			String bookBranch, String curCode, BigDecimal amount,
			BigDecimal price) {
		this.transId = transId;
		this.accType = accType;
		this.bookcode = bookcode;
		this.assetId = assetId;
		this.accDate = accDate;
		this.costsCenter = costsCenter;
		this.bookBranch = bookBranch;
		this.curCode = curCode;
		this.amount = amount;
		this.price = price;
	}

	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	public String getBookcode() {
		return this.bookcode;
	}

	public void setBookcode(String bookcode) {
		this.bookcode = bookcode;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getAccDate() {
		return this.accDate;
	}

	public void setAccDate(String accDate) {
		this.accDate = accDate;
	}

	public String getCostsCenter() {
		return this.costsCenter;
	}

	public void setCostsCenter(String costsCenter) {
		this.costsCenter = costsCenter;
	}

	public String getBookBranch() {
		return this.bookBranch;
	}

	public void setBookBranch(String bookBranch) {
		this.bookBranch = bookBranch;
	}

	public String getCurCode() {
		return this.curCode;
	}

	public void setCurCode(String curCode) {
		this.curCode = curCode;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtbfairpriceId))
			return false;
		TmpAtbfairpriceId castOther = (TmpAtbfairpriceId) other;

		return ((this.getTransId() == castOther.getTransId()) || (this
				.getTransId() != null && castOther.getTransId() != null && this
				.getTransId().equals(castOther.getTransId())))
				&& ((this.getAccType() == castOther.getAccType()) || (this
						.getAccType() != null && castOther.getAccType() != null && this
						.getAccType().equals(castOther.getAccType())))
				&& ((this.getBookcode() == castOther.getBookcode()) || (this
						.getBookcode() != null
						&& castOther.getBookcode() != null && this
						.getBookcode().equals(castOther.getBookcode())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null && castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getAccDate() == castOther.getAccDate()) || (this
						.getAccDate() != null && castOther.getAccDate() != null && this
						.getAccDate().equals(castOther.getAccDate())))
				&& ((this.getCostsCenter() == castOther.getCostsCenter()) || (this
						.getCostsCenter() != null
						&& castOther.getCostsCenter() != null && this
						.getCostsCenter().equals(castOther.getCostsCenter())))
				&& ((this.getBookBranch() == castOther.getBookBranch()) || (this
						.getBookBranch() != null
						&& castOther.getBookBranch() != null && this
						.getBookBranch().equals(castOther.getBookBranch())))
				&& ((this.getCurCode() == castOther.getCurCode()) || (this
						.getCurCode() != null && castOther.getCurCode() != null && this
						.getCurCode().equals(castOther.getCurCode())))
				&& ((this.getAmount() == castOther.getAmount()) || (this
						.getAmount() != null && castOther.getAmount() != null && this
						.getAmount().equals(castOther.getAmount())))
				&& ((this.getPrice() == castOther.getPrice()) || (this
						.getPrice() != null && castOther.getPrice() != null && this
						.getPrice().equals(castOther.getPrice())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransId() == null ? 0 : this.getTransId().hashCode());
		result = 37 * result
				+ (getAccType() == null ? 0 : this.getAccType().hashCode());
		result = 37 * result
				+ (getBookcode() == null ? 0 : this.getBookcode().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result
				+ (getAccDate() == null ? 0 : this.getAccDate().hashCode());
		result = 37
				* result
				+ (getCostsCenter() == null ? 0 : this.getCostsCenter()
						.hashCode());
		result = 37
				* result
				+ (getBookBranch() == null ? 0 : this.getBookBranch()
						.hashCode());
		result = 37 * result
				+ (getCurCode() == null ? 0 : this.getCurCode().hashCode());
		result = 37 * result
				+ (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result
				+ (getPrice() == null ? 0 : this.getPrice().hashCode());
		return result;
	}

}
