package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAthisassetamorzsum generated by hbm2java
 */
public class TmpAthisassetamorzsum implements java.io.Serializable {

	private TmpAthisassetamorzsumId id;

	public TmpAthisassetamorzsum() {
	}

	public TmpAthisassetamorzsum(TmpAthisassetamorzsumId id) {
		this.id = id;
	}

	public TmpAthisassetamorzsumId getId() {
		return this.id;
	}

	public void setId(TmpAthisassetamorzsumId id) {
		this.id = id;
	}

}
