package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbinterestrate generated by hbm2java
 */
public class TmpAtbinterestrate implements java.io.Serializable {

	private TmpAtbinterestrateId id;

	public TmpAtbinterestrate() {
	}

	public TmpAtbinterestrate(TmpAtbinterestrateId id) {
		this.id = id;
	}

	public TmpAtbinterestrateId getId() {
		return this.id;
	}

	public void setId(TmpAtbinterestrateId id) {
		this.id = id;
	}

}
