package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtbfairpricesum generated by hbm2java
 */
public class TmpAtbfairpricesum implements java.io.Serializable {

	private TmpAtbfairpricesumId id;

	public TmpAtbfairpricesum() {
	}

	public TmpAtbfairpricesum(TmpAtbfairpricesumId id) {
		this.id = id;
	}

	public TmpAtbfairpricesumId getId() {
		return this.id;
	}

	public void setId(TmpAtbfairpricesumId id) {
		this.id = id;
	}

}
