package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpAtunpostentry generated by hbm2java
 */
public class TmpAtunpostentry implements java.io.Serializable {

	private TmpAtunpostentryId id;

	public TmpAtunpostentry() {
	}

	public TmpAtunpostentry(TmpAtunpostentryId id) {
		this.id = id;
	}

	public TmpAtunpostentryId getId() {
		return this.id;
	}

	public void setId(TmpAtunpostentryId id) {
		this.id = id;
	}

}
