package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtbassetbookvalueId generated by hbm2java
 */
public class TmpAtbassetbookvalueId implements java.io.Serializable {

	private String costsCenter;
	private String assetPort;
	private String accType;
	private String bookcode;
	private String transId;
	private String assetId;
	private String curCode;
	private String bookBranch;
	private Character assetFlag;
	private BigDecimal assetCount;
	private BigDecimal assetPosition;
	private BigDecimal acosts;
	private BigDecimal costsfull;
	private BigDecimal costs;
	private BigDecimal interest;
	private BigDecimal ajstinterate;
	private BigDecimal impairment;
	private BigDecimal interestaccrual;
	private BigDecimal curraccrual;
	private String costDate;

	public TmpAtbassetbookvalueId() {
	}

	public TmpAtbassetbookvalueId(String costsCenter, String assetPort,
			String accType, String bookcode, String transId, String assetId,
			String curCode) {
		this.costsCenter = costsCenter;
		this.assetPort = assetPort;
		this.accType = accType;
		this.bookcode = bookcode;
		this.transId = transId;
		this.assetId = assetId;
		this.curCode = curCode;
	}

	public TmpAtbassetbookvalueId(String costsCenter, String assetPort,
			String accType, String bookcode, String transId, String assetId,
			String curCode, String bookBranch, Character assetFlag,
			BigDecimal assetCount, BigDecimal assetPosition, BigDecimal acosts,
			BigDecimal costsfull, BigDecimal costs, BigDecimal interest,
			BigDecimal ajstinterate, BigDecimal impairment,
			BigDecimal interestaccrual, BigDecimal curraccrual, String costDate) {
		this.costsCenter = costsCenter;
		this.assetPort = assetPort;
		this.accType = accType;
		this.bookcode = bookcode;
		this.transId = transId;
		this.assetId = assetId;
		this.curCode = curCode;
		this.bookBranch = bookBranch;
		this.assetFlag = assetFlag;
		this.assetCount = assetCount;
		this.assetPosition = assetPosition;
		this.acosts = acosts;
		this.costsfull = costsfull;
		this.costs = costs;
		this.interest = interest;
		this.ajstinterate = ajstinterate;
		this.impairment = impairment;
		this.interestaccrual = interestaccrual;
		this.curraccrual = curraccrual;
		this.costDate = costDate;
	}

	public String getCostsCenter() {
		return this.costsCenter;
	}

	public void setCostsCenter(String costsCenter) {
		this.costsCenter = costsCenter;
	}

	public String getAssetPort() {
		return this.assetPort;
	}

	public void setAssetPort(String assetPort) {
		this.assetPort = assetPort;
	}

	public String getAccType() {
		return this.accType;
	}

	public void setAccType(String accType) {
		this.accType = accType;
	}

	public String getBookcode() {
		return this.bookcode;
	}

	public void setBookcode(String bookcode) {
		this.bookcode = bookcode;
	}

	public String getTransId() {
		return this.transId;
	}

	public void setTransId(String transId) {
		this.transId = transId;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public String getCurCode() {
		return this.curCode;
	}

	public void setCurCode(String curCode) {
		this.curCode = curCode;
	}

	public String getBookBranch() {
		return this.bookBranch;
	}

	public void setBookBranch(String bookBranch) {
		this.bookBranch = bookBranch;
	}

	public Character getAssetFlag() {
		return this.assetFlag;
	}

	public void setAssetFlag(Character assetFlag) {
		this.assetFlag = assetFlag;
	}

	public BigDecimal getAssetCount() {
		return this.assetCount;
	}

	public void setAssetCount(BigDecimal assetCount) {
		this.assetCount = assetCount;
	}

	public BigDecimal getAssetPosition() {
		return this.assetPosition;
	}

	public void setAssetPosition(BigDecimal assetPosition) {
		this.assetPosition = assetPosition;
	}

	public BigDecimal getAcosts() {
		return this.acosts;
	}

	public void setAcosts(BigDecimal acosts) {
		this.acosts = acosts;
	}

	public BigDecimal getCostsfull() {
		return this.costsfull;
	}

	public void setCostsfull(BigDecimal costsfull) {
		this.costsfull = costsfull;
	}

	public BigDecimal getCosts() {
		return this.costs;
	}

	public void setCosts(BigDecimal costs) {
		this.costs = costs;
	}

	public BigDecimal getInterest() {
		return this.interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public BigDecimal getAjstinterate() {
		return this.ajstinterate;
	}

	public void setAjstinterate(BigDecimal ajstinterate) {
		this.ajstinterate = ajstinterate;
	}

	public BigDecimal getImpairment() {
		return this.impairment;
	}

	public void setImpairment(BigDecimal impairment) {
		this.impairment = impairment;
	}

	public BigDecimal getInterestaccrual() {
		return this.interestaccrual;
	}

	public void setInterestaccrual(BigDecimal interestaccrual) {
		this.interestaccrual = interestaccrual;
	}

	public BigDecimal getCurraccrual() {
		return this.curraccrual;
	}

	public void setCurraccrual(BigDecimal curraccrual) {
		this.curraccrual = curraccrual;
	}

	public String getCostDate() {
		return this.costDate;
	}

	public void setCostDate(String costDate) {
		this.costDate = costDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtbassetbookvalueId))
			return false;
		TmpAtbassetbookvalueId castOther = (TmpAtbassetbookvalueId) other;

		return ((this.getCostsCenter() == castOther.getCostsCenter()) || (this
				.getCostsCenter() != null && castOther.getCostsCenter() != null && this
				.getCostsCenter().equals(castOther.getCostsCenter())))
				&& ((this.getAssetPort() == castOther.getAssetPort()) || (this
						.getAssetPort() != null
						&& castOther.getAssetPort() != null && this
						.getAssetPort().equals(castOther.getAssetPort())))
				&& ((this.getAccType() == castOther.getAccType()) || (this
						.getAccType() != null && castOther.getAccType() != null && this
						.getAccType().equals(castOther.getAccType())))
				&& ((this.getBookcode() == castOther.getBookcode()) || (this
						.getBookcode() != null
						&& castOther.getBookcode() != null && this
						.getBookcode().equals(castOther.getBookcode())))
				&& ((this.getTransId() == castOther.getTransId()) || (this
						.getTransId() != null && castOther.getTransId() != null && this
						.getTransId().equals(castOther.getTransId())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null && castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getCurCode() == castOther.getCurCode()) || (this
						.getCurCode() != null && castOther.getCurCode() != null && this
						.getCurCode().equals(castOther.getCurCode())))
				&& ((this.getBookBranch() == castOther.getBookBranch()) || (this
						.getBookBranch() != null
						&& castOther.getBookBranch() != null && this
						.getBookBranch().equals(castOther.getBookBranch())))
				&& ((this.getAssetFlag() == castOther.getAssetFlag()) || (this
						.getAssetFlag() != null
						&& castOther.getAssetFlag() != null && this
						.getAssetFlag().equals(castOther.getAssetFlag())))
				&& ((this.getAssetCount() == castOther.getAssetCount()) || (this
						.getAssetCount() != null
						&& castOther.getAssetCount() != null && this
						.getAssetCount().equals(castOther.getAssetCount())))
				&& ((this.getAssetPosition() == castOther.getAssetPosition()) || (this
						.getAssetPosition() != null
						&& castOther.getAssetPosition() != null && this
						.getAssetPosition()
						.equals(castOther.getAssetPosition())))
				&& ((this.getAcosts() == castOther.getAcosts()) || (this
						.getAcosts() != null && castOther.getAcosts() != null && this
						.getAcosts().equals(castOther.getAcosts())))
				&& ((this.getCostsfull() == castOther.getCostsfull()) || (this
						.getCostsfull() != null
						&& castOther.getCostsfull() != null && this
						.getCostsfull().equals(castOther.getCostsfull())))
				&& ((this.getCosts() == castOther.getCosts()) || (this
						.getCosts() != null && castOther.getCosts() != null && this
						.getCosts().equals(castOther.getCosts())))
				&& ((this.getInterest() == castOther.getInterest()) || (this
						.getInterest() != null
						&& castOther.getInterest() != null && this
						.getInterest().equals(castOther.getInterest())))
				&& ((this.getAjstinterate() == castOther.getAjstinterate()) || (this
						.getAjstinterate() != null
						&& castOther.getAjstinterate() != null && this
						.getAjstinterate().equals(castOther.getAjstinterate())))
				&& ((this.getImpairment() == castOther.getImpairment()) || (this
						.getImpairment() != null
						&& castOther.getImpairment() != null && this
						.getImpairment().equals(castOther.getImpairment())))
				&& ((this.getInterestaccrual() == castOther
						.getInterestaccrual()) || (this.getInterestaccrual() != null
						&& castOther.getInterestaccrual() != null && this
						.getInterestaccrual().equals(
								castOther.getInterestaccrual())))
				&& ((this.getCurraccrual() == castOther.getCurraccrual()) || (this
						.getCurraccrual() != null
						&& castOther.getCurraccrual() != null && this
						.getCurraccrual().equals(castOther.getCurraccrual())))
				&& ((this.getCostDate() == castOther.getCostDate()) || (this
						.getCostDate() != null
						&& castOther.getCostDate() != null && this
						.getCostDate().equals(castOther.getCostDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCostsCenter() == null ? 0 : this.getCostsCenter()
						.hashCode());
		result = 37 * result
				+ (getAssetPort() == null ? 0 : this.getAssetPort().hashCode());
		result = 37 * result
				+ (getAccType() == null ? 0 : this.getAccType().hashCode());
		result = 37 * result
				+ (getBookcode() == null ? 0 : this.getBookcode().hashCode());
		result = 37 * result
				+ (getTransId() == null ? 0 : this.getTransId().hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result
				+ (getCurCode() == null ? 0 : this.getCurCode().hashCode());
		result = 37
				* result
				+ (getBookBranch() == null ? 0 : this.getBookBranch()
						.hashCode());
		result = 37 * result
				+ (getAssetFlag() == null ? 0 : this.getAssetFlag().hashCode());
		result = 37
				* result
				+ (getAssetCount() == null ? 0 : this.getAssetCount()
						.hashCode());
		result = 37
				* result
				+ (getAssetPosition() == null ? 0 : this.getAssetPosition()
						.hashCode());
		result = 37 * result
				+ (getAcosts() == null ? 0 : this.getAcosts().hashCode());
		result = 37 * result
				+ (getCostsfull() == null ? 0 : this.getCostsfull().hashCode());
		result = 37 * result
				+ (getCosts() == null ? 0 : this.getCosts().hashCode());
		result = 37 * result
				+ (getInterest() == null ? 0 : this.getInterest().hashCode());
		result = 37
				* result
				+ (getAjstinterate() == null ? 0 : this.getAjstinterate()
						.hashCode());
		result = 37
				* result
				+ (getImpairment() == null ? 0 : this.getImpairment()
						.hashCode());
		result = 37
				* result
				+ (getInterestaccrual() == null ? 0 : this.getInterestaccrual()
						.hashCode());
		result = 37
				* result
				+ (getCurraccrual() == null ? 0 : this.getCurraccrual()
						.hashCode());
		result = 37 * result
				+ (getCostDate() == null ? 0 : this.getCostDate().hashCode());
		return result;
	}

}
