package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpAtbinterestrateId generated by hbm2java
 */
public class TmpAtbinterestrateId implements java.io.Serializable {

	private String costsCenter;
	private String assetId;
	private BigDecimal legNo;
	private char rateType;
	private BigDecimal rate;
	private String curCode;
	private String beginDate;
	private String endDate;
	private String changeDate;
	private String basis;
	private String freq;
	private Character compdMethod;
	private String indexId;
	private char status;

	public TmpAtbinterestrateId() {
	}

	public TmpAtbinterestrateId(String costsCenter, String assetId,
			BigDecimal legNo, char rateType, String beginDate, String endDate,
			char status) {
		this.costsCenter = costsCenter;
		this.assetId = assetId;
		this.legNo = legNo;
		this.rateType = rateType;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.status = status;
	}

	public TmpAtbinterestrateId(String costsCenter, String assetId,
			BigDecimal legNo, char rateType, BigDecimal rate, String curCode,
			String beginDate, String endDate, String changeDate, String basis,
			String freq, Character compdMethod, String indexId, char status) {
		this.costsCenter = costsCenter;
		this.assetId = assetId;
		this.legNo = legNo;
		this.rateType = rateType;
		this.rate = rate;
		this.curCode = curCode;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.changeDate = changeDate;
		this.basis = basis;
		this.freq = freq;
		this.compdMethod = compdMethod;
		this.indexId = indexId;
		this.status = status;
	}

	public String getCostsCenter() {
		return this.costsCenter;
	}

	public void setCostsCenter(String costsCenter) {
		this.costsCenter = costsCenter;
	}

	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public BigDecimal getLegNo() {
		return this.legNo;
	}

	public void setLegNo(BigDecimal legNo) {
		this.legNo = legNo;
	}

	public char getRateType() {
		return this.rateType;
	}

	public void setRateType(char rateType) {
		this.rateType = rateType;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public String getCurCode() {
		return this.curCode;
	}

	public void setCurCode(String curCode) {
		this.curCode = curCode;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getChangeDate() {
		return this.changeDate;
	}

	public void setChangeDate(String changeDate) {
		this.changeDate = changeDate;
	}

	public String getBasis() {
		return this.basis;
	}

	public void setBasis(String basis) {
		this.basis = basis;
	}

	public String getFreq() {
		return this.freq;
	}

	public void setFreq(String freq) {
		this.freq = freq;
	}

	public Character getCompdMethod() {
		return this.compdMethod;
	}

	public void setCompdMethod(Character compdMethod) {
		this.compdMethod = compdMethod;
	}

	public String getIndexId() {
		return this.indexId;
	}

	public void setIndexId(String indexId) {
		this.indexId = indexId;
	}

	public char getStatus() {
		return this.status;
	}

	public void setStatus(char status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpAtbinterestrateId))
			return false;
		TmpAtbinterestrateId castOther = (TmpAtbinterestrateId) other;

		return ((this.getCostsCenter() == castOther.getCostsCenter()) || (this
				.getCostsCenter() != null && castOther.getCostsCenter() != null && this
				.getCostsCenter().equals(castOther.getCostsCenter())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this
						.getAssetId() != null && castOther.getAssetId() != null && this
						.getAssetId().equals(castOther.getAssetId())))
				&& ((this.getLegNo() == castOther.getLegNo()) || (this
						.getLegNo() != null && castOther.getLegNo() != null && this
						.getLegNo().equals(castOther.getLegNo())))
				&& (this.getRateType() == castOther.getRateType())
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null
						&& castOther.getRate() != null && this.getRate()
						.equals(castOther.getRate())))
				&& ((this.getCurCode() == castOther.getCurCode()) || (this
						.getCurCode() != null && castOther.getCurCode() != null && this
						.getCurCode().equals(castOther.getCurCode())))
				&& ((this.getBeginDate() == castOther.getBeginDate()) || (this
						.getBeginDate() != null
						&& castOther.getBeginDate() != null && this
						.getBeginDate().equals(castOther.getBeginDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this
						.getEndDate() != null && castOther.getEndDate() != null && this
						.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getChangeDate() == castOther.getChangeDate()) || (this
						.getChangeDate() != null
						&& castOther.getChangeDate() != null && this
						.getChangeDate().equals(castOther.getChangeDate())))
				&& ((this.getBasis() == castOther.getBasis()) || (this
						.getBasis() != null && castOther.getBasis() != null && this
						.getBasis().equals(castOther.getBasis())))
				&& ((this.getFreq() == castOther.getFreq()) || (this.getFreq() != null
						&& castOther.getFreq() != null && this.getFreq()
						.equals(castOther.getFreq())))
				&& ((this.getCompdMethod() == castOther.getCompdMethod()) || (this
						.getCompdMethod() != null
						&& castOther.getCompdMethod() != null && this
						.getCompdMethod().equals(castOther.getCompdMethod())))
				&& ((this.getIndexId() == castOther.getIndexId()) || (this
						.getIndexId() != null && castOther.getIndexId() != null && this
						.getIndexId().equals(castOther.getIndexId())))
				&& (this.getStatus() == castOther.getStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCostsCenter() == null ? 0 : this.getCostsCenter()
						.hashCode());
		result = 37 * result
				+ (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		result = 37 * result
				+ (getLegNo() == null ? 0 : this.getLegNo().hashCode());
		result = 37 * result + this.getRateType();
		result = 37 * result
				+ (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37 * result
				+ (getCurCode() == null ? 0 : this.getCurCode().hashCode());
		result = 37 * result
				+ (getBeginDate() == null ? 0 : this.getBeginDate().hashCode());
		result = 37 * result
				+ (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37
				* result
				+ (getChangeDate() == null ? 0 : this.getChangeDate()
						.hashCode());
		result = 37 * result
				+ (getBasis() == null ? 0 : this.getBasis().hashCode());
		result = 37 * result
				+ (getFreq() == null ? 0 : this.getFreq().hashCode());
		result = 37
				* result
				+ (getCompdMethod() == null ? 0 : this.getCompdMethod()
						.hashCode());
		result = 37 * result
				+ (getIndexId() == null ? 0 : this.getIndexId().hashCode());
		result = 37 * result + this.getStatus();
		return result;
	}

}
