package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbcreditdetail generated by hbm2java
 */
public class TmpTbcreditdetail implements java.io.Serializable {

	private TmpTbcreditdetailId id;

	public TmpTbcreditdetail() {
	}

	public TmpTbcreditdetail(TmpTbcreditdetailId id) {
		this.id = id;
	}

	public TmpTbcreditdetailId getId() {
		return this.id;
	}

	public void setId(TmpTbcreditdetailId id) {
		this.id = id;
	}

}
