package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbassetplan generated by hbm2java
 */
public class TmpTbassetplan implements java.io.Serializable {

	private TmpTbassetplanId id;

	public TmpTbassetplan() {
	}

	public TmpTbassetplan(TmpTbassetplanId id) {
		this.id = id;
	}

	public TmpTbassetplanId getId() {
		return this.id;
	}

	public void setId(TmpTbassetplanId id) {
		this.id = id;
	}

}
