package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbassetunitstock generated by hbm2java
 */
public class TmpTbassetunitstock implements java.io.Serializable {

	private TmpTbassetunitstockId id;

	public TmpTbassetunitstock() {
	}

	public TmpTbassetunitstock(TmpTbassetunitstockId id) {
		this.id = id;
	}

	public TmpTbassetunitstockId getId() {
		return this.id;
	}

	public void setId(TmpTbassetunitstockId id) {
		this.id = id;
	}

}
