package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbpendsettleId generated by hbm2java
 */
public class TmpTbpendsettleId implements java.io.Serializable {

	private BigDecimal transDate;
	private String pendSerialNo;
	private String flowInstanceId;
	private BigDecimal settleDate;
	private String originalNo;
	private String businClass;
	private String settleStatus;
	private String stockSettleStatus;
	private String cashSettleStatus;
	private String oriBusinClass;
	private String dailyInstructionNo;
	private String combiNo;
	private String investType;
	private String interCode;
	private String marketNo;
	private String entrustDirection;
	private BigDecimal settleSpeed;
	private String settleType;
	private String firstMaturity;

	public TmpTbpendsettleId() {
	}

	public TmpTbpendsettleId(BigDecimal transDate, String pendSerialNo,
			String flowInstanceId, BigDecimal settleDate, String originalNo,
			String businClass, String settleStatus, String stockSettleStatus,
			String cashSettleStatus, String oriBusinClass,
			String dailyInstructionNo, String combiNo, String investType,
			String interCode, String marketNo, String entrustDirection,
			BigDecimal settleSpeed, String settleType, String firstMaturity) {
		this.transDate = transDate;
		this.pendSerialNo = pendSerialNo;
		this.flowInstanceId = flowInstanceId;
		this.settleDate = settleDate;
		this.originalNo = originalNo;
		this.businClass = businClass;
		this.settleStatus = settleStatus;
		this.stockSettleStatus = stockSettleStatus;
		this.cashSettleStatus = cashSettleStatus;
		this.oriBusinClass = oriBusinClass;
		this.dailyInstructionNo = dailyInstructionNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.marketNo = marketNo;
		this.entrustDirection = entrustDirection;
		this.settleSpeed = settleSpeed;
		this.settleType = settleType;
		this.firstMaturity = firstMaturity;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getPendSerialNo() {
		return this.pendSerialNo;
	}

	public void setPendSerialNo(String pendSerialNo) {
		this.pendSerialNo = pendSerialNo;
	}

	public String getFlowInstanceId() {
		return this.flowInstanceId;
	}

	public void setFlowInstanceId(String flowInstanceId) {
		this.flowInstanceId = flowInstanceId;
	}

	public BigDecimal getSettleDate() {
		return this.settleDate;
	}

	public void setSettleDate(BigDecimal settleDate) {
		this.settleDate = settleDate;
	}

	public String getOriginalNo() {
		return this.originalNo;
	}

	public void setOriginalNo(String originalNo) {
		this.originalNo = originalNo;
	}

	public String getBusinClass() {
		return this.businClass;
	}

	public void setBusinClass(String businClass) {
		this.businClass = businClass;
	}

	public String getSettleStatus() {
		return this.settleStatus;
	}

	public void setSettleStatus(String settleStatus) {
		this.settleStatus = settleStatus;
	}

	public String getStockSettleStatus() {
		return this.stockSettleStatus;
	}

	public void setStockSettleStatus(String stockSettleStatus) {
		this.stockSettleStatus = stockSettleStatus;
	}

	public String getCashSettleStatus() {
		return this.cashSettleStatus;
	}

	public void setCashSettleStatus(String cashSettleStatus) {
		this.cashSettleStatus = cashSettleStatus;
	}

	public String getOriBusinClass() {
		return this.oriBusinClass;
	}

	public void setOriBusinClass(String oriBusinClass) {
		this.oriBusinClass = oriBusinClass;
	}

	public String getDailyInstructionNo() {
		return this.dailyInstructionNo;
	}

	public void setDailyInstructionNo(String dailyInstructionNo) {
		this.dailyInstructionNo = dailyInstructionNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public String getMarketNo() {
		return this.marketNo;
	}

	public void setMarketNo(String marketNo) {
		this.marketNo = marketNo;
	}

	public String getEntrustDirection() {
		return this.entrustDirection;
	}

	public void setEntrustDirection(String entrustDirection) {
		this.entrustDirection = entrustDirection;
	}

	public BigDecimal getSettleSpeed() {
		return this.settleSpeed;
	}

	public void setSettleSpeed(BigDecimal settleSpeed) {
		this.settleSpeed = settleSpeed;
	}

	public String getSettleType() {
		return this.settleType;
	}

	public void setSettleType(String settleType) {
		this.settleType = settleType;
	}

	public String getFirstMaturity() {
		return this.firstMaturity;
	}

	public void setFirstMaturity(String firstMaturity) {
		this.firstMaturity = firstMaturity;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbpendsettleId))
			return false;
		TmpTbpendsettleId castOther = (TmpTbpendsettleId) other;

		return ((this.getTransDate() == castOther.getTransDate()) || (this
				.getTransDate() != null && castOther.getTransDate() != null && this
				.getTransDate().equals(castOther.getTransDate())))
				&& ((this.getPendSerialNo() == castOther.getPendSerialNo()) || (this
						.getPendSerialNo() != null
						&& castOther.getPendSerialNo() != null && this
						.getPendSerialNo().equals(castOther.getPendSerialNo())))
				&& ((this.getFlowInstanceId() == castOther.getFlowInstanceId()) || (this
						.getFlowInstanceId() != null
						&& castOther.getFlowInstanceId() != null && this
						.getFlowInstanceId().equals(
								castOther.getFlowInstanceId())))
				&& ((this.getSettleDate() == castOther.getSettleDate()) || (this
						.getSettleDate() != null
						&& castOther.getSettleDate() != null && this
						.getSettleDate().equals(castOther.getSettleDate())))
				&& ((this.getOriginalNo() == castOther.getOriginalNo()) || (this
						.getOriginalNo() != null
						&& castOther.getOriginalNo() != null && this
						.getOriginalNo().equals(castOther.getOriginalNo())))
				&& ((this.getBusinClass() == castOther.getBusinClass()) || (this
						.getBusinClass() != null
						&& castOther.getBusinClass() != null && this
						.getBusinClass().equals(castOther.getBusinClass())))
				&& ((this.getSettleStatus() == castOther.getSettleStatus()) || (this
						.getSettleStatus() != null
						&& castOther.getSettleStatus() != null && this
						.getSettleStatus().equals(castOther.getSettleStatus())))
				&& ((this.getStockSettleStatus() == castOther
						.getStockSettleStatus()) || (this
						.getStockSettleStatus() != null
						&& castOther.getStockSettleStatus() != null && this
						.getStockSettleStatus().equals(
								castOther.getStockSettleStatus())))
				&& ((this.getCashSettleStatus() == castOther
						.getCashSettleStatus()) || (this.getCashSettleStatus() != null
						&& castOther.getCashSettleStatus() != null && this
						.getCashSettleStatus().equals(
								castOther.getCashSettleStatus())))
				&& ((this.getOriBusinClass() == castOther.getOriBusinClass()) || (this
						.getOriBusinClass() != null
						&& castOther.getOriBusinClass() != null && this
						.getOriBusinClass()
						.equals(castOther.getOriBusinClass())))
				&& ((this.getDailyInstructionNo() == castOther
						.getDailyInstructionNo()) || (this
						.getDailyInstructionNo() != null
						&& castOther.getDailyInstructionNo() != null && this
						.getDailyInstructionNo().equals(
								castOther.getDailyInstructionNo())))
				&& ((this.getCombiNo() == castOther.getCombiNo()) || (this
						.getCombiNo() != null && castOther.getCombiNo() != null && this
						.getCombiNo().equals(castOther.getCombiNo())))
				&& ((this.getInvestType() == castOther.getInvestType()) || (this
						.getInvestType() != null
						&& castOther.getInvestType() != null && this
						.getInvestType().equals(castOther.getInvestType())))
				&& ((this.getInterCode() == castOther.getInterCode()) || (this
						.getInterCode() != null
						&& castOther.getInterCode() != null && this
						.getInterCode().equals(castOther.getInterCode())))
				&& ((this.getMarketNo() == castOther.getMarketNo()) || (this
						.getMarketNo() != null
						&& castOther.getMarketNo() != null && this
						.getMarketNo().equals(castOther.getMarketNo())))
				&& ((this.getEntrustDirection() == castOther
						.getEntrustDirection()) || (this.getEntrustDirection() != null
						&& castOther.getEntrustDirection() != null && this
						.getEntrustDirection().equals(
								castOther.getEntrustDirection())))
				&& ((this.getSettleSpeed() == castOther.getSettleSpeed()) || (this
						.getSettleSpeed() != null
						&& castOther.getSettleSpeed() != null && this
						.getSettleSpeed().equals(castOther.getSettleSpeed())))
				&& ((this.getSettleType() == castOther.getSettleType()) || (this
						.getSettleType() != null
						&& castOther.getSettleType() != null && this
						.getSettleType().equals(castOther.getSettleType())))
				&& ((this.getFirstMaturity() == castOther.getFirstMaturity()) || (this
						.getFirstMaturity() != null
						&& castOther.getFirstMaturity() != null && this
						.getFirstMaturity()
						.equals(castOther.getFirstMaturity())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		result = 37
				* result
				+ (getPendSerialNo() == null ? 0 : this.getPendSerialNo()
						.hashCode());
		result = 37
				* result
				+ (getFlowInstanceId() == null ? 0 : this.getFlowInstanceId()
						.hashCode());
		result = 37
				* result
				+ (getSettleDate() == null ? 0 : this.getSettleDate()
						.hashCode());
		result = 37
				* result
				+ (getOriginalNo() == null ? 0 : this.getOriginalNo()
						.hashCode());
		result = 37
				* result
				+ (getBusinClass() == null ? 0 : this.getBusinClass()
						.hashCode());
		result = 37
				* result
				+ (getSettleStatus() == null ? 0 : this.getSettleStatus()
						.hashCode());
		result = 37
				* result
				+ (getStockSettleStatus() == null ? 0 : this
						.getStockSettleStatus().hashCode());
		result = 37
				* result
				+ (getCashSettleStatus() == null ? 0 : this
						.getCashSettleStatus().hashCode());
		result = 37
				* result
				+ (getOriBusinClass() == null ? 0 : this.getOriBusinClass()
						.hashCode());
		result = 37
				* result
				+ (getDailyInstructionNo() == null ? 0 : this
						.getDailyInstructionNo().hashCode());
		result = 37 * result
				+ (getCombiNo() == null ? 0 : this.getCombiNo().hashCode());
		result = 37
				* result
				+ (getInvestType() == null ? 0 : this.getInvestType()
						.hashCode());
		result = 37 * result
				+ (getInterCode() == null ? 0 : this.getInterCode().hashCode());
		result = 37 * result
				+ (getMarketNo() == null ? 0 : this.getMarketNo().hashCode());
		result = 37
				* result
				+ (getEntrustDirection() == null ? 0 : this
						.getEntrustDirection().hashCode());
		result = 37
				* result
				+ (getSettleSpeed() == null ? 0 : this.getSettleSpeed()
						.hashCode());
		result = 37
				* result
				+ (getSettleType() == null ? 0 : this.getSettleType()
						.hashCode());
		result = 37
				* result
				+ (getFirstMaturity() == null ? 0 : this.getFirstMaturity()
						.hashCode());
		return result;
	}

}
