package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbunitcfl generated by hbm2java
 */
public class TmpTbunitcfl implements java.io.Serializable {

	private TmpTbunitcflId id;

	public TmpTbunitcfl() {
	}

	public TmpTbunitcfl(TmpTbunitcflId id) {
		this.id = id;
	}

	public TmpTbunitcflId getId() {
		return this.id;
	}

	public void setId(TmpTbunitcflId id) {
		this.id = id;
	}

}
