package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbhisassetunitstockId generated by hbm2java
 */
public class TmpTbhisassetunitstockId implements java.io.Serializable {

	private BigDecimal transDate;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String investType;
	private String interCode;
	private BigDecimal beginAmount;
	private BigDecimal currentAmount;
	private BigDecimal frozenAmount;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public TmpTbhisassetunitstockId() {
	}

	public TmpTbhisassetunitstockId(BigDecimal transDate, String fundNo,
			String assetNo, String combiNo, String investType,
			String interCode, BigDecimal beginAmount, BigDecimal currentAmount,
			BigDecimal frozenAmount, BigDecimal lastDate, BigDecimal lastTime) {
		this.transDate = transDate;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.beginAmount = beginAmount;
		this.currentAmount = currentAmount;
		this.frozenAmount = frozenAmount;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public BigDecimal getBeginAmount() {
		return this.beginAmount;
	}

	public void setBeginAmount(BigDecimal beginAmount) {
		this.beginAmount = beginAmount;
	}

	public BigDecimal getCurrentAmount() {
		return this.currentAmount;
	}

	public void setCurrentAmount(BigDecimal currentAmount) {
		this.currentAmount = currentAmount;
	}

	public BigDecimal getFrozenAmount() {
		return this.frozenAmount;
	}

	public void setFrozenAmount(BigDecimal frozenAmount) {
		this.frozenAmount = frozenAmount;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbhisassetunitstockId))
			return false;
		TmpTbhisassetunitstockId castOther = (TmpTbhisassetunitstockId) other;

		return ((this.getTransDate() == castOther.getTransDate()) || (this
				.getTransDate() != null && castOther.getTransDate() != null && this
				.getTransDate().equals(castOther.getTransDate())))
				&& ((this.getFundNo() == castOther.getFundNo()) || (this
						.getFundNo() != null && castOther.getFundNo() != null && this
						.getFundNo().equals(castOther.getFundNo())))
				&& ((this.getAssetNo() == castOther.getAssetNo()) || (this
						.getAssetNo() != null && castOther.getAssetNo() != null && this
						.getAssetNo().equals(castOther.getAssetNo())))
				&& ((this.getCombiNo() == castOther.getCombiNo()) || (this
						.getCombiNo() != null && castOther.getCombiNo() != null && this
						.getCombiNo().equals(castOther.getCombiNo())))
				&& ((this.getInvestType() == castOther.getInvestType()) || (this
						.getInvestType() != null
						&& castOther.getInvestType() != null && this
						.getInvestType().equals(castOther.getInvestType())))
				&& ((this.getInterCode() == castOther.getInterCode()) || (this
						.getInterCode() != null
						&& castOther.getInterCode() != null && this
						.getInterCode().equals(castOther.getInterCode())))
				&& ((this.getBeginAmount() == castOther.getBeginAmount()) || (this
						.getBeginAmount() != null
						&& castOther.getBeginAmount() != null && this
						.getBeginAmount().equals(castOther.getBeginAmount())))
				&& ((this.getCurrentAmount() == castOther.getCurrentAmount()) || (this
						.getCurrentAmount() != null
						&& castOther.getCurrentAmount() != null && this
						.getCurrentAmount()
						.equals(castOther.getCurrentAmount())))
				&& ((this.getFrozenAmount() == castOther.getFrozenAmount()) || (this
						.getFrozenAmount() != null
						&& castOther.getFrozenAmount() != null && this
						.getFrozenAmount().equals(castOther.getFrozenAmount())))
				&& ((this.getLastDate() == castOther.getLastDate()) || (this
						.getLastDate() != null
						&& castOther.getLastDate() != null && this
						.getLastDate().equals(castOther.getLastDate())))
				&& ((this.getLastTime() == castOther.getLastTime()) || (this
						.getLastTime() != null
						&& castOther.getLastTime() != null && this
						.getLastTime().equals(castOther.getLastTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		result = 37 * result
				+ (getFundNo() == null ? 0 : this.getFundNo().hashCode());
		result = 37 * result
				+ (getAssetNo() == null ? 0 : this.getAssetNo().hashCode());
		result = 37 * result
				+ (getCombiNo() == null ? 0 : this.getCombiNo().hashCode());
		result = 37
				* result
				+ (getInvestType() == null ? 0 : this.getInvestType()
						.hashCode());
		result = 37 * result
				+ (getInterCode() == null ? 0 : this.getInterCode().hashCode());
		result = 37
				* result
				+ (getBeginAmount() == null ? 0 : this.getBeginAmount()
						.hashCode());
		result = 37
				* result
				+ (getCurrentAmount() == null ? 0 : this.getCurrentAmount()
						.hashCode());
		result = 37
				* result
				+ (getFrozenAmount() == null ? 0 : this.getFrozenAmount()
						.hashCode());
		result = 37 * result
				+ (getLastDate() == null ? 0 : this.getLastDate().hashCode());
		result = 37 * result
				+ (getLastTime() == null ? 0 : this.getLastTime().hashCode());
		return result;
	}

}
