package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbbankrealdeal generated by hbm2java
 */
public class TmpTbbankrealdeal implements java.io.Serializable {

	private TmpTbbankrealdealId id;

	public TmpTbbankrealdeal() {
	}

	public TmpTbbankrealdeal(TmpTbbankrealdealId id) {
		this.id = id;
	}

	public TmpTbbankrealdealId getId() {
		return this.id;
	}

	public void setId(TmpTbbankrealdealId id) {
		this.id = id;
	}

}
