package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbunitstock generated by hbm2java
 */
public class TmpTbunitstock implements java.io.Serializable {

	private TmpTbunitstockId id;

	public TmpTbunitstock() {
	}

	public TmpTbunitstock(TmpTbunitstockId id) {
		this.id = id;
	}

	public TmpTbunitstockId getId() {
		return this.id;
	}

	public void setId(TmpTbunitstockId id) {
		this.id = id;
	}

}
