package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbmmrealdeal generated by hbm2java
 */
public class TmpTbmmrealdeal implements java.io.Serializable {

	private TmpTbmmrealdealId id;

	public TmpTbmmrealdeal() {
	}

	public TmpTbmmrealdeal(TmpTbmmrealdealId id) {
		this.id = id;
	}

	public TmpTbmmrealdealId getId() {
		return this.id;
	}

	public void setId(TmpTbmmrealdealId id) {
		this.id = id;
	}

}
