package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbhisunitstock generated by hbm2java
 */
public class TmpTbhisunitstock implements java.io.Serializable {

	private TmpTbhisunitstockId id;

	public TmpTbhisunitstock() {
	}

	public TmpTbhisunitstock(TmpTbhisunitstockId id) {
		this.id = id;
	}

	public TmpTbhisunitstockId getId() {
		return this.id;
	}

	public void setId(TmpTbhisunitstockId id) {
		this.id = id;
	}

}
