package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbdealhgmortagageId generated by hbm2java
 */
public class TmpTbdealhgmortagageId implements java.io.Serializable {

	private BigDecimal transDate;
	private String dealSerialNo;
	private BigDecimal operationId;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String investType;
	private String interCode;
	private BigDecimal ratio;
	private BigDecimal mortagageAmount;
	private String offerSide;

	public TmpTbdealhgmortagageId() {
	}

	public TmpTbdealhgmortagageId(BigDecimal transDate, String dealSerialNo,
			BigDecimal operationId, String fundNo, String assetNo,
			String combiNo, String investType, String interCode,
			BigDecimal ratio, BigDecimal mortagageAmount, String offerSide) {
		this.transDate = transDate;
		this.dealSerialNo = dealSerialNo;
		this.operationId = operationId;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.ratio = ratio;
		this.mortagageAmount = mortagageAmount;
		this.offerSide = offerSide;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getDealSerialNo() {
		return this.dealSerialNo;
	}

	public void setDealSerialNo(String dealSerialNo) {
		this.dealSerialNo = dealSerialNo;
	}

	public BigDecimal getOperationId() {
		return this.operationId;
	}

	public void setOperationId(BigDecimal operationId) {
		this.operationId = operationId;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public BigDecimal getRatio() {
		return this.ratio;
	}

	public void setRatio(BigDecimal ratio) {
		this.ratio = ratio;
	}

	public BigDecimal getMortagageAmount() {
		return this.mortagageAmount;
	}

	public void setMortagageAmount(BigDecimal mortagageAmount) {
		this.mortagageAmount = mortagageAmount;
	}

	public String getOfferSide() {
		return this.offerSide;
	}

	public void setOfferSide(String offerSide) {
		this.offerSide = offerSide;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbdealhgmortagageId))
			return false;
		TmpTbdealhgmortagageId castOther = (TmpTbdealhgmortagageId) other;

		return ((this.getTransDate() == castOther.getTransDate()) || (this
				.getTransDate() != null && castOther.getTransDate() != null && this
				.getTransDate().equals(castOther.getTransDate())))
				&& ((this.getDealSerialNo() == castOther.getDealSerialNo()) || (this
						.getDealSerialNo() != null
						&& castOther.getDealSerialNo() != null && this
						.getDealSerialNo().equals(castOther.getDealSerialNo())))
				&& ((this.getOperationId() == castOther.getOperationId()) || (this
						.getOperationId() != null
						&& castOther.getOperationId() != null && this
						.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getFundNo() == castOther.getFundNo()) || (this
						.getFundNo() != null && castOther.getFundNo() != null && this
						.getFundNo().equals(castOther.getFundNo())))
				&& ((this.getAssetNo() == castOther.getAssetNo()) || (this
						.getAssetNo() != null && castOther.getAssetNo() != null && this
						.getAssetNo().equals(castOther.getAssetNo())))
				&& ((this.getCombiNo() == castOther.getCombiNo()) || (this
						.getCombiNo() != null && castOther.getCombiNo() != null && this
						.getCombiNo().equals(castOther.getCombiNo())))
				&& ((this.getInvestType() == castOther.getInvestType()) || (this
						.getInvestType() != null
						&& castOther.getInvestType() != null && this
						.getInvestType().equals(castOther.getInvestType())))
				&& ((this.getInterCode() == castOther.getInterCode()) || (this
						.getInterCode() != null
						&& castOther.getInterCode() != null && this
						.getInterCode().equals(castOther.getInterCode())))
				&& ((this.getRatio() == castOther.getRatio()) || (this
						.getRatio() != null && castOther.getRatio() != null && this
						.getRatio().equals(castOther.getRatio())))
				&& ((this.getMortagageAmount() == castOther
						.getMortagageAmount()) || (this.getMortagageAmount() != null
						&& castOther.getMortagageAmount() != null && this
						.getMortagageAmount().equals(
								castOther.getMortagageAmount())))
				&& ((this.getOfferSide() == castOther.getOfferSide()) || (this
						.getOfferSide() != null
						&& castOther.getOfferSide() != null && this
						.getOfferSide().equals(castOther.getOfferSide())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		result = 37
				* result
				+ (getDealSerialNo() == null ? 0 : this.getDealSerialNo()
						.hashCode());
		result = 37
				* result
				+ (getOperationId() == null ? 0 : this.getOperationId()
						.hashCode());
		result = 37 * result
				+ (getFundNo() == null ? 0 : this.getFundNo().hashCode());
		result = 37 * result
				+ (getAssetNo() == null ? 0 : this.getAssetNo().hashCode());
		result = 37 * result
				+ (getCombiNo() == null ? 0 : this.getCombiNo().hashCode());
		result = 37
				* result
				+ (getInvestType() == null ? 0 : this.getInvestType()
						.hashCode());
		result = 37 * result
				+ (getInterCode() == null ? 0 : this.getInterCode().hashCode());
		result = 37 * result
				+ (getRatio() == null ? 0 : this.getRatio().hashCode());
		result = 37
				* result
				+ (getMortagageAmount() == null ? 0 : this.getMortagageAmount()
						.hashCode());
		result = 37 * result
				+ (getOfferSide() == null ? 0 : this.getOfferSide().hashCode());
		return result;
	}

}
