package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbissueunitstockId generated by hbm2java
 */
public class TmpTbissueunitstockId implements java.io.Serializable {

	private BigDecimal transDate;
	private String fundNo;
	private String assetNo;
	private String combiNo;
	private String investType;
	private String interCode;
	private BigDecimal amount;
	private BigDecimal lastDate;
	private BigDecimal lastTime;

	public TmpTbissueunitstockId() {
	}

	public TmpTbissueunitstockId(BigDecimal transDate, String fundNo,
			String assetNo, String combiNo, String investType,
			String interCode, BigDecimal amount, BigDecimal lastDate,
			BigDecimal lastTime) {
		this.transDate = transDate;
		this.fundNo = fundNo;
		this.assetNo = assetNo;
		this.combiNo = combiNo;
		this.investType = investType;
		this.interCode = interCode;
		this.amount = amount;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
	}

	public BigDecimal getTransDate() {
		return this.transDate;
	}

	public void setTransDate(BigDecimal transDate) {
		this.transDate = transDate;
	}

	public String getFundNo() {
		return this.fundNo;
	}

	public void setFundNo(String fundNo) {
		this.fundNo = fundNo;
	}

	public String getAssetNo() {
		return this.assetNo;
	}

	public void setAssetNo(String assetNo) {
		this.assetNo = assetNo;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getInvestType() {
		return this.investType;
	}

	public void setInvestType(String investType) {
		this.investType = investType;
	}

	public String getInterCode() {
		return this.interCode;
	}

	public void setInterCode(String interCode) {
		this.interCode = interCode;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbissueunitstockId))
			return false;
		TmpTbissueunitstockId castOther = (TmpTbissueunitstockId) other;

		return ((this.getTransDate() == castOther.getTransDate()) || (this
				.getTransDate() != null && castOther.getTransDate() != null && this
				.getTransDate().equals(castOther.getTransDate())))
				&& ((this.getFundNo() == castOther.getFundNo()) || (this
						.getFundNo() != null && castOther.getFundNo() != null && this
						.getFundNo().equals(castOther.getFundNo())))
				&& ((this.getAssetNo() == castOther.getAssetNo()) || (this
						.getAssetNo() != null && castOther.getAssetNo() != null && this
						.getAssetNo().equals(castOther.getAssetNo())))
				&& ((this.getCombiNo() == castOther.getCombiNo()) || (this
						.getCombiNo() != null && castOther.getCombiNo() != null && this
						.getCombiNo().equals(castOther.getCombiNo())))
				&& ((this.getInvestType() == castOther.getInvestType()) || (this
						.getInvestType() != null
						&& castOther.getInvestType() != null && this
						.getInvestType().equals(castOther.getInvestType())))
				&& ((this.getInterCode() == castOther.getInterCode()) || (this
						.getInterCode() != null
						&& castOther.getInterCode() != null && this
						.getInterCode().equals(castOther.getInterCode())))
				&& ((this.getAmount() == castOther.getAmount()) || (this
						.getAmount() != null && castOther.getAmount() != null && this
						.getAmount().equals(castOther.getAmount())))
				&& ((this.getLastDate() == castOther.getLastDate()) || (this
						.getLastDate() != null
						&& castOther.getLastDate() != null && this
						.getLastDate().equals(castOther.getLastDate())))
				&& ((this.getLastTime() == castOther.getLastTime()) || (this
						.getLastTime() != null
						&& castOther.getLastTime() != null && this
						.getLastTime().equals(castOther.getLastTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransDate() == null ? 0 : this.getTransDate().hashCode());
		result = 37 * result
				+ (getFundNo() == null ? 0 : this.getFundNo().hashCode());
		result = 37 * result
				+ (getAssetNo() == null ? 0 : this.getAssetNo().hashCode());
		result = 37 * result
				+ (getCombiNo() == null ? 0 : this.getCombiNo().hashCode());
		result = 37
				* result
				+ (getInvestType() == null ? 0 : this.getInvestType()
						.hashCode());
		result = 37 * result
				+ (getInterCode() == null ? 0 : this.getInterCode().hashCode());
		result = 37 * result
				+ (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result
				+ (getLastDate() == null ? 0 : this.getLastDate().hashCode());
		result = 37 * result
				+ (getLastTime() == null ? 0 : this.getLastTime().hashCode());
		return result;
	}

}
