package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbmmrealdealId generated by hbm2java
 */
public class TmpTbmmrealdealId implements java.io.Serializable {

	private String dealSerialNo;
	private BigDecimal versionNo;
	private String dealNo;
	private String contractNo;
	private String contractName;
	private String subAccountNo;
	private String limitUnit;
	private BigDecimal limit;
	private String amtSource;
	private BigDecimal upperLimit;
	private String autoContinueFlag;
	private BigDecimal foundDate;
	private BigDecimal dealTime;
	private String withInterestFlag;
	private BigDecimal interestAmt;
	private BigDecimal settleAmt;
	private BigDecimal interest;
	private BigDecimal interestDate;
	private BigDecimal lastInterestEndDate;
	private String baseInterest;
	private String aheadAllow;
	private BigDecimal settleSpeed;
	private String firstSettleType;
	private String secondSettleType;
	private BigDecimal secondClearBalance;
	private BigDecimal rate;
	private BigDecimal hgDays;
	private BigDecimal realHgDays;
	private String tenderInfoId;
	private BigDecimal payDate;
	private BigDecimal matureInterest;
	private String repurchaseOrg;
	private String objectMethod;
	private String reserve;
	private String reserve2;
	private String reserve3;

	public TmpTbmmrealdealId() {
	}

	public TmpTbmmrealdealId(String dealSerialNo, BigDecimal versionNo,
			String dealNo, String contractNo, String contractName,
			String subAccountNo, String limitUnit, BigDecimal limit,
			String amtSource, BigDecimal upperLimit, String autoContinueFlag,
			BigDecimal foundDate, BigDecimal dealTime, String withInterestFlag,
			BigDecimal interestAmt, BigDecimal settleAmt, BigDecimal interest,
			BigDecimal interestDate, BigDecimal lastInterestEndDate,
			String baseInterest, String aheadAllow, BigDecimal settleSpeed,
			String firstSettleType, String secondSettleType,
			BigDecimal secondClearBalance, BigDecimal rate, BigDecimal hgDays,
			BigDecimal realHgDays, String tenderInfoId, BigDecimal payDate,
			BigDecimal matureInterest, String repurchaseOrg,
			String objectMethod, String reserve, String reserve2,
			String reserve3) {
		this.dealSerialNo = dealSerialNo;
		this.versionNo = versionNo;
		this.dealNo = dealNo;
		this.contractNo = contractNo;
		this.contractName = contractName;
		this.subAccountNo = subAccountNo;
		this.limitUnit = limitUnit;
		this.limit = limit;
		this.amtSource = amtSource;
		this.upperLimit = upperLimit;
		this.autoContinueFlag = autoContinueFlag;
		this.foundDate = foundDate;
		this.dealTime = dealTime;
		this.withInterestFlag = withInterestFlag;
		this.interestAmt = interestAmt;
		this.settleAmt = settleAmt;
		this.interest = interest;
		this.interestDate = interestDate;
		this.lastInterestEndDate = lastInterestEndDate;
		this.baseInterest = baseInterest;
		this.aheadAllow = aheadAllow;
		this.settleSpeed = settleSpeed;
		this.firstSettleType = firstSettleType;
		this.secondSettleType = secondSettleType;
		this.secondClearBalance = secondClearBalance;
		this.rate = rate;
		this.hgDays = hgDays;
		this.realHgDays = realHgDays;
		this.tenderInfoId = tenderInfoId;
		this.payDate = payDate;
		this.matureInterest = matureInterest;
		this.repurchaseOrg = repurchaseOrg;
		this.objectMethod = objectMethod;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
	}

	public String getDealSerialNo() {
		return this.dealSerialNo;
	}

	public void setDealSerialNo(String dealSerialNo) {
		this.dealSerialNo = dealSerialNo;
	}

	public BigDecimal getVersionNo() {
		return this.versionNo;
	}

	public void setVersionNo(BigDecimal versionNo) {
		this.versionNo = versionNo;
	}

	public String getDealNo() {
		return this.dealNo;
	}

	public void setDealNo(String dealNo) {
		this.dealNo = dealNo;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public String getContractName() {
		return this.contractName;
	}

	public void setContractName(String contractName) {
		this.contractName = contractName;
	}

	public String getSubAccountNo() {
		return this.subAccountNo;
	}

	public void setSubAccountNo(String subAccountNo) {
		this.subAccountNo = subAccountNo;
	}

	public String getLimitUnit() {
		return this.limitUnit;
	}

	public void setLimitUnit(String limitUnit) {
		this.limitUnit = limitUnit;
	}

	public BigDecimal getLimit() {
		return this.limit;
	}

	public void setLimit(BigDecimal limit) {
		this.limit = limit;
	}

	public String getAmtSource() {
		return this.amtSource;
	}

	public void setAmtSource(String amtSource) {
		this.amtSource = amtSource;
	}

	public BigDecimal getUpperLimit() {
		return this.upperLimit;
	}

	public void setUpperLimit(BigDecimal upperLimit) {
		this.upperLimit = upperLimit;
	}

	public String getAutoContinueFlag() {
		return this.autoContinueFlag;
	}

	public void setAutoContinueFlag(String autoContinueFlag) {
		this.autoContinueFlag = autoContinueFlag;
	}

	public BigDecimal getFoundDate() {
		return this.foundDate;
	}

	public void setFoundDate(BigDecimal foundDate) {
		this.foundDate = foundDate;
	}

	public BigDecimal getDealTime() {
		return this.dealTime;
	}

	public void setDealTime(BigDecimal dealTime) {
		this.dealTime = dealTime;
	}

	public String getWithInterestFlag() {
		return this.withInterestFlag;
	}

	public void setWithInterestFlag(String withInterestFlag) {
		this.withInterestFlag = withInterestFlag;
	}

	public BigDecimal getInterestAmt() {
		return this.interestAmt;
	}

	public void setInterestAmt(BigDecimal interestAmt) {
		this.interestAmt = interestAmt;
	}

	public BigDecimal getSettleAmt() {
		return this.settleAmt;
	}

	public void setSettleAmt(BigDecimal settleAmt) {
		this.settleAmt = settleAmt;
	}

	public BigDecimal getInterest() {
		return this.interest;
	}

	public void setInterest(BigDecimal interest) {
		this.interest = interest;
	}

	public BigDecimal getInterestDate() {
		return this.interestDate;
	}

	public void setInterestDate(BigDecimal interestDate) {
		this.interestDate = interestDate;
	}

	public BigDecimal getLastInterestEndDate() {
		return this.lastInterestEndDate;
	}

	public void setLastInterestEndDate(BigDecimal lastInterestEndDate) {
		this.lastInterestEndDate = lastInterestEndDate;
	}

	public String getBaseInterest() {
		return this.baseInterest;
	}

	public void setBaseInterest(String baseInterest) {
		this.baseInterest = baseInterest;
	}

	public String getAheadAllow() {
		return this.aheadAllow;
	}

	public void setAheadAllow(String aheadAllow) {
		this.aheadAllow = aheadAllow;
	}

	public BigDecimal getSettleSpeed() {
		return this.settleSpeed;
	}

	public void setSettleSpeed(BigDecimal settleSpeed) {
		this.settleSpeed = settleSpeed;
	}

	public String getFirstSettleType() {
		return this.firstSettleType;
	}

	public void setFirstSettleType(String firstSettleType) {
		this.firstSettleType = firstSettleType;
	}

	public String getSecondSettleType() {
		return this.secondSettleType;
	}

	public void setSecondSettleType(String secondSettleType) {
		this.secondSettleType = secondSettleType;
	}

	public BigDecimal getSecondClearBalance() {
		return this.secondClearBalance;
	}

	public void setSecondClearBalance(BigDecimal secondClearBalance) {
		this.secondClearBalance = secondClearBalance;
	}

	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	public BigDecimal getHgDays() {
		return this.hgDays;
	}

	public void setHgDays(BigDecimal hgDays) {
		this.hgDays = hgDays;
	}

	public BigDecimal getRealHgDays() {
		return this.realHgDays;
	}

	public void setRealHgDays(BigDecimal realHgDays) {
		this.realHgDays = realHgDays;
	}

	public String getTenderInfoId() {
		return this.tenderInfoId;
	}

	public void setTenderInfoId(String tenderInfoId) {
		this.tenderInfoId = tenderInfoId;
	}

	public BigDecimal getPayDate() {
		return this.payDate;
	}

	public void setPayDate(BigDecimal payDate) {
		this.payDate = payDate;
	}

	public BigDecimal getMatureInterest() {
		return this.matureInterest;
	}

	public void setMatureInterest(BigDecimal matureInterest) {
		this.matureInterest = matureInterest;
	}

	public String getRepurchaseOrg() {
		return this.repurchaseOrg;
	}

	public void setRepurchaseOrg(String repurchaseOrg) {
		this.repurchaseOrg = repurchaseOrg;
	}

	public String getObjectMethod() {
		return this.objectMethod;
	}

	public void setObjectMethod(String objectMethod) {
		this.objectMethod = objectMethod;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbmmrealdealId))
			return false;
		TmpTbmmrealdealId castOther = (TmpTbmmrealdealId) other;

		return ((this.getDealSerialNo() == castOther.getDealSerialNo()) || (this
				.getDealSerialNo() != null
				&& castOther.getDealSerialNo() != null && this
				.getDealSerialNo().equals(castOther.getDealSerialNo())))
				&& ((this.getVersionNo() == castOther.getVersionNo()) || (this
						.getVersionNo() != null
						&& castOther.getVersionNo() != null && this
						.getVersionNo().equals(castOther.getVersionNo())))
				&& ((this.getDealNo() == castOther.getDealNo()) || (this
						.getDealNo() != null && castOther.getDealNo() != null && this
						.getDealNo().equals(castOther.getDealNo())))
				&& ((this.getContractNo() == castOther.getContractNo()) || (this
						.getContractNo() != null
						&& castOther.getContractNo() != null && this
						.getContractNo().equals(castOther.getContractNo())))
				&& ((this.getContractName() == castOther.getContractName()) || (this
						.getContractName() != null
						&& castOther.getContractName() != null && this
						.getContractName().equals(castOther.getContractName())))
				&& ((this.getSubAccountNo() == castOther.getSubAccountNo()) || (this
						.getSubAccountNo() != null
						&& castOther.getSubAccountNo() != null && this
						.getSubAccountNo().equals(castOther.getSubAccountNo())))
				&& ((this.getLimitUnit() == castOther.getLimitUnit()) || (this
						.getLimitUnit() != null
						&& castOther.getLimitUnit() != null && this
						.getLimitUnit().equals(castOther.getLimitUnit())))
				&& ((this.getLimit() == castOther.getLimit()) || (this
						.getLimit() != null && castOther.getLimit() != null && this
						.getLimit().equals(castOther.getLimit())))
				&& ((this.getAmtSource() == castOther.getAmtSource()) || (this
						.getAmtSource() != null
						&& castOther.getAmtSource() != null && this
						.getAmtSource().equals(castOther.getAmtSource())))
				&& ((this.getUpperLimit() == castOther.getUpperLimit()) || (this
						.getUpperLimit() != null
						&& castOther.getUpperLimit() != null && this
						.getUpperLimit().equals(castOther.getUpperLimit())))
				&& ((this.getAutoContinueFlag() == castOther
						.getAutoContinueFlag()) || (this.getAutoContinueFlag() != null
						&& castOther.getAutoContinueFlag() != null && this
						.getAutoContinueFlag().equals(
								castOther.getAutoContinueFlag())))
				&& ((this.getFoundDate() == castOther.getFoundDate()) || (this
						.getFoundDate() != null
						&& castOther.getFoundDate() != null && this
						.getFoundDate().equals(castOther.getFoundDate())))
				&& ((this.getDealTime() == castOther.getDealTime()) || (this
						.getDealTime() != null
						&& castOther.getDealTime() != null && this
						.getDealTime().equals(castOther.getDealTime())))
				&& ((this.getWithInterestFlag() == castOther
						.getWithInterestFlag()) || (this.getWithInterestFlag() != null
						&& castOther.getWithInterestFlag() != null && this
						.getWithInterestFlag().equals(
								castOther.getWithInterestFlag())))
				&& ((this.getInterestAmt() == castOther.getInterestAmt()) || (this
						.getInterestAmt() != null
						&& castOther.getInterestAmt() != null && this
						.getInterestAmt().equals(castOther.getInterestAmt())))
				&& ((this.getSettleAmt() == castOther.getSettleAmt()) || (this
						.getSettleAmt() != null
						&& castOther.getSettleAmt() != null && this
						.getSettleAmt().equals(castOther.getSettleAmt())))
				&& ((this.getInterest() == castOther.getInterest()) || (this
						.getInterest() != null
						&& castOther.getInterest() != null && this
						.getInterest().equals(castOther.getInterest())))
				&& ((this.getInterestDate() == castOther.getInterestDate()) || (this
						.getInterestDate() != null
						&& castOther.getInterestDate() != null && this
						.getInterestDate().equals(castOther.getInterestDate())))
				&& ((this.getLastInterestEndDate() == castOther
						.getLastInterestEndDate()) || (this
						.getLastInterestEndDate() != null
						&& castOther.getLastInterestEndDate() != null && this
						.getLastInterestEndDate().equals(
								castOther.getLastInterestEndDate())))
				&& ((this.getBaseInterest() == castOther.getBaseInterest()) || (this
						.getBaseInterest() != null
						&& castOther.getBaseInterest() != null && this
						.getBaseInterest().equals(castOther.getBaseInterest())))
				&& ((this.getAheadAllow() == castOther.getAheadAllow()) || (this
						.getAheadAllow() != null
						&& castOther.getAheadAllow() != null && this
						.getAheadAllow().equals(castOther.getAheadAllow())))
				&& ((this.getSettleSpeed() == castOther.getSettleSpeed()) || (this
						.getSettleSpeed() != null
						&& castOther.getSettleSpeed() != null && this
						.getSettleSpeed().equals(castOther.getSettleSpeed())))
				&& ((this.getFirstSettleType() == castOther
						.getFirstSettleType()) || (this.getFirstSettleType() != null
						&& castOther.getFirstSettleType() != null && this
						.getFirstSettleType().equals(
								castOther.getFirstSettleType())))
				&& ((this.getSecondSettleType() == castOther
						.getSecondSettleType()) || (this.getSecondSettleType() != null
						&& castOther.getSecondSettleType() != null && this
						.getSecondSettleType().equals(
								castOther.getSecondSettleType())))
				&& ((this.getSecondClearBalance() == castOther
						.getSecondClearBalance()) || (this
						.getSecondClearBalance() != null
						&& castOther.getSecondClearBalance() != null && this
						.getSecondClearBalance().equals(
								castOther.getSecondClearBalance())))
				&& ((this.getRate() == castOther.getRate()) || (this.getRate() != null
						&& castOther.getRate() != null && this.getRate()
						.equals(castOther.getRate())))
				&& ((this.getHgDays() == castOther.getHgDays()) || (this
						.getHgDays() != null && castOther.getHgDays() != null && this
						.getHgDays().equals(castOther.getHgDays())))
				&& ((this.getRealHgDays() == castOther.getRealHgDays()) || (this
						.getRealHgDays() != null
						&& castOther.getRealHgDays() != null && this
						.getRealHgDays().equals(castOther.getRealHgDays())))
				&& ((this.getTenderInfoId() == castOther.getTenderInfoId()) || (this
						.getTenderInfoId() != null
						&& castOther.getTenderInfoId() != null && this
						.getTenderInfoId().equals(castOther.getTenderInfoId())))
				&& ((this.getPayDate() == castOther.getPayDate()) || (this
						.getPayDate() != null && castOther.getPayDate() != null && this
						.getPayDate().equals(castOther.getPayDate())))
				&& ((this.getMatureInterest() == castOther.getMatureInterest()) || (this
						.getMatureInterest() != null
						&& castOther.getMatureInterest() != null && this
						.getMatureInterest().equals(
								castOther.getMatureInterest())))
				&& ((this.getRepurchaseOrg() == castOther.getRepurchaseOrg()) || (this
						.getRepurchaseOrg() != null
						&& castOther.getRepurchaseOrg() != null && this
						.getRepurchaseOrg()
						.equals(castOther.getRepurchaseOrg())))
				&& ((this.getObjectMethod() == castOther.getObjectMethod()) || (this
						.getObjectMethod() != null
						&& castOther.getObjectMethod() != null && this
						.getObjectMethod().equals(castOther.getObjectMethod())))
				&& ((this.getReserve() == castOther.getReserve()) || (this
						.getReserve() != null && castOther.getReserve() != null && this
						.getReserve().equals(castOther.getReserve())))
				&& ((this.getReserve2() == castOther.getReserve2()) || (this
						.getReserve2() != null
						&& castOther.getReserve2() != null && this
						.getReserve2().equals(castOther.getReserve2())))
				&& ((this.getReserve3() == castOther.getReserve3()) || (this
						.getReserve3() != null
						&& castOther.getReserve3() != null && this
						.getReserve3().equals(castOther.getReserve3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDealSerialNo() == null ? 0 : this.getDealSerialNo()
						.hashCode());
		result = 37 * result
				+ (getVersionNo() == null ? 0 : this.getVersionNo().hashCode());
		result = 37 * result
				+ (getDealNo() == null ? 0 : this.getDealNo().hashCode());
		result = 37
				* result
				+ (getContractNo() == null ? 0 : this.getContractNo()
						.hashCode());
		result = 37
				* result
				+ (getContractName() == null ? 0 : this.getContractName()
						.hashCode());
		result = 37
				* result
				+ (getSubAccountNo() == null ? 0 : this.getSubAccountNo()
						.hashCode());
		result = 37 * result
				+ (getLimitUnit() == null ? 0 : this.getLimitUnit().hashCode());
		result = 37 * result
				+ (getLimit() == null ? 0 : this.getLimit().hashCode());
		result = 37 * result
				+ (getAmtSource() == null ? 0 : this.getAmtSource().hashCode());
		result = 37
				* result
				+ (getUpperLimit() == null ? 0 : this.getUpperLimit()
						.hashCode());
		result = 37
				* result
				+ (getAutoContinueFlag() == null ? 0 : this
						.getAutoContinueFlag().hashCode());
		result = 37 * result
				+ (getFoundDate() == null ? 0 : this.getFoundDate().hashCode());
		result = 37 * result
				+ (getDealTime() == null ? 0 : this.getDealTime().hashCode());
		result = 37
				* result
				+ (getWithInterestFlag() == null ? 0 : this
						.getWithInterestFlag().hashCode());
		result = 37
				* result
				+ (getInterestAmt() == null ? 0 : this.getInterestAmt()
						.hashCode());
		result = 37 * result
				+ (getSettleAmt() == null ? 0 : this.getSettleAmt().hashCode());
		result = 37 * result
				+ (getInterest() == null ? 0 : this.getInterest().hashCode());
		result = 37
				* result
				+ (getInterestDate() == null ? 0 : this.getInterestDate()
						.hashCode());
		result = 37
				* result
				+ (getLastInterestEndDate() == null ? 0 : this
						.getLastInterestEndDate().hashCode());
		result = 37
				* result
				+ (getBaseInterest() == null ? 0 : this.getBaseInterest()
						.hashCode());
		result = 37
				* result
				+ (getAheadAllow() == null ? 0 : this.getAheadAllow()
						.hashCode());
		result = 37
				* result
				+ (getSettleSpeed() == null ? 0 : this.getSettleSpeed()
						.hashCode());
		result = 37
				* result
				+ (getFirstSettleType() == null ? 0 : this.getFirstSettleType()
						.hashCode());
		result = 37
				* result
				+ (getSecondSettleType() == null ? 0 : this
						.getSecondSettleType().hashCode());
		result = 37
				* result
				+ (getSecondClearBalance() == null ? 0 : this
						.getSecondClearBalance().hashCode());
		result = 37 * result
				+ (getRate() == null ? 0 : this.getRate().hashCode());
		result = 37 * result
				+ (getHgDays() == null ? 0 : this.getHgDays().hashCode());
		result = 37
				* result
				+ (getRealHgDays() == null ? 0 : this.getRealHgDays()
						.hashCode());
		result = 37
				* result
				+ (getTenderInfoId() == null ? 0 : this.getTenderInfoId()
						.hashCode());
		result = 37 * result
				+ (getPayDate() == null ? 0 : this.getPayDate().hashCode());
		result = 37
				* result
				+ (getMatureInterest() == null ? 0 : this.getMatureInterest()
						.hashCode());
		result = 37
				* result
				+ (getRepurchaseOrg() == null ? 0 : this.getRepurchaseOrg()
						.hashCode());
		result = 37
				* result
				+ (getObjectMethod() == null ? 0 : this.getObjectMethod()
						.hashCode());
		result = 37 * result
				+ (getReserve() == null ? 0 : this.getReserve().hashCode());
		result = 37 * result
				+ (getReserve2() == null ? 0 : this.getReserve2().hashCode());
		result = 37 * result
				+ (getReserve3() == null ? 0 : this.getReserve3().hashCode());
		return result;
	}

}
