package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbbillpropertyId generated by hbm2java
 */
public class TmpTbbillpropertyId implements java.io.Serializable {

	private String billNo;
	private BigDecimal outDate;
	private BigDecimal endDate;
	private BigDecimal faceAmt;
	private String billClass;
	private String billType;
	private String accepterNo;
	private String accepterName;
	private String accepterBankNo;
	private String accepterBankno;
	private String accepterOpenName;
	private String accepterOpenNo;
	private String accepterOpenAname;
	private String accepterType;
	private String drawerNo;
	private String drawerAccount;
	private String drawerOpenName;
	private String drawerOpenNo;
	private String drawerOpenAname;
	private String receiverNo;
	private String receiverAccount;
	private String receiverOpenName;
	private String receiverOpenNo;
	private String receiverOpenAname;
	private String allowFlag;
	private String payBasis;
	private String combiNo;
	private String status;
	private String dealingStatus;
	private String isOrgin;
	private String buySubCode;
	private BigDecimal lastDate;
	private BigDecimal lastTime;
	private BigDecimal endDateUnadj;

	public TmpTbbillpropertyId() {
	}

	public TmpTbbillpropertyId(String billNo, BigDecimal outDate,
			BigDecimal endDate, BigDecimal faceAmt, String billClass,
			String billType, String accepterNo, String accepterName,
			String accepterBankNo, String accepterBankno,
			String accepterOpenName, String accepterOpenNo,
			String accepterOpenAname, String accepterType, String drawerNo,
			String drawerAccount, String drawerOpenName, String drawerOpenNo,
			String drawerOpenAname, String receiverNo, String receiverAccount,
			String receiverOpenName, String receiverOpenNo,
			String receiverOpenAname, String allowFlag, String payBasis,
			String combiNo, String status, String dealingStatus,
			String isOrgin, String buySubCode, BigDecimal lastDate,
			BigDecimal lastTime, BigDecimal endDateUnadj) {
		this.billNo = billNo;
		this.outDate = outDate;
		this.endDate = endDate;
		this.faceAmt = faceAmt;
		this.billClass = billClass;
		this.billType = billType;
		this.accepterNo = accepterNo;
		this.accepterName = accepterName;
		this.accepterBankNo = accepterBankNo;
		this.accepterBankno = accepterBankno;
		this.accepterOpenName = accepterOpenName;
		this.accepterOpenNo = accepterOpenNo;
		this.accepterOpenAname = accepterOpenAname;
		this.accepterType = accepterType;
		this.drawerNo = drawerNo;
		this.drawerAccount = drawerAccount;
		this.drawerOpenName = drawerOpenName;
		this.drawerOpenNo = drawerOpenNo;
		this.drawerOpenAname = drawerOpenAname;
		this.receiverNo = receiverNo;
		this.receiverAccount = receiverAccount;
		this.receiverOpenName = receiverOpenName;
		this.receiverOpenNo = receiverOpenNo;
		this.receiverOpenAname = receiverOpenAname;
		this.allowFlag = allowFlag;
		this.payBasis = payBasis;
		this.combiNo = combiNo;
		this.status = status;
		this.dealingStatus = dealingStatus;
		this.isOrgin = isOrgin;
		this.buySubCode = buySubCode;
		this.lastDate = lastDate;
		this.lastTime = lastTime;
		this.endDateUnadj = endDateUnadj;
	}

	public String getBillNo() {
		return this.billNo;
	}

	public void setBillNo(String billNo) {
		this.billNo = billNo;
	}

	public BigDecimal getOutDate() {
		return this.outDate;
	}

	public void setOutDate(BigDecimal outDate) {
		this.outDate = outDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public BigDecimal getFaceAmt() {
		return this.faceAmt;
	}

	public void setFaceAmt(BigDecimal faceAmt) {
		this.faceAmt = faceAmt;
	}

	public String getBillClass() {
		return this.billClass;
	}

	public void setBillClass(String billClass) {
		this.billClass = billClass;
	}

	public String getBillType() {
		return this.billType;
	}

	public void setBillType(String billType) {
		this.billType = billType;
	}

	public String getAccepterNo() {
		return this.accepterNo;
	}

	public void setAccepterNo(String accepterNo) {
		this.accepterNo = accepterNo;
	}

	public String getAccepterName() {
		return this.accepterName;
	}

	public void setAccepterName(String accepterName) {
		this.accepterName = accepterName;
	}

	public String getAccepterBankNo() {
		return this.accepterBankNo;
	}

	public void setAccepterBankNo(String accepterBankNo) {
		this.accepterBankNo = accepterBankNo;
	}

	public String getAccepterBankno() {
		return this.accepterBankno;
	}

	public void setAccepterBankno(String accepterBankno) {
		this.accepterBankno = accepterBankno;
	}

	public String getAccepterOpenName() {
		return this.accepterOpenName;
	}

	public void setAccepterOpenName(String accepterOpenName) {
		this.accepterOpenName = accepterOpenName;
	}

	public String getAccepterOpenNo() {
		return this.accepterOpenNo;
	}

	public void setAccepterOpenNo(String accepterOpenNo) {
		this.accepterOpenNo = accepterOpenNo;
	}

	public String getAccepterOpenAname() {
		return this.accepterOpenAname;
	}

	public void setAccepterOpenAname(String accepterOpenAname) {
		this.accepterOpenAname = accepterOpenAname;
	}

	public String getAccepterType() {
		return this.accepterType;
	}

	public void setAccepterType(String accepterType) {
		this.accepterType = accepterType;
	}

	public String getDrawerNo() {
		return this.drawerNo;
	}

	public void setDrawerNo(String drawerNo) {
		this.drawerNo = drawerNo;
	}

	public String getDrawerAccount() {
		return this.drawerAccount;
	}

	public void setDrawerAccount(String drawerAccount) {
		this.drawerAccount = drawerAccount;
	}

	public String getDrawerOpenName() {
		return this.drawerOpenName;
	}

	public void setDrawerOpenName(String drawerOpenName) {
		this.drawerOpenName = drawerOpenName;
	}

	public String getDrawerOpenNo() {
		return this.drawerOpenNo;
	}

	public void setDrawerOpenNo(String drawerOpenNo) {
		this.drawerOpenNo = drawerOpenNo;
	}

	public String getDrawerOpenAname() {
		return this.drawerOpenAname;
	}

	public void setDrawerOpenAname(String drawerOpenAname) {
		this.drawerOpenAname = drawerOpenAname;
	}

	public String getReceiverNo() {
		return this.receiverNo;
	}

	public void setReceiverNo(String receiverNo) {
		this.receiverNo = receiverNo;
	}

	public String getReceiverAccount() {
		return this.receiverAccount;
	}

	public void setReceiverAccount(String receiverAccount) {
		this.receiverAccount = receiverAccount;
	}

	public String getReceiverOpenName() {
		return this.receiverOpenName;
	}

	public void setReceiverOpenName(String receiverOpenName) {
		this.receiverOpenName = receiverOpenName;
	}

	public String getReceiverOpenNo() {
		return this.receiverOpenNo;
	}

	public void setReceiverOpenNo(String receiverOpenNo) {
		this.receiverOpenNo = receiverOpenNo;
	}

	public String getReceiverOpenAname() {
		return this.receiverOpenAname;
	}

	public void setReceiverOpenAname(String receiverOpenAname) {
		this.receiverOpenAname = receiverOpenAname;
	}

	public String getAllowFlag() {
		return this.allowFlag;
	}

	public void setAllowFlag(String allowFlag) {
		this.allowFlag = allowFlag;
	}

	public String getPayBasis() {
		return this.payBasis;
	}

	public void setPayBasis(String payBasis) {
		this.payBasis = payBasis;
	}

	public String getCombiNo() {
		return this.combiNo;
	}

	public void setCombiNo(String combiNo) {
		this.combiNo = combiNo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDealingStatus() {
		return this.dealingStatus;
	}

	public void setDealingStatus(String dealingStatus) {
		this.dealingStatus = dealingStatus;
	}

	public String getIsOrgin() {
		return this.isOrgin;
	}

	public void setIsOrgin(String isOrgin) {
		this.isOrgin = isOrgin;
	}

	public String getBuySubCode() {
		return this.buySubCode;
	}

	public void setBuySubCode(String buySubCode) {
		this.buySubCode = buySubCode;
	}

	public BigDecimal getLastDate() {
		return this.lastDate;
	}

	public void setLastDate(BigDecimal lastDate) {
		this.lastDate = lastDate;
	}

	public BigDecimal getLastTime() {
		return this.lastTime;
	}

	public void setLastTime(BigDecimal lastTime) {
		this.lastTime = lastTime;
	}

	public BigDecimal getEndDateUnadj() {
		return this.endDateUnadj;
	}

	public void setEndDateUnadj(BigDecimal endDateUnadj) {
		this.endDateUnadj = endDateUnadj;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbbillpropertyId))
			return false;
		TmpTbbillpropertyId castOther = (TmpTbbillpropertyId) other;

		return ((this.getBillNo() == castOther.getBillNo()) || (this
				.getBillNo() != null && castOther.getBillNo() != null && this
				.getBillNo().equals(castOther.getBillNo())))
				&& ((this.getOutDate() == castOther.getOutDate()) || (this
						.getOutDate() != null && castOther.getOutDate() != null && this
						.getOutDate().equals(castOther.getOutDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this
						.getEndDate() != null && castOther.getEndDate() != null && this
						.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getFaceAmt() == castOther.getFaceAmt()) || (this
						.getFaceAmt() != null && castOther.getFaceAmt() != null && this
						.getFaceAmt().equals(castOther.getFaceAmt())))
				&& ((this.getBillClass() == castOther.getBillClass()) || (this
						.getBillClass() != null
						&& castOther.getBillClass() != null && this
						.getBillClass().equals(castOther.getBillClass())))
				&& ((this.getBillType() == castOther.getBillType()) || (this
						.getBillType() != null
						&& castOther.getBillType() != null && this
						.getBillType().equals(castOther.getBillType())))
				&& ((this.getAccepterNo() == castOther.getAccepterNo()) || (this
						.getAccepterNo() != null
						&& castOther.getAccepterNo() != null && this
						.getAccepterNo().equals(castOther.getAccepterNo())))
				&& ((this.getAccepterName() == castOther.getAccepterName()) || (this
						.getAccepterName() != null
						&& castOther.getAccepterName() != null && this
						.getAccepterName().equals(castOther.getAccepterName())))
				&& ((this.getAccepterBankNo() == castOther.getAccepterBankNo()) || (this
						.getAccepterBankNo() != null
						&& castOther.getAccepterBankNo() != null && this
						.getAccepterBankNo().equals(
								castOther.getAccepterBankNo())))
				&& ((this.getAccepterBankno() == castOther.getAccepterBankno()) || (this
						.getAccepterBankno() != null
						&& castOther.getAccepterBankno() != null && this
						.getAccepterBankno().equals(
								castOther.getAccepterBankno())))
				&& ((this.getAccepterOpenName() == castOther
						.getAccepterOpenName()) || (this.getAccepterOpenName() != null
						&& castOther.getAccepterOpenName() != null && this
						.getAccepterOpenName().equals(
								castOther.getAccepterOpenName())))
				&& ((this.getAccepterOpenNo() == castOther.getAccepterOpenNo()) || (this
						.getAccepterOpenNo() != null
						&& castOther.getAccepterOpenNo() != null && this
						.getAccepterOpenNo().equals(
								castOther.getAccepterOpenNo())))
				&& ((this.getAccepterOpenAname() == castOther
						.getAccepterOpenAname()) || (this
						.getAccepterOpenAname() != null
						&& castOther.getAccepterOpenAname() != null && this
						.getAccepterOpenAname().equals(
								castOther.getAccepterOpenAname())))
				&& ((this.getAccepterType() == castOther.getAccepterType()) || (this
						.getAccepterType() != null
						&& castOther.getAccepterType() != null && this
						.getAccepterType().equals(castOther.getAccepterType())))
				&& ((this.getDrawerNo() == castOther.getDrawerNo()) || (this
						.getDrawerNo() != null
						&& castOther.getDrawerNo() != null && this
						.getDrawerNo().equals(castOther.getDrawerNo())))
				&& ((this.getDrawerAccount() == castOther.getDrawerAccount()) || (this
						.getDrawerAccount() != null
						&& castOther.getDrawerAccount() != null && this
						.getDrawerAccount()
						.equals(castOther.getDrawerAccount())))
				&& ((this.getDrawerOpenName() == castOther.getDrawerOpenName()) || (this
						.getDrawerOpenName() != null
						&& castOther.getDrawerOpenName() != null && this
						.getDrawerOpenName().equals(
								castOther.getDrawerOpenName())))
				&& ((this.getDrawerOpenNo() == castOther.getDrawerOpenNo()) || (this
						.getDrawerOpenNo() != null
						&& castOther.getDrawerOpenNo() != null && this
						.getDrawerOpenNo().equals(castOther.getDrawerOpenNo())))
				&& ((this.getDrawerOpenAname() == castOther
						.getDrawerOpenAname()) || (this.getDrawerOpenAname() != null
						&& castOther.getDrawerOpenAname() != null && this
						.getDrawerOpenAname().equals(
								castOther.getDrawerOpenAname())))
				&& ((this.getReceiverNo() == castOther.getReceiverNo()) || (this
						.getReceiverNo() != null
						&& castOther.getReceiverNo() != null && this
						.getReceiverNo().equals(castOther.getReceiverNo())))
				&& ((this.getReceiverAccount() == castOther
						.getReceiverAccount()) || (this.getReceiverAccount() != null
						&& castOther.getReceiverAccount() != null && this
						.getReceiverAccount().equals(
								castOther.getReceiverAccount())))
				&& ((this.getReceiverOpenName() == castOther
						.getReceiverOpenName()) || (this.getReceiverOpenName() != null
						&& castOther.getReceiverOpenName() != null && this
						.getReceiverOpenName().equals(
								castOther.getReceiverOpenName())))
				&& ((this.getReceiverOpenNo() == castOther.getReceiverOpenNo()) || (this
						.getReceiverOpenNo() != null
						&& castOther.getReceiverOpenNo() != null && this
						.getReceiverOpenNo().equals(
								castOther.getReceiverOpenNo())))
				&& ((this.getReceiverOpenAname() == castOther
						.getReceiverOpenAname()) || (this
						.getReceiverOpenAname() != null
						&& castOther.getReceiverOpenAname() != null && this
						.getReceiverOpenAname().equals(
								castOther.getReceiverOpenAname())))
				&& ((this.getAllowFlag() == castOther.getAllowFlag()) || (this
						.getAllowFlag() != null
						&& castOther.getAllowFlag() != null && this
						.getAllowFlag().equals(castOther.getAllowFlag())))
				&& ((this.getPayBasis() == castOther.getPayBasis()) || (this
						.getPayBasis() != null
						&& castOther.getPayBasis() != null && this
						.getPayBasis().equals(castOther.getPayBasis())))
				&& ((this.getCombiNo() == castOther.getCombiNo()) || (this
						.getCombiNo() != null && castOther.getCombiNo() != null && this
						.getCombiNo().equals(castOther.getCombiNo())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getDealingStatus() == castOther.getDealingStatus()) || (this
						.getDealingStatus() != null
						&& castOther.getDealingStatus() != null && this
						.getDealingStatus()
						.equals(castOther.getDealingStatus())))
				&& ((this.getIsOrgin() == castOther.getIsOrgin()) || (this
						.getIsOrgin() != null && castOther.getIsOrgin() != null && this
						.getIsOrgin().equals(castOther.getIsOrgin())))
				&& ((this.getBuySubCode() == castOther.getBuySubCode()) || (this
						.getBuySubCode() != null
						&& castOther.getBuySubCode() != null && this
						.getBuySubCode().equals(castOther.getBuySubCode())))
				&& ((this.getLastDate() == castOther.getLastDate()) || (this
						.getLastDate() != null
						&& castOther.getLastDate() != null && this
						.getLastDate().equals(castOther.getLastDate())))
				&& ((this.getLastTime() == castOther.getLastTime()) || (this
						.getLastTime() != null
						&& castOther.getLastTime() != null && this
						.getLastTime().equals(castOther.getLastTime())))
				&& ((this.getEndDateUnadj() == castOther.getEndDateUnadj()) || (this
						.getEndDateUnadj() != null
						&& castOther.getEndDateUnadj() != null && this
						.getEndDateUnadj().equals(castOther.getEndDateUnadj())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getBillNo() == null ? 0 : this.getBillNo().hashCode());
		result = 37 * result
				+ (getOutDate() == null ? 0 : this.getOutDate().hashCode());
		result = 37 * result
				+ (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37 * result
				+ (getFaceAmt() == null ? 0 : this.getFaceAmt().hashCode());
		result = 37 * result
				+ (getBillClass() == null ? 0 : this.getBillClass().hashCode());
		result = 37 * result
				+ (getBillType() == null ? 0 : this.getBillType().hashCode());
		result = 37
				* result
				+ (getAccepterNo() == null ? 0 : this.getAccepterNo()
						.hashCode());
		result = 37
				* result
				+ (getAccepterName() == null ? 0 : this.getAccepterName()
						.hashCode());
		result = 37
				* result
				+ (getAccepterBankNo() == null ? 0 : this.getAccepterBankNo()
						.hashCode());
		result = 37
				* result
				+ (getAccepterBankno() == null ? 0 : this.getAccepterBankno()
						.hashCode());
		result = 37
				* result
				+ (getAccepterOpenName() == null ? 0 : this
						.getAccepterOpenName().hashCode());
		result = 37
				* result
				+ (getAccepterOpenNo() == null ? 0 : this.getAccepterOpenNo()
						.hashCode());
		result = 37
				* result
				+ (getAccepterOpenAname() == null ? 0 : this
						.getAccepterOpenAname().hashCode());
		result = 37
				* result
				+ (getAccepterType() == null ? 0 : this.getAccepterType()
						.hashCode());
		result = 37 * result
				+ (getDrawerNo() == null ? 0 : this.getDrawerNo().hashCode());
		result = 37
				* result
				+ (getDrawerAccount() == null ? 0 : this.getDrawerAccount()
						.hashCode());
		result = 37
				* result
				+ (getDrawerOpenName() == null ? 0 : this.getDrawerOpenName()
						.hashCode());
		result = 37
				* result
				+ (getDrawerOpenNo() == null ? 0 : this.getDrawerOpenNo()
						.hashCode());
		result = 37
				* result
				+ (getDrawerOpenAname() == null ? 0 : this.getDrawerOpenAname()
						.hashCode());
		result = 37
				* result
				+ (getReceiverNo() == null ? 0 : this.getReceiverNo()
						.hashCode());
		result = 37
				* result
				+ (getReceiverAccount() == null ? 0 : this.getReceiverAccount()
						.hashCode());
		result = 37
				* result
				+ (getReceiverOpenName() == null ? 0 : this
						.getReceiverOpenName().hashCode());
		result = 37
				* result
				+ (getReceiverOpenNo() == null ? 0 : this.getReceiverOpenNo()
						.hashCode());
		result = 37
				* result
				+ (getReceiverOpenAname() == null ? 0 : this
						.getReceiverOpenAname().hashCode());
		result = 37 * result
				+ (getAllowFlag() == null ? 0 : this.getAllowFlag().hashCode());
		result = 37 * result
				+ (getPayBasis() == null ? 0 : this.getPayBasis().hashCode());
		result = 37 * result
				+ (getCombiNo() == null ? 0 : this.getCombiNo().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37
				* result
				+ (getDealingStatus() == null ? 0 : this.getDealingStatus()
						.hashCode());
		result = 37 * result
				+ (getIsOrgin() == null ? 0 : this.getIsOrgin().hashCode());
		result = 37
				* result
				+ (getBuySubCode() == null ? 0 : this.getBuySubCode()
						.hashCode());
		result = 37 * result
				+ (getLastDate() == null ? 0 : this.getLastDate().hashCode());
		result = 37 * result
				+ (getLastTime() == null ? 0 : this.getLastTime().hashCode());
		result = 37
				* result
				+ (getEndDateUnadj() == null ? 0 : this.getEndDateUnadj()
						.hashCode());
		return result;
	}

}
