package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbinstext generated by hbm2java
 */
public class TmpTbinstext implements java.io.Serializable {

	private TmpTbinstextId id;

	public TmpTbinstext() {
	}

	public TmpTbinstext(TmpTbinstextId id) {
		this.id = id;
	}

	public TmpTbinstextId getId() {
		return this.id;
	}

	public void setId(TmpTbinstextId id) {
		this.id = id;
	}

}
