package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbinstrdeal generated by hbm2java
 */
public class TmpTbinstrdeal implements java.io.Serializable {

	private TmpTbinstrdealId id;

	public TmpTbinstrdeal() {
	}

	public TmpTbinstrdeal(TmpTbinstrdealId id) {
		this.id = id;
	}

	public TmpTbinstrdealId getId() {
		return this.id;
	}

	public void setId(TmpTbinstrdealId id) {
		this.id = id;
	}

}
