package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpTbobservId generated by hbm2java
 */
public class TmpTbobservId implements java.io.Serializable {

	private String isBond;
	private String dealSerialNo;
	private BigDecimal legNo;
	private BigDecimal cflNo;
	private BigDecimal rateNo;
	private BigDecimal observNo;
	private String indexId;
	private String obsFreq;
	private BigDecimal obsDate;
	private BigDecimal obsDateUnadj;
	private String dateAdjustMethod;
	private BigDecimal obsTime;
	private BigDecimal knowRate;
	private BigDecimal estimateRate;
	private String observStatus;
	private String reserve;
	private String reserve2;
	private String reserve3;

	public TmpTbobservId() {
	}

	public TmpTbobservId(String isBond, String dealSerialNo, BigDecimal legNo,
			BigDecimal cflNo, BigDecimal rateNo, BigDecimal observNo,
			String indexId, String obsFreq, BigDecimal obsDate,
			BigDecimal obsDateUnadj, String dateAdjustMethod,
			BigDecimal obsTime, BigDecimal knowRate, BigDecimal estimateRate,
			String observStatus, String reserve, String reserve2,
			String reserve3) {
		this.isBond = isBond;
		this.dealSerialNo = dealSerialNo;
		this.legNo = legNo;
		this.cflNo = cflNo;
		this.rateNo = rateNo;
		this.observNo = observNo;
		this.indexId = indexId;
		this.obsFreq = obsFreq;
		this.obsDate = obsDate;
		this.obsDateUnadj = obsDateUnadj;
		this.dateAdjustMethod = dateAdjustMethod;
		this.obsTime = obsTime;
		this.knowRate = knowRate;
		this.estimateRate = estimateRate;
		this.observStatus = observStatus;
		this.reserve = reserve;
		this.reserve2 = reserve2;
		this.reserve3 = reserve3;
	}

	public String getIsBond() {
		return this.isBond;
	}

	public void setIsBond(String isBond) {
		this.isBond = isBond;
	}

	public String getDealSerialNo() {
		return this.dealSerialNo;
	}

	public void setDealSerialNo(String dealSerialNo) {
		this.dealSerialNo = dealSerialNo;
	}

	public BigDecimal getLegNo() {
		return this.legNo;
	}

	public void setLegNo(BigDecimal legNo) {
		this.legNo = legNo;
	}

	public BigDecimal getCflNo() {
		return this.cflNo;
	}

	public void setCflNo(BigDecimal cflNo) {
		this.cflNo = cflNo;
	}

	public BigDecimal getRateNo() {
		return this.rateNo;
	}

	public void setRateNo(BigDecimal rateNo) {
		this.rateNo = rateNo;
	}

	public BigDecimal getObservNo() {
		return this.observNo;
	}

	public void setObservNo(BigDecimal observNo) {
		this.observNo = observNo;
	}

	public String getIndexId() {
		return this.indexId;
	}

	public void setIndexId(String indexId) {
		this.indexId = indexId;
	}

	public String getObsFreq() {
		return this.obsFreq;
	}

	public void setObsFreq(String obsFreq) {
		this.obsFreq = obsFreq;
	}

	public BigDecimal getObsDate() {
		return this.obsDate;
	}

	public void setObsDate(BigDecimal obsDate) {
		this.obsDate = obsDate;
	}

	public BigDecimal getObsDateUnadj() {
		return this.obsDateUnadj;
	}

	public void setObsDateUnadj(BigDecimal obsDateUnadj) {
		this.obsDateUnadj = obsDateUnadj;
	}

	public String getDateAdjustMethod() {
		return this.dateAdjustMethod;
	}

	public void setDateAdjustMethod(String dateAdjustMethod) {
		this.dateAdjustMethod = dateAdjustMethod;
	}

	public BigDecimal getObsTime() {
		return this.obsTime;
	}

	public void setObsTime(BigDecimal obsTime) {
		this.obsTime = obsTime;
	}

	public BigDecimal getKnowRate() {
		return this.knowRate;
	}

	public void setKnowRate(BigDecimal knowRate) {
		this.knowRate = knowRate;
	}

	public BigDecimal getEstimateRate() {
		return this.estimateRate;
	}

	public void setEstimateRate(BigDecimal estimateRate) {
		this.estimateRate = estimateRate;
	}

	public String getObservStatus() {
		return this.observStatus;
	}

	public void setObservStatus(String observStatus) {
		this.observStatus = observStatus;
	}

	public String getReserve() {
		return this.reserve;
	}

	public void setReserve(String reserve) {
		this.reserve = reserve;
	}

	public String getReserve2() {
		return this.reserve2;
	}

	public void setReserve2(String reserve2) {
		this.reserve2 = reserve2;
	}

	public String getReserve3() {
		return this.reserve3;
	}

	public void setReserve3(String reserve3) {
		this.reserve3 = reserve3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpTbobservId))
			return false;
		TmpTbobservId castOther = (TmpTbobservId) other;

		return ((this.getIsBond() == castOther.getIsBond()) || (this
				.getIsBond() != null && castOther.getIsBond() != null && this
				.getIsBond().equals(castOther.getIsBond())))
				&& ((this.getDealSerialNo() == castOther.getDealSerialNo()) || (this
						.getDealSerialNo() != null
						&& castOther.getDealSerialNo() != null && this
						.getDealSerialNo().equals(castOther.getDealSerialNo())))
				&& ((this.getLegNo() == castOther.getLegNo()) || (this
						.getLegNo() != null && castOther.getLegNo() != null && this
						.getLegNo().equals(castOther.getLegNo())))
				&& ((this.getCflNo() == castOther.getCflNo()) || (this
						.getCflNo() != null && castOther.getCflNo() != null && this
						.getCflNo().equals(castOther.getCflNo())))
				&& ((this.getRateNo() == castOther.getRateNo()) || (this
						.getRateNo() != null && castOther.getRateNo() != null && this
						.getRateNo().equals(castOther.getRateNo())))
				&& ((this.getObservNo() == castOther.getObservNo()) || (this
						.getObservNo() != null
						&& castOther.getObservNo() != null && this
						.getObservNo().equals(castOther.getObservNo())))
				&& ((this.getIndexId() == castOther.getIndexId()) || (this
						.getIndexId() != null && castOther.getIndexId() != null && this
						.getIndexId().equals(castOther.getIndexId())))
				&& ((this.getObsFreq() == castOther.getObsFreq()) || (this
						.getObsFreq() != null && castOther.getObsFreq() != null && this
						.getObsFreq().equals(castOther.getObsFreq())))
				&& ((this.getObsDate() == castOther.getObsDate()) || (this
						.getObsDate() != null && castOther.getObsDate() != null && this
						.getObsDate().equals(castOther.getObsDate())))
				&& ((this.getObsDateUnadj() == castOther.getObsDateUnadj()) || (this
						.getObsDateUnadj() != null
						&& castOther.getObsDateUnadj() != null && this
						.getObsDateUnadj().equals(castOther.getObsDateUnadj())))
				&& ((this.getDateAdjustMethod() == castOther
						.getDateAdjustMethod()) || (this.getDateAdjustMethod() != null
						&& castOther.getDateAdjustMethod() != null && this
						.getDateAdjustMethod().equals(
								castOther.getDateAdjustMethod())))
				&& ((this.getObsTime() == castOther.getObsTime()) || (this
						.getObsTime() != null && castOther.getObsTime() != null && this
						.getObsTime().equals(castOther.getObsTime())))
				&& ((this.getKnowRate() == castOther.getKnowRate()) || (this
						.getKnowRate() != null
						&& castOther.getKnowRate() != null && this
						.getKnowRate().equals(castOther.getKnowRate())))
				&& ((this.getEstimateRate() == castOther.getEstimateRate()) || (this
						.getEstimateRate() != null
						&& castOther.getEstimateRate() != null && this
						.getEstimateRate().equals(castOther.getEstimateRate())))
				&& ((this.getObservStatus() == castOther.getObservStatus()) || (this
						.getObservStatus() != null
						&& castOther.getObservStatus() != null && this
						.getObservStatus().equals(castOther.getObservStatus())))
				&& ((this.getReserve() == castOther.getReserve()) || (this
						.getReserve() != null && castOther.getReserve() != null && this
						.getReserve().equals(castOther.getReserve())))
				&& ((this.getReserve2() == castOther.getReserve2()) || (this
						.getReserve2() != null
						&& castOther.getReserve2() != null && this
						.getReserve2().equals(castOther.getReserve2())))
				&& ((this.getReserve3() == castOther.getReserve3()) || (this
						.getReserve3() != null
						&& castOther.getReserve3() != null && this
						.getReserve3().equals(castOther.getReserve3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIsBond() == null ? 0 : this.getIsBond().hashCode());
		result = 37
				* result
				+ (getDealSerialNo() == null ? 0 : this.getDealSerialNo()
						.hashCode());
		result = 37 * result
				+ (getLegNo() == null ? 0 : this.getLegNo().hashCode());
		result = 37 * result
				+ (getCflNo() == null ? 0 : this.getCflNo().hashCode());
		result = 37 * result
				+ (getRateNo() == null ? 0 : this.getRateNo().hashCode());
		result = 37 * result
				+ (getObservNo() == null ? 0 : this.getObservNo().hashCode());
		result = 37 * result
				+ (getIndexId() == null ? 0 : this.getIndexId().hashCode());
		result = 37 * result
				+ (getObsFreq() == null ? 0 : this.getObsFreq().hashCode());
		result = 37 * result
				+ (getObsDate() == null ? 0 : this.getObsDate().hashCode());
		result = 37
				* result
				+ (getObsDateUnadj() == null ? 0 : this.getObsDateUnadj()
						.hashCode());
		result = 37
				* result
				+ (getDateAdjustMethod() == null ? 0 : this
						.getDateAdjustMethod().hashCode());
		result = 37 * result
				+ (getObsTime() == null ? 0 : this.getObsTime().hashCode());
		result = 37 * result
				+ (getKnowRate() == null ? 0 : this.getKnowRate().hashCode());
		result = 37
				* result
				+ (getEstimateRate() == null ? 0 : this.getEstimateRate()
						.hashCode());
		result = 37
				* result
				+ (getObservStatus() == null ? 0 : this.getObservStatus()
						.hashCode());
		result = 37 * result
				+ (getReserve() == null ? 0 : this.getReserve().hashCode());
		result = 37 * result
				+ (getReserve2() == null ? 0 : this.getReserve2().hashCode());
		result = 37 * result
				+ (getReserve3() == null ? 0 : this.getReserve3().hashCode());
		return result;
	}

}
