package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbinstrate generated by hbm2java
 */
public class TmpTbinstrate implements java.io.Serializable {

	private TmpTbinstrateId id;

	public TmpTbinstrate() {
	}

	public TmpTbinstrate(TmpTbinstrateId id) {
		this.id = id;
	}

	public TmpTbinstrateId getId() {
		return this.id;
	}

	public void setId(TmpTbinstrateId id) {
		this.id = id;
	}

}
