package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbinstratevar generated by hbm2java
 */
public class TmpTbinstratevar implements java.io.Serializable {

	private TmpTbinstratevarId id;

	public TmpTbinstratevar() {
	}

	public TmpTbinstratevar(TmpTbinstratevarId id) {
		this.id = id;
	}

	public TmpTbinstratevarId getId() {
		return this.id;
	}

	public void setId(TmpTbinstratevarId id) {
		this.id = id;
	}

}
