package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbissueunitstock generated by hbm2java
 */
public class TmpTbissueunitstock implements java.io.Serializable {

	private TmpTbissueunitstockId id;

	public TmpTbissueunitstock() {
	}

	public TmpTbissueunitstock(TmpTbissueunitstockId id) {
		this.id = id;
	}

	public TmpTbissueunitstockId getId() {
		return this.id;
	}

	public void setId(TmpTbissueunitstockId id) {
		this.id = id;
	}

}
