package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbdealhgmortagage generated by hbm2java
 */
public class TmpTbdealhgmortagage implements java.io.Serializable {

	private TmpTbdealhgmortagageId id;

	public TmpTbdealhgmortagage() {
	}

	public TmpTbdealhgmortagage(TmpTbdealhgmortagageId id) {
		this.id = id;
	}

	public TmpTbdealhgmortagageId getId() {
		return this.id;
	}

	public void setId(TmpTbdealhgmortagageId id) {
		this.id = id;
	}

}
