package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TmpTbpendsettle generated by hbm2java
 */
public class TmpTbpendsettle implements java.io.Serializable {

	private TmpTbpendsettleId id;

	public TmpTbpendsettle() {
	}

	public TmpTbpendsettle(TmpTbpendsettleId id) {
		this.id = id;
	}

	public TmpTbpendsettleId getId() {
		return this.id;
	}

	public void setId(TmpTbpendsettleId id) {
		this.id = id;
	}

}
