package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TmpVersion generated by hbm2java
 */
public class TmpVersion implements java.io.Serializable {

	private BigDecimal versionId;

	public TmpVersion() {
	}

	public TmpVersion(BigDecimal versionId) {
		this.versionId = versionId;
	}

	public BigDecimal getVersionId() {
		return this.versionId;
	}

	public void setVersionId(BigDecimal versionId) {
		this.versionId = versionId;
	}

}
