package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysStdType generated by hbm2java
 */
public class TsysStdType implements java.io.Serializable {

	private String stdTypeCode;
	private String stdTypeName;

	public TsysStdType() {
	}

	public TsysStdType(String stdTypeCode) {
		this.stdTypeCode = stdTypeCode;
	}

	public TsysStdType(String stdTypeCode, String stdTypeName) {
		this.stdTypeCode = stdTypeCode;
		this.stdTypeName = stdTypeName;
	}

	public String getStdTypeCode() {
		return this.stdTypeCode;
	}

	public void setStdTypeCode(String stdTypeCode) {
		this.stdTypeCode = stdTypeCode;
	}

	public String getStdTypeName() {
		return this.stdTypeName;
	}

	public void setStdTypeName(String stdTypeName) {
		this.stdTypeName = stdTypeName;
	}

}
