package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysOfficeUserId generated by hbm2java
 */
public class TsysOfficeUserId implements java.io.Serializable {

	private String userId;
	private String officeCode;

	public TsysOfficeUserId() {
	}

	public TsysOfficeUserId(String userId, String officeCode) {
		this.userId = userId;
		this.officeCode = officeCode;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getOfficeCode() {
		return this.officeCode;
	}

	public void setOfficeCode(String officeCode) {
		this.officeCode = officeCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsysOfficeUserId))
			return false;
		TsysOfficeUserId castOther = (TsysOfficeUserId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getOfficeCode() == castOther.getOfficeCode()) || (this
						.getOfficeCode() != null
						&& castOther.getOfficeCode() != null && this
						.getOfficeCode().equals(castOther.getOfficeCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37
				* result
				+ (getOfficeCode() == null ? 0 : this.getOfficeCode()
						.hashCode());
		return result;
	}

}
