package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TsysMenu generated by hbm2java
 */
public class TsysMenu implements java.io.Serializable {

	private TsysMenuId id;
	private String transCode;
	private String subTransCode;
	private String menuName;
	private String menuArg;
	private String menuIcon;
	private String windowType;
	private String tip;
	private String hotKey;
	private String parentCode;
	private BigDecimal orderNo;
	private String openFlag;
	private String treeIdx;
	private String remark;
	private String windowModel;
	private String menuUrl;

	public TsysMenu() {
	}

	public TsysMenu(TsysMenuId id, String menuName) {
		this.id = id;
		this.menuName = menuName;
	}

	public TsysMenu(TsysMenuId id, String transCode, String subTransCode,
			String menuName, String menuArg, String menuIcon,
			String windowType, String tip, String hotKey, String parentCode,
			BigDecimal orderNo, String openFlag, String treeIdx, String remark,
			String windowModel, String menuUrl) {
		this.id = id;
		this.transCode = transCode;
		this.subTransCode = subTransCode;
		this.menuName = menuName;
		this.menuArg = menuArg;
		this.menuIcon = menuIcon;
		this.windowType = windowType;
		this.tip = tip;
		this.hotKey = hotKey;
		this.parentCode = parentCode;
		this.orderNo = orderNo;
		this.openFlag = openFlag;
		this.treeIdx = treeIdx;
		this.remark = remark;
		this.windowModel = windowModel;
		this.menuUrl = menuUrl;
	}

	public TsysMenuId getId() {
		return this.id;
	}

	public void setId(TsysMenuId id) {
		this.id = id;
	}

	public String getTransCode() {
		return this.transCode;
	}

	public void setTransCode(String transCode) {
		this.transCode = transCode;
	}

	public String getSubTransCode() {
		return this.subTransCode;
	}

	public void setSubTransCode(String subTransCode) {
		this.subTransCode = subTransCode;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuArg() {
		return this.menuArg;
	}

	public void setMenuArg(String menuArg) {
		this.menuArg = menuArg;
	}

	public String getMenuIcon() {
		return this.menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon;
	}

	public String getWindowType() {
		return this.windowType;
	}

	public void setWindowType(String windowType) {
		this.windowType = windowType;
	}

	public String getTip() {
		return this.tip;
	}

	public void setTip(String tip) {
		this.tip = tip;
	}

	public String getHotKey() {
		return this.hotKey;
	}

	public void setHotKey(String hotKey) {
		this.hotKey = hotKey;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public BigDecimal getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(BigDecimal orderNo) {
		this.orderNo = orderNo;
	}

	public String getOpenFlag() {
		return this.openFlag;
	}

	public void setOpenFlag(String openFlag) {
		this.openFlag = openFlag;
	}

	public String getTreeIdx() {
		return this.treeIdx;
	}

	public void setTreeIdx(String treeIdx) {
		this.treeIdx = treeIdx;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getWindowModel() {
		return this.windowModel;
	}

	public void setWindowModel(String windowModel) {
		this.windowModel = windowModel;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

}
