package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysOfficeUser generated by hbm2java
 */
public class TsysOfficeUser implements java.io.Serializable {

	private TsysOfficeUserId id;

	public TsysOfficeUser() {
	}

	public TsysOfficeUser(TsysOfficeUserId id) {
		this.id = id;
	}

	public TsysOfficeUserId getId() {
		return this.id;
	}

	public void setId(TsysOfficeUserId id) {
		this.id = id;
	}

}
