package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysRoleUser generated by hbm2java
 */
public class TsysRoleUser implements java.io.Serializable {

	private TsysRoleUserId id;

	public TsysRoleUser() {
	}

	public TsysRoleUser(TsysRoleUserId id) {
		this.id = id;
	}

	public TsysRoleUserId getId() {
		return this.id;
	}

	public void setId(TsysRoleUserId id) {
		this.id = id;
	}

}
