package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysMenuId generated by hbm2java
 */
public class TsysMenuId implements java.io.Serializable {

	private String menuCode;
	private String kindCode;

	public TsysMenuId() {
	}

	public TsysMenuId(String menuCode, String kindCode) {
		this.menuCode = menuCode;
		this.kindCode = kindCode;
	}

	public String getMenuCode() {
		return this.menuCode;
	}

	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsysMenuId))
			return false;
		TsysMenuId castOther = (TsysMenuId) other;

		return ((this.getMenuCode() == castOther.getMenuCode()) || (this
				.getMenuCode() != null && castOther.getMenuCode() != null && this
				.getMenuCode().equals(castOther.getMenuCode())))
				&& ((this.getKindCode() == castOther.getKindCode()) || (this
						.getKindCode() != null
						&& castOther.getKindCode() != null && this
						.getKindCode().equals(castOther.getKindCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getMenuCode() == null ? 0 : this.getMenuCode().hashCode());
		result = 37 * result
				+ (getKindCode() == null ? 0 : this.getKindCode().hashCode());
		return result;
	}

}
