package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysDefValue generated by hbm2java
 */
public class TsysDefValue implements java.io.Serializable {

	private String defValueCode;
	private String defValueName;
	private String defValue;

	public TsysDefValue() {
	}

	public TsysDefValue(String defValueCode) {
		this.defValueCode = defValueCode;
	}

	public TsysDefValue(String defValueCode, String defValueName,
			String defValue) {
		this.defValueCode = defValueCode;
		this.defValueName = defValueName;
		this.defValue = defValue;
	}

	public String getDefValueCode() {
		return this.defValueCode;
	}

	public void setDefValueCode(String defValueCode) {
		this.defValueCode = defValueCode;
	}

	public String getDefValueName() {
		return this.defValueName;
	}

	public void setDefValueName(String defValueName) {
		this.defValueName = defValueName;
	}

	public String getDefValue() {
		return this.defValue;
	}

	public void setDefValue(String defValue) {
		this.defValue = defValue;
	}

}
