package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysDictEntry generated by hbm2java
 */
public class TsysDictEntry implements java.io.Serializable {

	private String dictEntryCode;
	private String dictEntryName;
	private String kindCode;
	private String ctrlFlag;
	private String remark;

	public TsysDictEntry() {
	}

	public TsysDictEntry(String dictEntryCode, String dictEntryName) {
		this.dictEntryCode = dictEntryCode;
		this.dictEntryName = dictEntryName;
	}

	public TsysDictEntry(String dictEntryCode, String dictEntryName,
			String kindCode, String ctrlFlag, String remark) {
		this.dictEntryCode = dictEntryCode;
		this.dictEntryName = dictEntryName;
		this.kindCode = kindCode;
		this.ctrlFlag = ctrlFlag;
		this.remark = remark;
	}

	public String getDictEntryCode() {
		return this.dictEntryCode;
	}

	public void setDictEntryCode(String dictEntryCode) {
		this.dictEntryCode = dictEntryCode;
	}

	public String getDictEntryName() {
		return this.dictEntryName;
	}

	public void setDictEntryName(String dictEntryName) {
		this.dictEntryName = dictEntryName;
	}

	public String getKindCode() {
		return this.kindCode;
	}

	public void setKindCode(String kindCode) {
		this.kindCode = kindCode;
	}

	public String getCtrlFlag() {
		return this.ctrlFlag;
	}

	public void setCtrlFlag(String ctrlFlag) {
		this.ctrlFlag = ctrlFlag;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
