package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysDbSource generated by hbm2java
 */
public class TsysDbSource implements java.io.Serializable {

	private TsysDbSourceId id;
	private String dbDialect;
	private String dbDriver;
	private String remark;

	public TsysDbSource() {
	}

	public TsysDbSource(TsysDbSourceId id) {
		this.id = id;
	}

	public TsysDbSource(TsysDbSourceId id, String dbDialect, String dbDriver,
			String remark) {
		this.id = id;
		this.dbDialect = dbDialect;
		this.dbDriver = dbDriver;
		this.remark = remark;
	}

	public TsysDbSourceId getId() {
		return this.id;
	}

	public void setId(TsysDbSourceId id) {
		this.id = id;
	}

	public String getDbDialect() {
		return this.dbDialect;
	}

	public void setDbDialect(String dbDialect) {
		this.dbDialect = dbDialect;
	}

	public String getDbDriver() {
		return this.dbDriver;
	}

	public void setDbDriver(String dbDriver) {
		this.dbDriver = dbDriver;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
