package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

import java.math.BigDecimal;

/**
 * TsysUserRightId generated by hbm2java
 */
public class TsysUserRightId implements java.io.Serializable {

	private String transCode;
	private String subTransCode;
	private String userId;
	private BigDecimal beginDate;
	private BigDecimal endDate;
	private String rightFlag;

	public TsysUserRightId() {
	}

	public TsysUserRightId(String transCode, String subTransCode,
			String userId, BigDecimal beginDate, BigDecimal endDate,
			String rightFlag) {
		this.transCode = transCode;
		this.subTransCode = subTransCode;
		this.userId = userId;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.rightFlag = rightFlag;
	}

	public String getTransCode() {
		return this.transCode;
	}

	public void setTransCode(String transCode) {
		this.transCode = transCode;
	}

	public String getSubTransCode() {
		return this.subTransCode;
	}

	public void setSubTransCode(String subTransCode) {
		this.subTransCode = subTransCode;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public BigDecimal getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(BigDecimal beginDate) {
		this.beginDate = beginDate;
	}

	public BigDecimal getEndDate() {
		return this.endDate;
	}

	public void setEndDate(BigDecimal endDate) {
		this.endDate = endDate;
	}

	public String getRightFlag() {
		return this.rightFlag;
	}

	public void setRightFlag(String rightFlag) {
		this.rightFlag = rightFlag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsysUserRightId))
			return false;
		TsysUserRightId castOther = (TsysUserRightId) other;

		return ((this.getTransCode() == castOther.getTransCode()) || (this
				.getTransCode() != null && castOther.getTransCode() != null && this
				.getTransCode().equals(castOther.getTransCode())))
				&& ((this.getSubTransCode() == castOther.getSubTransCode()) || (this
						.getSubTransCode() != null
						&& castOther.getSubTransCode() != null && this
						.getSubTransCode().equals(castOther.getSubTransCode())))
				&& ((this.getUserId() == castOther.getUserId()) || (this
						.getUserId() != null && castOther.getUserId() != null && this
						.getUserId().equals(castOther.getUserId())))
				&& ((this.getBeginDate() == castOther.getBeginDate()) || (this
						.getBeginDate() != null
						&& castOther.getBeginDate() != null && this
						.getBeginDate().equals(castOther.getBeginDate())))
				&& ((this.getEndDate() == castOther.getEndDate()) || (this
						.getEndDate() != null && castOther.getEndDate() != null && this
						.getEndDate().equals(castOther.getEndDate())))
				&& ((this.getRightFlag() == castOther.getRightFlag()) || (this
						.getRightFlag() != null
						&& castOther.getRightFlag() != null && this
						.getRightFlag().equals(castOther.getRightFlag())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTransCode() == null ? 0 : this.getTransCode().hashCode());
		result = 37
				* result
				+ (getSubTransCode() == null ? 0 : this.getSubTransCode()
						.hashCode());
		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getBeginDate() == null ? 0 : this.getBeginDate().hashCode());
		result = 37 * result
				+ (getEndDate() == null ? 0 : this.getEndDate().hashCode());
		result = 37 * result
				+ (getRightFlag() == null ? 0 : this.getRightFlag().hashCode());
		return result;
	}

}
