package com.bfm.db.bean;

// Generated 2015-11-18 13:51:58 by Hibernate Tools 4.0.0

/**
 * TsysBranch generated by hbm2java
 */
public class TsysBranch implements java.io.Serializable {

	private String branchCode;
	private String branchLevel;
	private String branchName;
	private String shortName;
	private String parentCode;
	private String branchPath;
	private String remark;
	private String extField1;
	private String extField2;
	private String extField3;
	private String branchType;

	public TsysBranch() {
	}

	public TsysBranch(String branchCode) {
		this.branchCode = branchCode;
	}

	public TsysBranch(String branchCode, String branchLevel, String branchName,
			String shortName, String parentCode, String branchPath,
			String remark, String extField1, String extField2,
			String extField3, String branchType) {
		this.branchCode = branchCode;
		this.branchLevel = branchLevel;
		this.branchName = branchName;
		this.shortName = shortName;
		this.parentCode = parentCode;
		this.branchPath = branchPath;
		this.remark = remark;
		this.extField1 = extField1;
		this.extField2 = extField2;
		this.extField3 = extField3;
		this.branchType = branchType;
	}

	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	public String getBranchLevel() {
		return this.branchLevel;
	}

	public void setBranchLevel(String branchLevel) {
		this.branchLevel = branchLevel;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	public String getBranchPath() {
		return this.branchPath;
	}

	public void setBranchPath(String branchPath) {
		this.branchPath = branchPath;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getExtField1() {
		return this.extField1;
	}

	public void setExtField1(String extField1) {
		this.extField1 = extField1;
	}

	public String getExtField2() {
		return this.extField2;
	}

	public void setExtField2(String extField2) {
		this.extField2 = extField2;
	}

	public String getExtField3() {
		return this.extField3;
	}

	public void setExtField3(String extField3) {
		this.extField3 = extField3;
	}

	public String getBranchType() {
		return this.branchType;
	}

	public void setBranchType(String branchType) {
		this.branchType = branchType;
	}

}
